#pragma once

// standard allows way simpler implementation
// but this one is proven to work in MSVC

#define DAS_EXPAND(x) x
#define  DAS_FOR_EACH_1(WHAT, ARG, X) WHAT(X, ARG)
#define  DAS_FOR_EACH_2(WHAT, ARG, X, ...) WHAT(X, ARG) DAS_EXPAND(DAS_FOR_EACH_1(WHAT, ARG, __VA_ARGS__))
#define  DAS_FOR_EACH_3(WHAT, ARG, X, ...) WHAT(X, ARG) DAS_EXPAND(DAS_FOR_EACH_2(WHAT, ARG, __VA_ARGS__))
#define  DAS_FOR_EACH_4(WHAT, ARG, X, ...) WHAT(X, ARG) DAS_EXPAND(DAS_FOR_EACH_3(WHAT, ARG, __VA_ARGS__))
#define  DAS_FOR_EACH_5(WHAT, ARG, X, ...) WHAT(X, ARG) DAS_EXPAND(DAS_FOR_EACH_4(WHAT, ARG, __VA_ARGS__))
#define  DAS_FOR_EACH_6(WHAT, ARG, X, ...) WHAT(X, ARG) DAS_EXPAND(DAS_FOR_EACH_5(WHAT, ARG, __VA_ARGS__))
#define  DAS_FOR_EACH_7(WHAT, ARG, X, ...) WHAT(X, ARG) DAS_EXPAND(DAS_FOR_EACH_6(WHAT, ARG, __VA_ARGS__))
#define  DAS_FOR_EACH_8(WHAT, ARG, X, ...) WHAT(X, ARG) DAS_EXPAND(DAS_FOR_EACH_7(WHAT, ARG, __VA_ARGS__))
#define  DAS_FOR_EACH_9(WHAT, ARG, X, ...) WHAT(X, ARG) DAS_EXPAND(DAS_FOR_EACH_8(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_10(WHAT, ARG, X, ...) WHAT(X, ARG) DAS_EXPAND(DAS_FOR_EACH_9(WHAT, ARG, __VA_ARGS__))

#define DAS_FOR_EACH_11(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_10(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_12(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_11(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_13(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_12(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_14(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_13(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_15(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_14(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_16(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_15(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_17(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_16(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_18(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_17(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_19(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_18(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_20(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_19(WHAT, ARG, __VA_ARGS__))

#define DAS_FOR_EACH_21(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_20(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_22(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_21(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_23(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_22(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_24(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_23(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_25(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_24(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_26(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_25(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_27(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_26(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_28(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_27(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_29(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_28(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_30(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_29(WHAT, ARG, __VA_ARGS__))

#define DAS_FOR_EACH_31(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_30(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_32(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_31(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_33(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_32(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_34(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_33(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_35(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_34(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_36(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_35(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_37(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_36(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_38(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_37(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_39(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_38(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_40(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_39(WHAT, ARG, __VA_ARGS__))

#define DAS_FOR_EACH_41(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_40(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_42(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_41(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_43(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_42(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_44(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_43(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_45(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_44(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_46(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_45(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_47(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_46(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_48(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_47(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_49(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_48(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_50(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_49(WHAT, ARG, __VA_ARGS__))

//... repeat as needed

#define DAS_FOR_EACH_NARG(...) DAS_FOR_EACH_NARG_(__VA_ARGS__, DAS_FOR_EACH_RSEQ_N())
#define DAS_FOR_EACH_NARG_(...) DAS_EXPAND(DAS_FOR_EACH_ARG_N(__VA_ARGS__))
#define DAS_FOR_EACH_ARG_N( \
     _1,  _2,  _3,  _4,  _5,  _6,  _7,  _8,  _9, _10, \
    _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, \
    _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, \
    _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, \
    _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, \
    N, ...) N
#define DAS_FOR_EACH_RSEQ_N() \
    50, 49, 48, 47, 46, 45, 44, 43, 42, 41, \
    40, 39, 38, 37, 36, 35, 34, 33, 32, 31, \
    30, 29, 28, 27, 26, 25, 24, 23, 22, 21, \
    20, 19, 18, 17, 16, 15, 14, 13, 12, 11, \
    10, 9,  8,  7,  6,  5,  4,  3,  2,  1, 0
#define CONCATENATE(x,y) x##y
#define DAS_FOR_EACH_(N, what, arg, ...) DAS_EXPAND(CONCATENATE(DAS_FOR_EACH_, N)(what, arg, __VA_ARGS__))
#define DAS_FOR_EACH(what, arg, ...) DAS_FOR_EACH_(DAS_FOR_EACH_NARG(__VA_ARGS__), what, arg, __VA_ARGS__)
