#pragma once

// standard allows way simpler implementation
// but this one is proven to work in MSVC

#define DAS_EXPAND(x) x
#define  DAS_FOR_EACH_1(WHAT, ARG, X) WHAT(X, ARG)
#define  DAS_FOR_EACH_2(WHAT, ARG, X, ...) WHAT(X, ARG) DAS_EXPAND(DAS_FOR_EACH_1(WHAT, ARG, __VA_ARGS__))
#define  DAS_FOR_EACH_3(WHAT, ARG, X, ...) WHAT(X, ARG) DAS_EXPAND(DAS_FOR_EACH_2(WHAT, ARG, __VA_ARGS__))
#define  DAS_FOR_EACH_4(WHAT, ARG, X, ...) WHAT(X, ARG) DAS_EXPAND(DAS_FOR_EACH_3(WHAT, ARG, __VA_ARGS__))
#define  DAS_FOR_EACH_5(WHAT, ARG, X, ...) WHAT(X, ARG) DAS_EXPAND(DAS_FOR_EACH_4(WHAT, ARG, __VA_ARGS__))
#define  DAS_FOR_EACH_6(WHAT, ARG, X, ...) WHAT(X, ARG) DAS_EXPAND(DAS_FOR_EACH_5(WHAT, ARG, __VA_ARGS__))
#define  DAS_FOR_EACH_7(WHAT, ARG, X, ...) WHAT(X, ARG) DAS_EXPAND(DAS_FOR_EACH_6(WHAT, ARG, __VA_ARGS__))
#define  DAS_FOR_EACH_8(WHAT, ARG, X, ...) WHAT(X, ARG) DAS_EXPAND(DAS_FOR_EACH_7(WHAT, ARG, __VA_ARGS__))
#define  DAS_FOR_EACH_9(WHAT, ARG, X, ...) WHAT(X, ARG) DAS_EXPAND(DAS_FOR_EACH_8(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_10(WHAT, ARG, X, ...) WHAT(X, ARG) DAS_EXPAND(DAS_FOR_EACH_9(WHAT, ARG, __VA_ARGS__))

#define DAS_FOR_EACH_11(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_10(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_12(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_11(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_13(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_12(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_14(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_13(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_15(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_14(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_16(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_15(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_17(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_16(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_18(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_17(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_19(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_18(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_20(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_19(WHAT, ARG, __VA_ARGS__))

#define DAS_FOR_EACH_21(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_20(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_22(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_21(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_23(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_22(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_24(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_23(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_25(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_24(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_26(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_25(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_27(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_26(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_28(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_27(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_29(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_28(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_30(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_29(WHAT, ARG, __VA_ARGS__))

#define DAS_FOR_EACH_31(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_30(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_32(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_31(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_33(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_32(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_34(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_33(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_35(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_34(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_36(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_35(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_37(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_36(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_38(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_37(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_39(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_38(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_40(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_39(WHAT, ARG, __VA_ARGS__))

#define DAS_FOR_EACH_41(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_40(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_42(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_41(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_43(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_42(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_44(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_43(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_45(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_44(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_46(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_45(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_47(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_46(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_48(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_47(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_49(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_48(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_50(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_49(WHAT, ARG, __VA_ARGS__))

#define DAS_FOR_EACH_51(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_50(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_52(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_51(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_53(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_52(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_54(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_53(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_55(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_54(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_56(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_55(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_57(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_56(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_58(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_57(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_59(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_58(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_60(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_59(WHAT, ARG, __VA_ARGS__))

#define DAS_FOR_EACH_61(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_60(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_62(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_61(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_63(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_62(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_64(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_63(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_65(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_64(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_66(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_65(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_67(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_66(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_68(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_67(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_69(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_68(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_70(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_69(WHAT, ARG, __VA_ARGS__))

#define DAS_FOR_EACH_71(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_70(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_72(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_71(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_73(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_72(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_74(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_73(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_75(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_74(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_76(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_75(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_77(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_76(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_78(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_77(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_79(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_78(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_80(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_79(WHAT, ARG, __VA_ARGS__))

#define DAS_FOR_EACH_81(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_80(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_82(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_81(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_83(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_82(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_84(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_83(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_85(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_84(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_86(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_85(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_87(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_86(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_88(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_87(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_89(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_88(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_90(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_89(WHAT, ARG, __VA_ARGS__))

#define DAS_FOR_EACH_91(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_90(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_92(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_91(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_93(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_92(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_94(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_93(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_95(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_94(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_96(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_95(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_97(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_96(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_98(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_97(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_99(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_98(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_100(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_99(WHAT, ARG, __VA_ARGS__))

#define DAS_FOR_EACH_101(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_100(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_102(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_101(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_103(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_102(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_104(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_103(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_105(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_104(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_106(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_105(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_107(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_106(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_108(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_107(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_109(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_108(WHAT, ARG, __VA_ARGS__))
#define DAS_FOR_EACH_110(WHAT, ARG, X, ...) WHAT(X, ARG)DAS_EXPAND(DAS_FOR_EACH_109(WHAT, ARG, __VA_ARGS__))


//... repeat as needed

#define DAS_FOR_EACH_NARG(...) DAS_FOR_EACH_NARG_(__VA_ARGS__, DAS_FOR_EACH_RSEQ_N())
#define DAS_FOR_EACH_NARG_(...) DAS_EXPAND(DAS_FOR_EACH_ARG_N(__VA_ARGS__))
#define DAS_FOR_EACH_ARG_N( \
     _1,  _2,  _3,  _4,  _5,  _6,  _7,  _8,  _9, _10, \
    _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, \
    _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, \
    _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, \
    _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, \
    _51, _52, _53, _54, _55, _56, _57, _58, _59, _60, \
    _61, _62, _63, _64, _65, _66, _67, _68, _69, _70, \
    _71, _72, _73, _74, _75, _76, _77, _78, _79, _80, \
    _81, _82, _83, _84, _85, _86, _87, _88, _89, _90, \
    _91, _92, _93, _94, _95, _96, _97, _98, _99, _100, \
    _101, _102, _103, _104, _105, _106, _107, _108, _109, _110, \
    N, ...) N
#define DAS_FOR_EACH_RSEQ_N() \
    110, 109, 108, 107, 106, 105, 104, 103, 102, 101, \
    100, 99, 98, 97, 96, 95, 94, 93, 92, 91, \
    90, 89, 88, 87, 86, 85, 84, 83, 82, 81, \
    80, 79, 78, 77, 76, 75, 74, 73, 72, 71, \
    70, 69, 68, 67, 66, 65, 64, 63, 62, 61, \
    60, 59, 58, 57, 56, 55, 54, 53, 52, 51, \
    50, 49, 48, 47, 46, 45, 44, 43, 42, 41, \
    40, 39, 38, 37, 36, 35, 34, 33, 32, 31, \
    30, 29, 28, 27, 26, 25, 24, 23, 22, 21, \
    20, 19, 18, 17, 16, 15, 14, 13, 12, 11, \
    10, 9,  8,  7,  6,  5,  4,  3,  2,  1, 0
#define CONCATENATE(x,y) x##y
#define DAS_FOR_EACH_(N, what, arg, ...) DAS_EXPAND(CONCATENATE(DAS_FOR_EACH_, N)(what, arg, __VA_ARGS__))
#define DAS_FOR_EACH(what, arg, ...) DAS_FOR_EACH_(DAS_FOR_EACH_NARG(__VA_ARGS__), what, arg, __VA_ARGS__)
