#! /bin/sh
echo "[  0%] aclocal"
aclocal || exit 1

echo "[ 20%] libtoolize"
libtoolize --copy --force || exit 1

echo "[ 40%] autoconf"
autoconf || exit 1

echo "[ 60%] autoheader"
autoheader || exit 1

echo "[ 80%] automake"
automake --gnu --add-missing --copy || exit 1

echo "[100%] ."
