# sweep_contexts.h for sweep_driver.c: one include per context that emitted an entry point, the
# rest as an X-macro. Contexts linking C++ modules run first and one is held open for the sweep -
# they bind the thread environment in a base class, and the global AOT library pass needs it.

string(REPLACE "|" ";" _files "${FILES}")
set(_includes "")
set(_list "")
set(_with_modules "")
set(_skipped 0)
foreach(_f IN LISTS _files)
    get_filename_component(_dir ${_f} DIRECTORY)
    get_filename_component(_name ${_f} NAME)
    set(_gen "${_dir}/_standalone_ctx_generated/${_name}")
    set(_entry "")
    if(EXISTS "${_gen}.h")
        # the prefix escapes a keyword stem (enum -> enum_), so read it rather than assume it
        file(STRINGS "${_gen}.h" _entry REGEX "_ctx \\* [A-Za-z_][A-Za-z0-9_]*_create\\(void\\)" LIMIT_COUNT 1)
    endif()
    string(REGEX MATCH "_ctx \\* ([A-Za-z_][A-Za-z0-9_]*)_create" _unused "${_entry}")
    if(NOT _entry OR CMAKE_MATCH_1 STREQUAL "")
        math(EXPR _skipped "${_skipped} + 1")
        continue()
    endif()
    string(APPEND _includes "#include \"${_gen}.h\"\n")
    set(_mods "")
    if(EXISTS "${_gen}.cpp")
        file(STRINGS "${_gen}.cpp" _mods REGEX "standalone_modules\\.h" LIMIT_COUNT 1)
    endif()
    if(_mods)
        string(APPEND _with_modules "    RUN(${CMAKE_MATCH_1}); \\\n")
    else()
        string(APPEND _list "    RUN(${CMAKE_MATCH_1}); \\\n")
    endif()
endforeach()

set(_anchor_call "")
if(NOT _with_modules STREQUAL "")
    string(REGEX MATCH "RUN\\(([A-Za-z_][A-Za-z0-9_]*)\\)" _unused "${_with_modules}")
    set(_anchor_call "A(${CMAKE_MATCH_1})")
endif()

file(WRITE ${OUT} "/* Generated by sweep_contexts.cmake. DO NOT EDIT. */
${_includes}
#define SWEEP_ANCHOR(A) ${_anchor_call}
#define SWEEP_CONTEXTS(RUN) \\
${_with_modules}${_list}    /* end */

")
message(STATUS "standalone sweep: ${_skipped} contexts skipped by the emitter")
