// generated by generator/generate.das -- DO NOT EDIT

#include "dasVULKAN.h"

namespace das {

#if defined(VK_NV_ray_tracing)
struct VkGeometryNV_Ann : ManagedStructureAnnotation<VkGeometryNV> {
    VkGeometryNV_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkGeometryNV", ml, "VkGeometryNV") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkGeometryNV_Ann * ann_VkGeometryNV = nullptr;
void VkGeometryNV_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkGeometryNV, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(geometryType)>("geometryType", "geometryType");
    addField<DAS_BIND_MANAGED_FIELD(geometry)>("geometry", "geometry");
    addFieldEx("flags", "flags", offsetof(VkGeometryNV, flags), makeVkFlags_VkGeometryFlagsKHR());
}
#endif

#if defined(VK_NV_ray_tracing)
struct VkBindAccelerationStructureMemoryInfoNV_Ann : ManagedStructureAnnotation<VkBindAccelerationStructureMemoryInfoNV> {
    VkBindAccelerationStructureMemoryInfoNV_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkBindAccelerationStructureMemoryInfoNV", ml, "VkBindAccelerationStructureMemoryInfoNV") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkBindAccelerationStructureMemoryInfoNV_Ann * ann_VkBindAccelerationStructureMemoryInfoNV = nullptr;
void VkBindAccelerationStructureMemoryInfoNV_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkBindAccelerationStructureMemoryInfoNV, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(accelerationStructure)>("accelerationStructure", "accelerationStructure");
    addField<DAS_BIND_MANAGED_FIELD(memory)>("memory", "memory");
    addField<DAS_BIND_MANAGED_FIELD(memoryOffset)>("memoryOffset", "memoryOffset");
    addField<DAS_BIND_MANAGED_FIELD(deviceIndexCount)>("deviceIndexCount", "deviceIndexCount");
    addFieldEx("pDeviceIndices", "pDeviceIndices", offsetof(VkBindAccelerationStructureMemoryInfoNV, pDeviceIndices), makeType<uint32_t *>(*mlib));
}
#endif

#if defined(VK_KHR_acceleration_structure)
struct VkWriteDescriptorSetAccelerationStructureKHR_Ann : ManagedStructureAnnotation<VkWriteDescriptorSetAccelerationStructureKHR> {
    VkWriteDescriptorSetAccelerationStructureKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkWriteDescriptorSetAccelerationStructureKHR", ml, "VkWriteDescriptorSetAccelerationStructureKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkWriteDescriptorSetAccelerationStructureKHR_Ann * ann_VkWriteDescriptorSetAccelerationStructureKHR = nullptr;
void VkWriteDescriptorSetAccelerationStructureKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkWriteDescriptorSetAccelerationStructureKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(accelerationStructureCount)>("accelerationStructureCount", "accelerationStructureCount");
    addFieldEx("pAccelerationStructures", "pAccelerationStructures", offsetof(VkWriteDescriptorSetAccelerationStructureKHR, pAccelerationStructures), makeType<VkAccelerationStructureKHR *>(*mlib));
}
#endif

#if defined(VK_NV_ray_tracing)
struct VkWriteDescriptorSetAccelerationStructureNV_Ann : ManagedStructureAnnotation<VkWriteDescriptorSetAccelerationStructureNV> {
    VkWriteDescriptorSetAccelerationStructureNV_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkWriteDescriptorSetAccelerationStructureNV", ml, "VkWriteDescriptorSetAccelerationStructureNV") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkWriteDescriptorSetAccelerationStructureNV_Ann * ann_VkWriteDescriptorSetAccelerationStructureNV = nullptr;
void VkWriteDescriptorSetAccelerationStructureNV_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkWriteDescriptorSetAccelerationStructureNV, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(accelerationStructureCount)>("accelerationStructureCount", "accelerationStructureCount");
    addFieldEx("pAccelerationStructures", "pAccelerationStructures", offsetof(VkWriteDescriptorSetAccelerationStructureNV, pAccelerationStructures), makeType<VkAccelerationStructureNV *>(*mlib));
}
#endif

#if defined(VK_NV_ray_tracing)
struct VkAccelerationStructureMemoryRequirementsInfoNV_Ann : ManagedStructureAnnotation<VkAccelerationStructureMemoryRequirementsInfoNV> {
    VkAccelerationStructureMemoryRequirementsInfoNV_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkAccelerationStructureMemoryRequirementsInfoNV", ml, "VkAccelerationStructureMemoryRequirementsInfoNV") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkAccelerationStructureMemoryRequirementsInfoNV_Ann * ann_VkAccelerationStructureMemoryRequirementsInfoNV = nullptr;
void VkAccelerationStructureMemoryRequirementsInfoNV_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkAccelerationStructureMemoryRequirementsInfoNV, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(type)>("type_", "type");
    addField<DAS_BIND_MANAGED_FIELD(accelerationStructure)>("accelerationStructure", "accelerationStructure");
}
#endif

#if defined(VK_KHR_acceleration_structure)
struct VkPhysicalDeviceAccelerationStructureFeaturesKHR_Ann : ManagedStructureAnnotation<VkPhysicalDeviceAccelerationStructureFeaturesKHR> {
    VkPhysicalDeviceAccelerationStructureFeaturesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceAccelerationStructureFeaturesKHR", ml, "VkPhysicalDeviceAccelerationStructureFeaturesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceAccelerationStructureFeaturesKHR_Ann * ann_VkPhysicalDeviceAccelerationStructureFeaturesKHR = nullptr;
void VkPhysicalDeviceAccelerationStructureFeaturesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceAccelerationStructureFeaturesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(accelerationStructure)>("accelerationStructure", "accelerationStructure");
    addField<DAS_BIND_MANAGED_FIELD(accelerationStructureCaptureReplay)>("accelerationStructureCaptureReplay", "accelerationStructureCaptureReplay");
    addField<DAS_BIND_MANAGED_FIELD(accelerationStructureIndirectBuild)>("accelerationStructureIndirectBuild", "accelerationStructureIndirectBuild");
    addField<DAS_BIND_MANAGED_FIELD(accelerationStructureHostCommands)>("accelerationStructureHostCommands", "accelerationStructureHostCommands");
    addField<DAS_BIND_MANAGED_FIELD(descriptorBindingAccelerationStructureUpdateAfterBind)>("descriptorBindingAccelerationStructureUpdateAfterBind", "descriptorBindingAccelerationStructureUpdateAfterBind");
}
#endif

#if defined(VK_KHR_ray_tracing_pipeline)
struct VkPhysicalDeviceRayTracingPipelineFeaturesKHR_Ann : ManagedStructureAnnotation<VkPhysicalDeviceRayTracingPipelineFeaturesKHR> {
    VkPhysicalDeviceRayTracingPipelineFeaturesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceRayTracingPipelineFeaturesKHR", ml, "VkPhysicalDeviceRayTracingPipelineFeaturesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceRayTracingPipelineFeaturesKHR_Ann * ann_VkPhysicalDeviceRayTracingPipelineFeaturesKHR = nullptr;
void VkPhysicalDeviceRayTracingPipelineFeaturesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceRayTracingPipelineFeaturesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(rayTracingPipeline)>("rayTracingPipeline", "rayTracingPipeline");
    addField<DAS_BIND_MANAGED_FIELD(rayTracingPipelineShaderGroupHandleCaptureReplay)>("rayTracingPipelineShaderGroupHandleCaptureReplay", "rayTracingPipelineShaderGroupHandleCaptureReplay");
    addField<DAS_BIND_MANAGED_FIELD(rayTracingPipelineShaderGroupHandleCaptureReplayMixed)>("rayTracingPipelineShaderGroupHandleCaptureReplayMixed", "rayTracingPipelineShaderGroupHandleCaptureReplayMixed");
    addField<DAS_BIND_MANAGED_FIELD(rayTracingPipelineTraceRaysIndirect)>("rayTracingPipelineTraceRaysIndirect", "rayTracingPipelineTraceRaysIndirect");
    addField<DAS_BIND_MANAGED_FIELD(rayTraversalPrimitiveCulling)>("rayTraversalPrimitiveCulling", "rayTraversalPrimitiveCulling");
}
#endif

#if defined(VK_KHR_ray_query)
struct VkPhysicalDeviceRayQueryFeaturesKHR_Ann : ManagedStructureAnnotation<VkPhysicalDeviceRayQueryFeaturesKHR> {
    VkPhysicalDeviceRayQueryFeaturesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceRayQueryFeaturesKHR", ml, "VkPhysicalDeviceRayQueryFeaturesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceRayQueryFeaturesKHR_Ann * ann_VkPhysicalDeviceRayQueryFeaturesKHR = nullptr;
void VkPhysicalDeviceRayQueryFeaturesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceRayQueryFeaturesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(rayQuery)>("rayQuery", "rayQuery");
}
#endif

#if defined(VK_KHR_acceleration_structure)
struct VkPhysicalDeviceAccelerationStructurePropertiesKHR_Ann : ManagedStructureAnnotation<VkPhysicalDeviceAccelerationStructurePropertiesKHR> {
    VkPhysicalDeviceAccelerationStructurePropertiesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceAccelerationStructurePropertiesKHR", ml, "VkPhysicalDeviceAccelerationStructurePropertiesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceAccelerationStructurePropertiesKHR_Ann * ann_VkPhysicalDeviceAccelerationStructurePropertiesKHR = nullptr;
void VkPhysicalDeviceAccelerationStructurePropertiesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceAccelerationStructurePropertiesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(maxGeometryCount)>("maxGeometryCount", "maxGeometryCount");
    addField<DAS_BIND_MANAGED_FIELD(maxInstanceCount)>("maxInstanceCount", "maxInstanceCount");
    addField<DAS_BIND_MANAGED_FIELD(maxPrimitiveCount)>("maxPrimitiveCount", "maxPrimitiveCount");
    addField<DAS_BIND_MANAGED_FIELD(maxPerStageDescriptorAccelerationStructures)>("maxPerStageDescriptorAccelerationStructures", "maxPerStageDescriptorAccelerationStructures");
    addField<DAS_BIND_MANAGED_FIELD(maxPerStageDescriptorUpdateAfterBindAccelerationStructures)>("maxPerStageDescriptorUpdateAfterBindAccelerationStructures", "maxPerStageDescriptorUpdateAfterBindAccelerationStructures");
    addField<DAS_BIND_MANAGED_FIELD(maxDescriptorSetAccelerationStructures)>("maxDescriptorSetAccelerationStructures", "maxDescriptorSetAccelerationStructures");
    addField<DAS_BIND_MANAGED_FIELD(maxDescriptorSetUpdateAfterBindAccelerationStructures)>("maxDescriptorSetUpdateAfterBindAccelerationStructures", "maxDescriptorSetUpdateAfterBindAccelerationStructures");
    addField<DAS_BIND_MANAGED_FIELD(minAccelerationStructureScratchOffsetAlignment)>("minAccelerationStructureScratchOffsetAlignment", "minAccelerationStructureScratchOffsetAlignment");
}
#endif

#if defined(VK_KHR_ray_tracing_pipeline)
struct VkPhysicalDeviceRayTracingPipelinePropertiesKHR_Ann : ManagedStructureAnnotation<VkPhysicalDeviceRayTracingPipelinePropertiesKHR> {
    VkPhysicalDeviceRayTracingPipelinePropertiesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceRayTracingPipelinePropertiesKHR", ml, "VkPhysicalDeviceRayTracingPipelinePropertiesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceRayTracingPipelinePropertiesKHR_Ann * ann_VkPhysicalDeviceRayTracingPipelinePropertiesKHR = nullptr;
void VkPhysicalDeviceRayTracingPipelinePropertiesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceRayTracingPipelinePropertiesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(shaderGroupHandleSize)>("shaderGroupHandleSize", "shaderGroupHandleSize");
    addField<DAS_BIND_MANAGED_FIELD(maxRayRecursionDepth)>("maxRayRecursionDepth", "maxRayRecursionDepth");
    addField<DAS_BIND_MANAGED_FIELD(maxShaderGroupStride)>("maxShaderGroupStride", "maxShaderGroupStride");
    addField<DAS_BIND_MANAGED_FIELD(shaderGroupBaseAlignment)>("shaderGroupBaseAlignment", "shaderGroupBaseAlignment");
    addField<DAS_BIND_MANAGED_FIELD(shaderGroupHandleCaptureReplaySize)>("shaderGroupHandleCaptureReplaySize", "shaderGroupHandleCaptureReplaySize");
    addField<DAS_BIND_MANAGED_FIELD(maxRayDispatchInvocationCount)>("maxRayDispatchInvocationCount", "maxRayDispatchInvocationCount");
    addField<DAS_BIND_MANAGED_FIELD(shaderGroupHandleAlignment)>("shaderGroupHandleAlignment", "shaderGroupHandleAlignment");
    addField<DAS_BIND_MANAGED_FIELD(maxRayHitAttributeSize)>("maxRayHitAttributeSize", "maxRayHitAttributeSize");
}
#endif

#if defined(VK_NV_ray_tracing)
struct VkPhysicalDeviceRayTracingPropertiesNV_Ann : ManagedStructureAnnotation<VkPhysicalDeviceRayTracingPropertiesNV> {
    VkPhysicalDeviceRayTracingPropertiesNV_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceRayTracingPropertiesNV", ml, "VkPhysicalDeviceRayTracingPropertiesNV") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceRayTracingPropertiesNV_Ann * ann_VkPhysicalDeviceRayTracingPropertiesNV = nullptr;
void VkPhysicalDeviceRayTracingPropertiesNV_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceRayTracingPropertiesNV, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(shaderGroupHandleSize)>("shaderGroupHandleSize", "shaderGroupHandleSize");
    addField<DAS_BIND_MANAGED_FIELD(maxRecursionDepth)>("maxRecursionDepth", "maxRecursionDepth");
    addField<DAS_BIND_MANAGED_FIELD(maxShaderGroupStride)>("maxShaderGroupStride", "maxShaderGroupStride");
    addField<DAS_BIND_MANAGED_FIELD(shaderGroupBaseAlignment)>("shaderGroupBaseAlignment", "shaderGroupBaseAlignment");
    addField<DAS_BIND_MANAGED_FIELD(maxGeometryCount)>("maxGeometryCount", "maxGeometryCount");
    addField<DAS_BIND_MANAGED_FIELD(maxInstanceCount)>("maxInstanceCount", "maxInstanceCount");
    addField<DAS_BIND_MANAGED_FIELD(maxTriangleCount)>("maxTriangleCount", "maxTriangleCount");
    addField<DAS_BIND_MANAGED_FIELD(maxDescriptorSetAccelerationStructures)>("maxDescriptorSetAccelerationStructures", "maxDescriptorSetAccelerationStructures");
}
#endif

#if defined(VK_KHR_ray_tracing_pipeline)
struct VkStridedDeviceAddressRegionKHR_Ann : ManagedStructureAnnotation<VkStridedDeviceAddressRegionKHR> {
    VkStridedDeviceAddressRegionKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkStridedDeviceAddressRegionKHR", ml, "VkStridedDeviceAddressRegionKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkStridedDeviceAddressRegionKHR_Ann * ann_VkStridedDeviceAddressRegionKHR = nullptr;
void VkStridedDeviceAddressRegionKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(deviceAddress)>("deviceAddress", "deviceAddress");
    addField<DAS_BIND_MANAGED_FIELD(stride)>("stride", "stride");
    addField<DAS_BIND_MANAGED_FIELD(size)>("size", "size");
}
#endif

#if defined(VK_KHR_ray_tracing_pipeline)
struct VkTraceRaysIndirectCommandKHR_Ann : ManagedStructureAnnotation<VkTraceRaysIndirectCommandKHR> {
    VkTraceRaysIndirectCommandKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkTraceRaysIndirectCommandKHR", ml, "VkTraceRaysIndirectCommandKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkTraceRaysIndirectCommandKHR_Ann * ann_VkTraceRaysIndirectCommandKHR = nullptr;
void VkTraceRaysIndirectCommandKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(width)>("width", "width");
    addField<DAS_BIND_MANAGED_FIELD(height)>("height", "height");
    addField<DAS_BIND_MANAGED_FIELD(depth)>("depth", "depth");
}
#endif

#if defined(VK_KHR_ray_tracing_maintenance1)
struct VkTraceRaysIndirectCommand2KHR_Ann : ManagedStructureAnnotation<VkTraceRaysIndirectCommand2KHR> {
    VkTraceRaysIndirectCommand2KHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkTraceRaysIndirectCommand2KHR", ml, "VkTraceRaysIndirectCommand2KHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkTraceRaysIndirectCommand2KHR_Ann * ann_VkTraceRaysIndirectCommand2KHR = nullptr;
void VkTraceRaysIndirectCommand2KHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(raygenShaderRecordAddress)>("raygenShaderRecordAddress", "raygenShaderRecordAddress");
    addField<DAS_BIND_MANAGED_FIELD(raygenShaderRecordSize)>("raygenShaderRecordSize", "raygenShaderRecordSize");
    addField<DAS_BIND_MANAGED_FIELD(missShaderBindingTableAddress)>("missShaderBindingTableAddress", "missShaderBindingTableAddress");
    addField<DAS_BIND_MANAGED_FIELD(missShaderBindingTableSize)>("missShaderBindingTableSize", "missShaderBindingTableSize");
    addField<DAS_BIND_MANAGED_FIELD(missShaderBindingTableStride)>("missShaderBindingTableStride", "missShaderBindingTableStride");
    addField<DAS_BIND_MANAGED_FIELD(hitShaderBindingTableAddress)>("hitShaderBindingTableAddress", "hitShaderBindingTableAddress");
    addField<DAS_BIND_MANAGED_FIELD(hitShaderBindingTableSize)>("hitShaderBindingTableSize", "hitShaderBindingTableSize");
    addField<DAS_BIND_MANAGED_FIELD(hitShaderBindingTableStride)>("hitShaderBindingTableStride", "hitShaderBindingTableStride");
    addField<DAS_BIND_MANAGED_FIELD(callableShaderBindingTableAddress)>("callableShaderBindingTableAddress", "callableShaderBindingTableAddress");
    addField<DAS_BIND_MANAGED_FIELD(callableShaderBindingTableSize)>("callableShaderBindingTableSize", "callableShaderBindingTableSize");
    addField<DAS_BIND_MANAGED_FIELD(callableShaderBindingTableStride)>("callableShaderBindingTableStride", "callableShaderBindingTableStride");
    addField<DAS_BIND_MANAGED_FIELD(width)>("width", "width");
    addField<DAS_BIND_MANAGED_FIELD(height)>("height", "height");
    addField<DAS_BIND_MANAGED_FIELD(depth)>("depth", "depth");
}
#endif

#if defined(VK_KHR_ray_tracing_maintenance1)
struct VkPhysicalDeviceRayTracingMaintenance1FeaturesKHR_Ann : ManagedStructureAnnotation<VkPhysicalDeviceRayTracingMaintenance1FeaturesKHR> {
    VkPhysicalDeviceRayTracingMaintenance1FeaturesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceRayTracingMaintenance1FeaturesKHR", ml, "VkPhysicalDeviceRayTracingMaintenance1FeaturesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceRayTracingMaintenance1FeaturesKHR_Ann * ann_VkPhysicalDeviceRayTracingMaintenance1FeaturesKHR = nullptr;
void VkPhysicalDeviceRayTracingMaintenance1FeaturesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceRayTracingMaintenance1FeaturesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(rayTracingMaintenance1)>("rayTracingMaintenance1", "rayTracingMaintenance1");
    addField<DAS_BIND_MANAGED_FIELD(rayTracingPipelineTraceRaysIndirect2)>("rayTracingPipelineTraceRaysIndirect2", "rayTracingPipelineTraceRaysIndirect2");
}
#endif

#if defined(VK_EXT_image_drm_format_modifier)
struct VkDrmFormatModifierPropertiesListEXT_Ann : ManagedStructureAnnotation<VkDrmFormatModifierPropertiesListEXT> {
    VkDrmFormatModifierPropertiesListEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDrmFormatModifierPropertiesListEXT", ml, "VkDrmFormatModifierPropertiesListEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDrmFormatModifierPropertiesListEXT_Ann * ann_VkDrmFormatModifierPropertiesListEXT = nullptr;
void VkDrmFormatModifierPropertiesListEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDrmFormatModifierPropertiesListEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(drmFormatModifierCount)>("drmFormatModifierCount", "drmFormatModifierCount");
    addFieldEx("pDrmFormatModifierProperties", "pDrmFormatModifierProperties", offsetof(VkDrmFormatModifierPropertiesListEXT, pDrmFormatModifierProperties), makeType<VkDrmFormatModifierPropertiesEXT *>(*mlib));
}
#endif

#if defined(VK_EXT_image_drm_format_modifier)
struct VkDrmFormatModifierPropertiesEXT_Ann : ManagedStructureAnnotation<VkDrmFormatModifierPropertiesEXT> {
    VkDrmFormatModifierPropertiesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDrmFormatModifierPropertiesEXT", ml, "VkDrmFormatModifierPropertiesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDrmFormatModifierPropertiesEXT_Ann * ann_VkDrmFormatModifierPropertiesEXT = nullptr;
void VkDrmFormatModifierPropertiesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(drmFormatModifier)>("drmFormatModifier", "drmFormatModifier");
    addField<DAS_BIND_MANAGED_FIELD(drmFormatModifierPlaneCount)>("drmFormatModifierPlaneCount", "drmFormatModifierPlaneCount");
    addFieldEx("drmFormatModifierTilingFeatures", "drmFormatModifierTilingFeatures", offsetof(VkDrmFormatModifierPropertiesEXT, drmFormatModifierTilingFeatures), makeVkFlags_VkFormatFeatureFlags());
}
#endif

#if defined(VK_EXT_image_drm_format_modifier)
struct VkPhysicalDeviceImageDrmFormatModifierInfoEXT_Ann : ManagedStructureAnnotation<VkPhysicalDeviceImageDrmFormatModifierInfoEXT> {
    VkPhysicalDeviceImageDrmFormatModifierInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceImageDrmFormatModifierInfoEXT", ml, "VkPhysicalDeviceImageDrmFormatModifierInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceImageDrmFormatModifierInfoEXT_Ann * ann_VkPhysicalDeviceImageDrmFormatModifierInfoEXT = nullptr;
void VkPhysicalDeviceImageDrmFormatModifierInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceImageDrmFormatModifierInfoEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(drmFormatModifier)>("drmFormatModifier", "drmFormatModifier");
    addField<DAS_BIND_MANAGED_FIELD(sharingMode)>("sharingMode", "sharingMode");
    addField<DAS_BIND_MANAGED_FIELD(queueFamilyIndexCount)>("queueFamilyIndexCount", "queueFamilyIndexCount");
    addFieldEx("pQueueFamilyIndices", "pQueueFamilyIndices", offsetof(VkPhysicalDeviceImageDrmFormatModifierInfoEXT, pQueueFamilyIndices), makeType<uint32_t *>(*mlib));
}
#endif

#if defined(VK_EXT_image_drm_format_modifier)
struct VkImageDrmFormatModifierListCreateInfoEXT_Ann : ManagedStructureAnnotation<VkImageDrmFormatModifierListCreateInfoEXT> {
    VkImageDrmFormatModifierListCreateInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkImageDrmFormatModifierListCreateInfoEXT", ml, "VkImageDrmFormatModifierListCreateInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkImageDrmFormatModifierListCreateInfoEXT_Ann * ann_VkImageDrmFormatModifierListCreateInfoEXT = nullptr;
void VkImageDrmFormatModifierListCreateInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkImageDrmFormatModifierListCreateInfoEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(drmFormatModifierCount)>("drmFormatModifierCount", "drmFormatModifierCount");
    addFieldEx("pDrmFormatModifiers", "pDrmFormatModifiers", offsetof(VkImageDrmFormatModifierListCreateInfoEXT, pDrmFormatModifiers), makeType<uint64_t *>(*mlib));
}
#endif

#if defined(VK_EXT_image_drm_format_modifier)
struct VkImageDrmFormatModifierExplicitCreateInfoEXT_Ann : ManagedStructureAnnotation<VkImageDrmFormatModifierExplicitCreateInfoEXT> {
    VkImageDrmFormatModifierExplicitCreateInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkImageDrmFormatModifierExplicitCreateInfoEXT", ml, "VkImageDrmFormatModifierExplicitCreateInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkImageDrmFormatModifierExplicitCreateInfoEXT_Ann * ann_VkImageDrmFormatModifierExplicitCreateInfoEXT = nullptr;
void VkImageDrmFormatModifierExplicitCreateInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkImageDrmFormatModifierExplicitCreateInfoEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(drmFormatModifier)>("drmFormatModifier", "drmFormatModifier");
    addField<DAS_BIND_MANAGED_FIELD(drmFormatModifierPlaneCount)>("drmFormatModifierPlaneCount", "drmFormatModifierPlaneCount");
    addFieldEx("pPlaneLayouts", "pPlaneLayouts", offsetof(VkImageDrmFormatModifierExplicitCreateInfoEXT, pPlaneLayouts), makeType<VkSubresourceLayout *>(*mlib));
}
#endif

#if defined(VK_EXT_image_drm_format_modifier)
struct VkImageDrmFormatModifierPropertiesEXT_Ann : ManagedStructureAnnotation<VkImageDrmFormatModifierPropertiesEXT> {
    VkImageDrmFormatModifierPropertiesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkImageDrmFormatModifierPropertiesEXT", ml, "VkImageDrmFormatModifierPropertiesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkImageDrmFormatModifierPropertiesEXT_Ann * ann_VkImageDrmFormatModifierPropertiesEXT = nullptr;
void VkImageDrmFormatModifierPropertiesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkImageDrmFormatModifierPropertiesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(drmFormatModifier)>("drmFormatModifier", "drmFormatModifier");
}
#endif

#if defined(VK_VERSION_1_2)
struct VkImageStencilUsageCreateInfo_Ann : ManagedStructureAnnotation<VkImageStencilUsageCreateInfo> {
    VkImageStencilUsageCreateInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkImageStencilUsageCreateInfo", ml, "VkImageStencilUsageCreateInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkImageStencilUsageCreateInfo_Ann * ann_VkImageStencilUsageCreateInfo = nullptr;
void VkImageStencilUsageCreateInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkImageStencilUsageCreateInfo, pNext), makeType<void *>(*mlib));
    addFieldEx("stencilUsage", "stencilUsage", offsetof(VkImageStencilUsageCreateInfo, stencilUsage), makeVkFlags_VkImageUsageFlags());
}
#endif

#if defined(VK_AMD_memory_overallocation_behavior)
struct VkDeviceMemoryOverallocationCreateInfoAMD_Ann : ManagedStructureAnnotation<VkDeviceMemoryOverallocationCreateInfoAMD> {
    VkDeviceMemoryOverallocationCreateInfoAMD_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDeviceMemoryOverallocationCreateInfoAMD", ml, "VkDeviceMemoryOverallocationCreateInfoAMD") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDeviceMemoryOverallocationCreateInfoAMD_Ann * ann_VkDeviceMemoryOverallocationCreateInfoAMD = nullptr;
void VkDeviceMemoryOverallocationCreateInfoAMD_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDeviceMemoryOverallocationCreateInfoAMD, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(overallocationBehavior)>("overallocationBehavior", "overallocationBehavior");
}
#endif

#if defined(VK_EXT_fragment_density_map)
struct VkPhysicalDeviceFragmentDensityMapFeaturesEXT_Ann : ManagedStructureAnnotation<VkPhysicalDeviceFragmentDensityMapFeaturesEXT> {
    VkPhysicalDeviceFragmentDensityMapFeaturesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceFragmentDensityMapFeaturesEXT", ml, "VkPhysicalDeviceFragmentDensityMapFeaturesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceFragmentDensityMapFeaturesEXT_Ann * ann_VkPhysicalDeviceFragmentDensityMapFeaturesEXT = nullptr;
void VkPhysicalDeviceFragmentDensityMapFeaturesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceFragmentDensityMapFeaturesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(fragmentDensityMap)>("fragmentDensityMap", "fragmentDensityMap");
    addField<DAS_BIND_MANAGED_FIELD(fragmentDensityMapDynamic)>("fragmentDensityMapDynamic", "fragmentDensityMapDynamic");
    addField<DAS_BIND_MANAGED_FIELD(fragmentDensityMapNonSubsampledImages)>("fragmentDensityMapNonSubsampledImages", "fragmentDensityMapNonSubsampledImages");
}
#endif

#if defined(VK_EXT_fragment_density_map2)
struct VkPhysicalDeviceFragmentDensityMap2FeaturesEXT_Ann : ManagedStructureAnnotation<VkPhysicalDeviceFragmentDensityMap2FeaturesEXT> {
    VkPhysicalDeviceFragmentDensityMap2FeaturesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceFragmentDensityMap2FeaturesEXT", ml, "VkPhysicalDeviceFragmentDensityMap2FeaturesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceFragmentDensityMap2FeaturesEXT_Ann * ann_VkPhysicalDeviceFragmentDensityMap2FeaturesEXT = nullptr;
void VkPhysicalDeviceFragmentDensityMap2FeaturesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceFragmentDensityMap2FeaturesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(fragmentDensityMapDeferred)>("fragmentDensityMapDeferred", "fragmentDensityMapDeferred");
}
#endif

#if defined(VK_EXT_fragment_density_map_offset)
struct VkPhysicalDeviceFragmentDensityMapOffsetFeaturesEXT_Ann : ManagedStructureAnnotation<VkPhysicalDeviceFragmentDensityMapOffsetFeaturesEXT> {
    VkPhysicalDeviceFragmentDensityMapOffsetFeaturesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceFragmentDensityMapOffsetFeaturesEXT", ml, "VkPhysicalDeviceFragmentDensityMapOffsetFeaturesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceFragmentDensityMapOffsetFeaturesEXT_Ann * ann_VkPhysicalDeviceFragmentDensityMapOffsetFeaturesEXT = nullptr;
void VkPhysicalDeviceFragmentDensityMapOffsetFeaturesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceFragmentDensityMapOffsetFeaturesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(fragmentDensityMapOffset)>("fragmentDensityMapOffset", "fragmentDensityMapOffset");
}
#endif

#if defined(VK_EXT_fragment_density_map)
struct VkPhysicalDeviceFragmentDensityMapPropertiesEXT_Ann : ManagedStructureAnnotation<VkPhysicalDeviceFragmentDensityMapPropertiesEXT> {
    VkPhysicalDeviceFragmentDensityMapPropertiesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceFragmentDensityMapPropertiesEXT", ml, "VkPhysicalDeviceFragmentDensityMapPropertiesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceFragmentDensityMapPropertiesEXT_Ann * ann_VkPhysicalDeviceFragmentDensityMapPropertiesEXT = nullptr;
void VkPhysicalDeviceFragmentDensityMapPropertiesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceFragmentDensityMapPropertiesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(minFragmentDensityTexelSize)>("minFragmentDensityTexelSize", "minFragmentDensityTexelSize");
    addField<DAS_BIND_MANAGED_FIELD(maxFragmentDensityTexelSize)>("maxFragmentDensityTexelSize", "maxFragmentDensityTexelSize");
    addField<DAS_BIND_MANAGED_FIELD(fragmentDensityInvocations)>("fragmentDensityInvocations", "fragmentDensityInvocations");
}
#endif

#if defined(VK_EXT_fragment_density_map2)
struct VkPhysicalDeviceFragmentDensityMap2PropertiesEXT_Ann : ManagedStructureAnnotation<VkPhysicalDeviceFragmentDensityMap2PropertiesEXT> {
    VkPhysicalDeviceFragmentDensityMap2PropertiesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceFragmentDensityMap2PropertiesEXT", ml, "VkPhysicalDeviceFragmentDensityMap2PropertiesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceFragmentDensityMap2PropertiesEXT_Ann * ann_VkPhysicalDeviceFragmentDensityMap2PropertiesEXT = nullptr;
void VkPhysicalDeviceFragmentDensityMap2PropertiesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceFragmentDensityMap2PropertiesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(subsampledLoads)>("subsampledLoads", "subsampledLoads");
    addField<DAS_BIND_MANAGED_FIELD(subsampledCoarseReconstructionEarlyAccess)>("subsampledCoarseReconstructionEarlyAccess", "subsampledCoarseReconstructionEarlyAccess");
    addField<DAS_BIND_MANAGED_FIELD(maxSubsampledArrayLayers)>("maxSubsampledArrayLayers", "maxSubsampledArrayLayers");
    addField<DAS_BIND_MANAGED_FIELD(maxDescriptorSetSubsampledSamplers)>("maxDescriptorSetSubsampledSamplers", "maxDescriptorSetSubsampledSamplers");
}
#endif

#if defined(VK_EXT_fragment_density_map_offset)
struct VkPhysicalDeviceFragmentDensityMapOffsetPropertiesEXT_Ann : ManagedStructureAnnotation<VkPhysicalDeviceFragmentDensityMapOffsetPropertiesEXT> {
    VkPhysicalDeviceFragmentDensityMapOffsetPropertiesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceFragmentDensityMapOffsetPropertiesEXT", ml, "VkPhysicalDeviceFragmentDensityMapOffsetPropertiesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceFragmentDensityMapOffsetPropertiesEXT_Ann * ann_VkPhysicalDeviceFragmentDensityMapOffsetPropertiesEXT = nullptr;
void VkPhysicalDeviceFragmentDensityMapOffsetPropertiesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceFragmentDensityMapOffsetPropertiesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(fragmentDensityOffsetGranularity)>("fragmentDensityOffsetGranularity", "fragmentDensityOffsetGranularity");
}
#endif

#if defined(VK_EXT_fragment_density_map)
struct VkRenderPassFragmentDensityMapCreateInfoEXT_Ann : ManagedStructureAnnotation<VkRenderPassFragmentDensityMapCreateInfoEXT> {
    VkRenderPassFragmentDensityMapCreateInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkRenderPassFragmentDensityMapCreateInfoEXT", ml, "VkRenderPassFragmentDensityMapCreateInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkRenderPassFragmentDensityMapCreateInfoEXT_Ann * ann_VkRenderPassFragmentDensityMapCreateInfoEXT = nullptr;
void VkRenderPassFragmentDensityMapCreateInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkRenderPassFragmentDensityMapCreateInfoEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(fragmentDensityMapAttachment)>("fragmentDensityMapAttachment", "fragmentDensityMapAttachment");
}
#endif

#if defined(VK_EXT_fragment_density_map_offset)
struct VkRenderPassFragmentDensityMapOffsetEndInfoEXT_Ann : ManagedStructureAnnotation<VkRenderPassFragmentDensityMapOffsetEndInfoEXT> {
    VkRenderPassFragmentDensityMapOffsetEndInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkRenderPassFragmentDensityMapOffsetEndInfoEXT", ml, "VkRenderPassFragmentDensityMapOffsetEndInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkRenderPassFragmentDensityMapOffsetEndInfoEXT_Ann * ann_VkRenderPassFragmentDensityMapOffsetEndInfoEXT = nullptr;
void VkRenderPassFragmentDensityMapOffsetEndInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkRenderPassFragmentDensityMapOffsetEndInfoEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(fragmentDensityOffsetCount)>("fragmentDensityOffsetCount", "fragmentDensityOffsetCount");
    addFieldEx("pFragmentDensityOffsets", "pFragmentDensityOffsets", offsetof(VkRenderPassFragmentDensityMapOffsetEndInfoEXT, pFragmentDensityOffsets), makeType<VkOffset2D *>(*mlib));
}
#endif

#if defined(VK_VERSION_1_2)
struct VkPhysicalDeviceScalarBlockLayoutFeatures_Ann : ManagedStructureAnnotation<VkPhysicalDeviceScalarBlockLayoutFeatures> {
    VkPhysicalDeviceScalarBlockLayoutFeatures_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceScalarBlockLayoutFeatures", ml, "VkPhysicalDeviceScalarBlockLayoutFeatures") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceScalarBlockLayoutFeatures_Ann * ann_VkPhysicalDeviceScalarBlockLayoutFeatures = nullptr;
void VkPhysicalDeviceScalarBlockLayoutFeatures_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceScalarBlockLayoutFeatures, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(scalarBlockLayout)>("scalarBlockLayout", "scalarBlockLayout");
}
#endif

#if defined(VK_KHR_surface_protected_capabilities)
struct VkSurfaceProtectedCapabilitiesKHR_Ann : ManagedStructureAnnotation<VkSurfaceProtectedCapabilitiesKHR> {
    VkSurfaceProtectedCapabilitiesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkSurfaceProtectedCapabilitiesKHR", ml, "VkSurfaceProtectedCapabilitiesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkSurfaceProtectedCapabilitiesKHR_Ann * ann_VkSurfaceProtectedCapabilitiesKHR = nullptr;
void VkSurfaceProtectedCapabilitiesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkSurfaceProtectedCapabilitiesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(supportsProtected)>("supportsProtected", "supportsProtected");
}
#endif

#if defined(VK_VERSION_1_2)
struct VkPhysicalDeviceUniformBufferStandardLayoutFeatures_Ann : ManagedStructureAnnotation<VkPhysicalDeviceUniformBufferStandardLayoutFeatures> {
    VkPhysicalDeviceUniformBufferStandardLayoutFeatures_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceUniformBufferStandardLayoutFeatures", ml, "VkPhysicalDeviceUniformBufferStandardLayoutFeatures") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceUniformBufferStandardLayoutFeatures_Ann * ann_VkPhysicalDeviceUniformBufferStandardLayoutFeatures = nullptr;
void VkPhysicalDeviceUniformBufferStandardLayoutFeatures_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceUniformBufferStandardLayoutFeatures, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(uniformBufferStandardLayout)>("uniformBufferStandardLayout", "uniformBufferStandardLayout");
}
#endif

#if defined(VK_EXT_depth_clip_enable)
struct VkPhysicalDeviceDepthClipEnableFeaturesEXT_Ann : ManagedStructureAnnotation<VkPhysicalDeviceDepthClipEnableFeaturesEXT> {
    VkPhysicalDeviceDepthClipEnableFeaturesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceDepthClipEnableFeaturesEXT", ml, "VkPhysicalDeviceDepthClipEnableFeaturesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceDepthClipEnableFeaturesEXT_Ann * ann_VkPhysicalDeviceDepthClipEnableFeaturesEXT = nullptr;
void VkPhysicalDeviceDepthClipEnableFeaturesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceDepthClipEnableFeaturesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(depthClipEnable)>("depthClipEnable", "depthClipEnable");
}
#endif

#if defined(VK_EXT_depth_clip_enable)
struct VkPipelineRasterizationDepthClipStateCreateInfoEXT_Ann : ManagedStructureAnnotation<VkPipelineRasterizationDepthClipStateCreateInfoEXT> {
    VkPipelineRasterizationDepthClipStateCreateInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPipelineRasterizationDepthClipStateCreateInfoEXT", ml, "VkPipelineRasterizationDepthClipStateCreateInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPipelineRasterizationDepthClipStateCreateInfoEXT_Ann * ann_VkPipelineRasterizationDepthClipStateCreateInfoEXT = nullptr;
void VkPipelineRasterizationDepthClipStateCreateInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPipelineRasterizationDepthClipStateCreateInfoEXT, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkPipelineRasterizationDepthClipStateCreateInfoEXT, flags), makeVkFlags_VkPipelineRasterizationDepthClipStateCreateFlagsEXT());
    addField<DAS_BIND_MANAGED_FIELD(depthClipEnable)>("depthClipEnable", "depthClipEnable");
}
#endif

#if defined(VK_EXT_memory_budget)
struct VkPhysicalDeviceMemoryBudgetPropertiesEXT_Ann : ManagedStructureAnnotation<VkPhysicalDeviceMemoryBudgetPropertiesEXT> {
    VkPhysicalDeviceMemoryBudgetPropertiesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceMemoryBudgetPropertiesEXT", ml, "VkPhysicalDeviceMemoryBudgetPropertiesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceMemoryBudgetPropertiesEXT_Ann * ann_VkPhysicalDeviceMemoryBudgetPropertiesEXT = nullptr;
void VkPhysicalDeviceMemoryBudgetPropertiesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceMemoryBudgetPropertiesEXT, pNext), makeType<void *>(*mlib));
    addFieldEx("heapBudget", "heapBudget", offsetof(VkPhysicalDeviceMemoryBudgetPropertiesEXT, heapBudget), makeFixedArrayTypeDecl(int32_t(VK_MAX_MEMORY_HEAPS), makeType<uint64_t>(*mlib)));
    addFieldEx("heapUsage", "heapUsage", offsetof(VkPhysicalDeviceMemoryBudgetPropertiesEXT, heapUsage), makeFixedArrayTypeDecl(int32_t(VK_MAX_MEMORY_HEAPS), makeType<uint64_t>(*mlib)));
}
#endif

#if defined(VK_EXT_memory_priority)
struct VkPhysicalDeviceMemoryPriorityFeaturesEXT_Ann : ManagedStructureAnnotation<VkPhysicalDeviceMemoryPriorityFeaturesEXT> {
    VkPhysicalDeviceMemoryPriorityFeaturesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceMemoryPriorityFeaturesEXT", ml, "VkPhysicalDeviceMemoryPriorityFeaturesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceMemoryPriorityFeaturesEXT_Ann * ann_VkPhysicalDeviceMemoryPriorityFeaturesEXT = nullptr;
void VkPhysicalDeviceMemoryPriorityFeaturesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceMemoryPriorityFeaturesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(memoryPriority)>("memoryPriority", "memoryPriority");
}
#endif

#if defined(VK_EXT_memory_priority)
struct VkMemoryPriorityAllocateInfoEXT_Ann : ManagedStructureAnnotation<VkMemoryPriorityAllocateInfoEXT> {
    VkMemoryPriorityAllocateInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkMemoryPriorityAllocateInfoEXT", ml, "VkMemoryPriorityAllocateInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkMemoryPriorityAllocateInfoEXT_Ann * ann_VkMemoryPriorityAllocateInfoEXT = nullptr;
void VkMemoryPriorityAllocateInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkMemoryPriorityAllocateInfoEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(priority)>("priority", "priority");
}
#endif

#if defined(VK_EXT_pageable_device_local_memory)
struct VkPhysicalDevicePageableDeviceLocalMemoryFeaturesEXT_Ann : ManagedStructureAnnotation<VkPhysicalDevicePageableDeviceLocalMemoryFeaturesEXT> {
    VkPhysicalDevicePageableDeviceLocalMemoryFeaturesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDevicePageableDeviceLocalMemoryFeaturesEXT", ml, "VkPhysicalDevicePageableDeviceLocalMemoryFeaturesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDevicePageableDeviceLocalMemoryFeaturesEXT_Ann * ann_VkPhysicalDevicePageableDeviceLocalMemoryFeaturesEXT = nullptr;
void VkPhysicalDevicePageableDeviceLocalMemoryFeaturesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDevicePageableDeviceLocalMemoryFeaturesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(pageableDeviceLocalMemory)>("pageableDeviceLocalMemory", "pageableDeviceLocalMemory");
}
#endif

#if defined(VK_VERSION_1_2)
struct VkPhysicalDeviceBufferDeviceAddressFeatures_Ann : ManagedStructureAnnotation<VkPhysicalDeviceBufferDeviceAddressFeatures> {
    VkPhysicalDeviceBufferDeviceAddressFeatures_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceBufferDeviceAddressFeatures", ml, "VkPhysicalDeviceBufferDeviceAddressFeatures") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceBufferDeviceAddressFeatures_Ann * ann_VkPhysicalDeviceBufferDeviceAddressFeatures = nullptr;
void VkPhysicalDeviceBufferDeviceAddressFeatures_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceBufferDeviceAddressFeatures, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(bufferDeviceAddress)>("bufferDeviceAddress", "bufferDeviceAddress");
    addField<DAS_BIND_MANAGED_FIELD(bufferDeviceAddressCaptureReplay)>("bufferDeviceAddressCaptureReplay", "bufferDeviceAddressCaptureReplay");
    addField<DAS_BIND_MANAGED_FIELD(bufferDeviceAddressMultiDevice)>("bufferDeviceAddressMultiDevice", "bufferDeviceAddressMultiDevice");
}
#endif

#if defined(VK_EXT_buffer_device_address)
struct VkPhysicalDeviceBufferDeviceAddressFeaturesEXT_Ann : ManagedStructureAnnotation<VkPhysicalDeviceBufferDeviceAddressFeaturesEXT> {
    VkPhysicalDeviceBufferDeviceAddressFeaturesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceBufferDeviceAddressFeaturesEXT", ml, "VkPhysicalDeviceBufferDeviceAddressFeaturesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceBufferDeviceAddressFeaturesEXT_Ann * ann_VkPhysicalDeviceBufferDeviceAddressFeaturesEXT = nullptr;
void VkPhysicalDeviceBufferDeviceAddressFeaturesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceBufferDeviceAddressFeaturesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(bufferDeviceAddress)>("bufferDeviceAddress", "bufferDeviceAddress");
    addField<DAS_BIND_MANAGED_FIELD(bufferDeviceAddressCaptureReplay)>("bufferDeviceAddressCaptureReplay", "bufferDeviceAddressCaptureReplay");
    addField<DAS_BIND_MANAGED_FIELD(bufferDeviceAddressMultiDevice)>("bufferDeviceAddressMultiDevice", "bufferDeviceAddressMultiDevice");
}
#endif

#if defined(VK_VERSION_1_2)
struct VkBufferDeviceAddressInfo_Ann : ManagedStructureAnnotation<VkBufferDeviceAddressInfo> {
    VkBufferDeviceAddressInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkBufferDeviceAddressInfo", ml, "VkBufferDeviceAddressInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkBufferDeviceAddressInfo_Ann * ann_VkBufferDeviceAddressInfo = nullptr;
void VkBufferDeviceAddressInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkBufferDeviceAddressInfo, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(buffer)>("buffer", "buffer");
}
#endif

#if defined(VK_VERSION_1_2)
struct VkBufferOpaqueCaptureAddressCreateInfo_Ann : ManagedStructureAnnotation<VkBufferOpaqueCaptureAddressCreateInfo> {
    VkBufferOpaqueCaptureAddressCreateInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkBufferOpaqueCaptureAddressCreateInfo", ml, "VkBufferOpaqueCaptureAddressCreateInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkBufferOpaqueCaptureAddressCreateInfo_Ann * ann_VkBufferOpaqueCaptureAddressCreateInfo = nullptr;
void VkBufferOpaqueCaptureAddressCreateInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkBufferOpaqueCaptureAddressCreateInfo, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(opaqueCaptureAddress)>("opaqueCaptureAddress", "opaqueCaptureAddress");
}
#endif

#if defined(VK_EXT_buffer_device_address)
struct VkBufferDeviceAddressCreateInfoEXT_Ann : ManagedStructureAnnotation<VkBufferDeviceAddressCreateInfoEXT> {
    VkBufferDeviceAddressCreateInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkBufferDeviceAddressCreateInfoEXT", ml, "VkBufferDeviceAddressCreateInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkBufferDeviceAddressCreateInfoEXT_Ann * ann_VkBufferDeviceAddressCreateInfoEXT = nullptr;
void VkBufferDeviceAddressCreateInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkBufferDeviceAddressCreateInfoEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(deviceAddress)>("deviceAddress", "deviceAddress");
}
#endif

#if defined(VK_EXT_filter_cubic)
struct VkPhysicalDeviceImageViewImageFormatInfoEXT_Ann : ManagedStructureAnnotation<VkPhysicalDeviceImageViewImageFormatInfoEXT> {
    VkPhysicalDeviceImageViewImageFormatInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceImageViewImageFormatInfoEXT", ml, "VkPhysicalDeviceImageViewImageFormatInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceImageViewImageFormatInfoEXT_Ann * ann_VkPhysicalDeviceImageViewImageFormatInfoEXT = nullptr;
void VkPhysicalDeviceImageViewImageFormatInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceImageViewImageFormatInfoEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(imageViewType)>("imageViewType", "imageViewType");
}
#endif

#if defined(VK_EXT_filter_cubic)
struct VkFilterCubicImageViewImageFormatPropertiesEXT_Ann : ManagedStructureAnnotation<VkFilterCubicImageViewImageFormatPropertiesEXT> {
    VkFilterCubicImageViewImageFormatPropertiesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkFilterCubicImageViewImageFormatPropertiesEXT", ml, "VkFilterCubicImageViewImageFormatPropertiesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkFilterCubicImageViewImageFormatPropertiesEXT_Ann * ann_VkFilterCubicImageViewImageFormatPropertiesEXT = nullptr;
void VkFilterCubicImageViewImageFormatPropertiesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkFilterCubicImageViewImageFormatPropertiesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(filterCubic)>("filterCubic", "filterCubic");
    addField<DAS_BIND_MANAGED_FIELD(filterCubicMinmax)>("filterCubicMinmax", "filterCubicMinmax");
}
#endif

#if defined(VK_VERSION_1_2)
struct VkPhysicalDeviceImagelessFramebufferFeatures_Ann : ManagedStructureAnnotation<VkPhysicalDeviceImagelessFramebufferFeatures> {
    VkPhysicalDeviceImagelessFramebufferFeatures_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceImagelessFramebufferFeatures", ml, "VkPhysicalDeviceImagelessFramebufferFeatures") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceImagelessFramebufferFeatures_Ann * ann_VkPhysicalDeviceImagelessFramebufferFeatures = nullptr;
void VkPhysicalDeviceImagelessFramebufferFeatures_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceImagelessFramebufferFeatures, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(imagelessFramebuffer)>("imagelessFramebuffer", "imagelessFramebuffer");
}
#endif

#if defined(VK_VERSION_1_2)
struct VkFramebufferAttachmentsCreateInfo_Ann : ManagedStructureAnnotation<VkFramebufferAttachmentsCreateInfo> {
    VkFramebufferAttachmentsCreateInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkFramebufferAttachmentsCreateInfo", ml, "VkFramebufferAttachmentsCreateInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkFramebufferAttachmentsCreateInfo_Ann * ann_VkFramebufferAttachmentsCreateInfo = nullptr;
void VkFramebufferAttachmentsCreateInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkFramebufferAttachmentsCreateInfo, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(attachmentImageInfoCount)>("attachmentImageInfoCount", "attachmentImageInfoCount");
    addFieldEx("pAttachmentImageInfos", "pAttachmentImageInfos", offsetof(VkFramebufferAttachmentsCreateInfo, pAttachmentImageInfos), makeType<VkFramebufferAttachmentImageInfo *>(*mlib));
}
#endif

#if defined(VK_VERSION_1_2)
struct VkFramebufferAttachmentImageInfo_Ann : ManagedStructureAnnotation<VkFramebufferAttachmentImageInfo> {
    VkFramebufferAttachmentImageInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkFramebufferAttachmentImageInfo", ml, "VkFramebufferAttachmentImageInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkFramebufferAttachmentImageInfo_Ann * ann_VkFramebufferAttachmentImageInfo = nullptr;
void VkFramebufferAttachmentImageInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkFramebufferAttachmentImageInfo, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkFramebufferAttachmentImageInfo, flags), makeVkFlags_VkImageCreateFlags());
    addFieldEx("usage", "usage", offsetof(VkFramebufferAttachmentImageInfo, usage), makeVkFlags_VkImageUsageFlags());
    addField<DAS_BIND_MANAGED_FIELD(width)>("width", "width");
    addField<DAS_BIND_MANAGED_FIELD(height)>("height", "height");
    addField<DAS_BIND_MANAGED_FIELD(layerCount)>("layerCount", "layerCount");
    addField<DAS_BIND_MANAGED_FIELD(viewFormatCount)>("viewFormatCount", "viewFormatCount");
    addFieldEx("pViewFormats", "pViewFormats", offsetof(VkFramebufferAttachmentImageInfo, pViewFormats), makeType<VkFormat *>(*mlib));
}
#endif

void das_vulkan_add_structs_10(Module & mod, ModuleLibrary & lib) {
#if defined(VK_NV_ray_tracing)
    ann_VkGeometryNV = new VkGeometryNV_Ann(lib); mod.addAnnotation(ann_VkGeometryNV);
#endif
#if defined(VK_NV_ray_tracing)
    ann_VkBindAccelerationStructureMemoryInfoNV = new VkBindAccelerationStructureMemoryInfoNV_Ann(lib); mod.addAnnotation(ann_VkBindAccelerationStructureMemoryInfoNV);
#endif
#if defined(VK_KHR_acceleration_structure)
    ann_VkWriteDescriptorSetAccelerationStructureKHR = new VkWriteDescriptorSetAccelerationStructureKHR_Ann(lib); mod.addAnnotation(ann_VkWriteDescriptorSetAccelerationStructureKHR);
#endif
#if defined(VK_NV_ray_tracing)
    ann_VkWriteDescriptorSetAccelerationStructureNV = new VkWriteDescriptorSetAccelerationStructureNV_Ann(lib); mod.addAnnotation(ann_VkWriteDescriptorSetAccelerationStructureNV);
#endif
#if defined(VK_NV_ray_tracing)
    ann_VkAccelerationStructureMemoryRequirementsInfoNV = new VkAccelerationStructureMemoryRequirementsInfoNV_Ann(lib); mod.addAnnotation(ann_VkAccelerationStructureMemoryRequirementsInfoNV);
#endif
#if defined(VK_KHR_acceleration_structure)
    ann_VkPhysicalDeviceAccelerationStructureFeaturesKHR = new VkPhysicalDeviceAccelerationStructureFeaturesKHR_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceAccelerationStructureFeaturesKHR);
#endif
#if defined(VK_KHR_ray_tracing_pipeline)
    ann_VkPhysicalDeviceRayTracingPipelineFeaturesKHR = new VkPhysicalDeviceRayTracingPipelineFeaturesKHR_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceRayTracingPipelineFeaturesKHR);
#endif
#if defined(VK_KHR_ray_query)
    ann_VkPhysicalDeviceRayQueryFeaturesKHR = new VkPhysicalDeviceRayQueryFeaturesKHR_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceRayQueryFeaturesKHR);
#endif
#if defined(VK_KHR_acceleration_structure)
    ann_VkPhysicalDeviceAccelerationStructurePropertiesKHR = new VkPhysicalDeviceAccelerationStructurePropertiesKHR_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceAccelerationStructurePropertiesKHR);
#endif
#if defined(VK_KHR_ray_tracing_pipeline)
    ann_VkPhysicalDeviceRayTracingPipelinePropertiesKHR = new VkPhysicalDeviceRayTracingPipelinePropertiesKHR_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceRayTracingPipelinePropertiesKHR);
#endif
#if defined(VK_NV_ray_tracing)
    ann_VkPhysicalDeviceRayTracingPropertiesNV = new VkPhysicalDeviceRayTracingPropertiesNV_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceRayTracingPropertiesNV);
#endif
#if defined(VK_KHR_ray_tracing_pipeline)
    ann_VkStridedDeviceAddressRegionKHR = new VkStridedDeviceAddressRegionKHR_Ann(lib); mod.addAnnotation(ann_VkStridedDeviceAddressRegionKHR);
#endif
#if defined(VK_KHR_ray_tracing_pipeline)
    ann_VkTraceRaysIndirectCommandKHR = new VkTraceRaysIndirectCommandKHR_Ann(lib); mod.addAnnotation(ann_VkTraceRaysIndirectCommandKHR);
#endif
#if defined(VK_KHR_ray_tracing_maintenance1)
    ann_VkTraceRaysIndirectCommand2KHR = new VkTraceRaysIndirectCommand2KHR_Ann(lib); mod.addAnnotation(ann_VkTraceRaysIndirectCommand2KHR);
#endif
#if defined(VK_KHR_ray_tracing_maintenance1)
    ann_VkPhysicalDeviceRayTracingMaintenance1FeaturesKHR = new VkPhysicalDeviceRayTracingMaintenance1FeaturesKHR_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceRayTracingMaintenance1FeaturesKHR);
#endif
#if defined(VK_EXT_image_drm_format_modifier)
    ann_VkDrmFormatModifierPropertiesListEXT = new VkDrmFormatModifierPropertiesListEXT_Ann(lib); mod.addAnnotation(ann_VkDrmFormatModifierPropertiesListEXT);
#endif
#if defined(VK_EXT_image_drm_format_modifier)
    ann_VkDrmFormatModifierPropertiesEXT = new VkDrmFormatModifierPropertiesEXT_Ann(lib); mod.addAnnotation(ann_VkDrmFormatModifierPropertiesEXT);
#endif
#if defined(VK_EXT_image_drm_format_modifier)
    ann_VkPhysicalDeviceImageDrmFormatModifierInfoEXT = new VkPhysicalDeviceImageDrmFormatModifierInfoEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceImageDrmFormatModifierInfoEXT);
#endif
#if defined(VK_EXT_image_drm_format_modifier)
    ann_VkImageDrmFormatModifierListCreateInfoEXT = new VkImageDrmFormatModifierListCreateInfoEXT_Ann(lib); mod.addAnnotation(ann_VkImageDrmFormatModifierListCreateInfoEXT);
#endif
#if defined(VK_EXT_image_drm_format_modifier)
    ann_VkImageDrmFormatModifierExplicitCreateInfoEXT = new VkImageDrmFormatModifierExplicitCreateInfoEXT_Ann(lib); mod.addAnnotation(ann_VkImageDrmFormatModifierExplicitCreateInfoEXT);
#endif
#if defined(VK_EXT_image_drm_format_modifier)
    ann_VkImageDrmFormatModifierPropertiesEXT = new VkImageDrmFormatModifierPropertiesEXT_Ann(lib); mod.addAnnotation(ann_VkImageDrmFormatModifierPropertiesEXT);
#endif
#if defined(VK_VERSION_1_2)
    ann_VkImageStencilUsageCreateInfo = new VkImageStencilUsageCreateInfo_Ann(lib); mod.addAnnotation(ann_VkImageStencilUsageCreateInfo);
#endif
#if defined(VK_AMD_memory_overallocation_behavior)
    ann_VkDeviceMemoryOverallocationCreateInfoAMD = new VkDeviceMemoryOverallocationCreateInfoAMD_Ann(lib); mod.addAnnotation(ann_VkDeviceMemoryOverallocationCreateInfoAMD);
#endif
#if defined(VK_EXT_fragment_density_map)
    ann_VkPhysicalDeviceFragmentDensityMapFeaturesEXT = new VkPhysicalDeviceFragmentDensityMapFeaturesEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceFragmentDensityMapFeaturesEXT);
#endif
#if defined(VK_EXT_fragment_density_map2)
    ann_VkPhysicalDeviceFragmentDensityMap2FeaturesEXT = new VkPhysicalDeviceFragmentDensityMap2FeaturesEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceFragmentDensityMap2FeaturesEXT);
#endif
#if defined(VK_EXT_fragment_density_map_offset)
    ann_VkPhysicalDeviceFragmentDensityMapOffsetFeaturesEXT = new VkPhysicalDeviceFragmentDensityMapOffsetFeaturesEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceFragmentDensityMapOffsetFeaturesEXT);
#endif
#if defined(VK_EXT_fragment_density_map)
    ann_VkPhysicalDeviceFragmentDensityMapPropertiesEXT = new VkPhysicalDeviceFragmentDensityMapPropertiesEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceFragmentDensityMapPropertiesEXT);
#endif
#if defined(VK_EXT_fragment_density_map2)
    ann_VkPhysicalDeviceFragmentDensityMap2PropertiesEXT = new VkPhysicalDeviceFragmentDensityMap2PropertiesEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceFragmentDensityMap2PropertiesEXT);
#endif
#if defined(VK_EXT_fragment_density_map_offset)
    ann_VkPhysicalDeviceFragmentDensityMapOffsetPropertiesEXT = new VkPhysicalDeviceFragmentDensityMapOffsetPropertiesEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceFragmentDensityMapOffsetPropertiesEXT);
#endif
#if defined(VK_EXT_fragment_density_map)
    ann_VkRenderPassFragmentDensityMapCreateInfoEXT = new VkRenderPassFragmentDensityMapCreateInfoEXT_Ann(lib); mod.addAnnotation(ann_VkRenderPassFragmentDensityMapCreateInfoEXT);
#endif
#if defined(VK_EXT_fragment_density_map_offset)
    ann_VkRenderPassFragmentDensityMapOffsetEndInfoEXT = new VkRenderPassFragmentDensityMapOffsetEndInfoEXT_Ann(lib); mod.addAnnotation(ann_VkRenderPassFragmentDensityMapOffsetEndInfoEXT);
#endif
#if defined(VK_VERSION_1_2)
    ann_VkPhysicalDeviceScalarBlockLayoutFeatures = new VkPhysicalDeviceScalarBlockLayoutFeatures_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceScalarBlockLayoutFeatures);
#endif
#if defined(VK_KHR_surface_protected_capabilities)
    ann_VkSurfaceProtectedCapabilitiesKHR = new VkSurfaceProtectedCapabilitiesKHR_Ann(lib); mod.addAnnotation(ann_VkSurfaceProtectedCapabilitiesKHR);
#endif
#if defined(VK_VERSION_1_2)
    ann_VkPhysicalDeviceUniformBufferStandardLayoutFeatures = new VkPhysicalDeviceUniformBufferStandardLayoutFeatures_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceUniformBufferStandardLayoutFeatures);
#endif
#if defined(VK_EXT_depth_clip_enable)
    ann_VkPhysicalDeviceDepthClipEnableFeaturesEXT = new VkPhysicalDeviceDepthClipEnableFeaturesEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceDepthClipEnableFeaturesEXT);
#endif
#if defined(VK_EXT_depth_clip_enable)
    ann_VkPipelineRasterizationDepthClipStateCreateInfoEXT = new VkPipelineRasterizationDepthClipStateCreateInfoEXT_Ann(lib); mod.addAnnotation(ann_VkPipelineRasterizationDepthClipStateCreateInfoEXT);
#endif
#if defined(VK_EXT_memory_budget)
    ann_VkPhysicalDeviceMemoryBudgetPropertiesEXT = new VkPhysicalDeviceMemoryBudgetPropertiesEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceMemoryBudgetPropertiesEXT);
#endif
#if defined(VK_EXT_memory_priority)
    ann_VkPhysicalDeviceMemoryPriorityFeaturesEXT = new VkPhysicalDeviceMemoryPriorityFeaturesEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceMemoryPriorityFeaturesEXT);
#endif
#if defined(VK_EXT_memory_priority)
    ann_VkMemoryPriorityAllocateInfoEXT = new VkMemoryPriorityAllocateInfoEXT_Ann(lib); mod.addAnnotation(ann_VkMemoryPriorityAllocateInfoEXT);
#endif
#if defined(VK_EXT_pageable_device_local_memory)
    ann_VkPhysicalDevicePageableDeviceLocalMemoryFeaturesEXT = new VkPhysicalDevicePageableDeviceLocalMemoryFeaturesEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDevicePageableDeviceLocalMemoryFeaturesEXT);
#endif
#if defined(VK_VERSION_1_2)
    ann_VkPhysicalDeviceBufferDeviceAddressFeatures = new VkPhysicalDeviceBufferDeviceAddressFeatures_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceBufferDeviceAddressFeatures);
#endif
#if defined(VK_EXT_buffer_device_address)
    ann_VkPhysicalDeviceBufferDeviceAddressFeaturesEXT = new VkPhysicalDeviceBufferDeviceAddressFeaturesEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceBufferDeviceAddressFeaturesEXT);
#endif
#if defined(VK_VERSION_1_2)
    ann_VkBufferDeviceAddressInfo = new VkBufferDeviceAddressInfo_Ann(lib); mod.addAnnotation(ann_VkBufferDeviceAddressInfo);
#endif
#if defined(VK_VERSION_1_2)
    ann_VkBufferOpaqueCaptureAddressCreateInfo = new VkBufferOpaqueCaptureAddressCreateInfo_Ann(lib); mod.addAnnotation(ann_VkBufferOpaqueCaptureAddressCreateInfo);
#endif
#if defined(VK_EXT_buffer_device_address)
    ann_VkBufferDeviceAddressCreateInfoEXT = new VkBufferDeviceAddressCreateInfoEXT_Ann(lib); mod.addAnnotation(ann_VkBufferDeviceAddressCreateInfoEXT);
#endif
#if defined(VK_EXT_filter_cubic)
    ann_VkPhysicalDeviceImageViewImageFormatInfoEXT = new VkPhysicalDeviceImageViewImageFormatInfoEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceImageViewImageFormatInfoEXT);
#endif
#if defined(VK_EXT_filter_cubic)
    ann_VkFilterCubicImageViewImageFormatPropertiesEXT = new VkFilterCubicImageViewImageFormatPropertiesEXT_Ann(lib); mod.addAnnotation(ann_VkFilterCubicImageViewImageFormatPropertiesEXT);
#endif
#if defined(VK_VERSION_1_2)
    ann_VkPhysicalDeviceImagelessFramebufferFeatures = new VkPhysicalDeviceImagelessFramebufferFeatures_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceImagelessFramebufferFeatures);
#endif
#if defined(VK_VERSION_1_2)
    ann_VkFramebufferAttachmentsCreateInfo = new VkFramebufferAttachmentsCreateInfo_Ann(lib); mod.addAnnotation(ann_VkFramebufferAttachmentsCreateInfo);
#endif
#if defined(VK_VERSION_1_2)
    ann_VkFramebufferAttachmentImageInfo = new VkFramebufferAttachmentImageInfo_Ann(lib); mod.addAnnotation(ann_VkFramebufferAttachmentImageInfo);
#endif
}

void das_vulkan_fill_structs_10(Module & mod, ModuleLibrary & lib) {
#if defined(VK_NV_ray_tracing)
    ann_VkGeometryNV->mlib = &lib; ann_VkGeometryNV->init(); ann_VkGeometryNV->mlib = nullptr;
#endif
#if defined(VK_NV_ray_tracing)
    ann_VkBindAccelerationStructureMemoryInfoNV->mlib = &lib; ann_VkBindAccelerationStructureMemoryInfoNV->init(); ann_VkBindAccelerationStructureMemoryInfoNV->mlib = nullptr;
#endif
#if defined(VK_KHR_acceleration_structure)
    ann_VkWriteDescriptorSetAccelerationStructureKHR->mlib = &lib; ann_VkWriteDescriptorSetAccelerationStructureKHR->init(); ann_VkWriteDescriptorSetAccelerationStructureKHR->mlib = nullptr;
#endif
#if defined(VK_NV_ray_tracing)
    ann_VkWriteDescriptorSetAccelerationStructureNV->mlib = &lib; ann_VkWriteDescriptorSetAccelerationStructureNV->init(); ann_VkWriteDescriptorSetAccelerationStructureNV->mlib = nullptr;
#endif
#if defined(VK_NV_ray_tracing)
    ann_VkAccelerationStructureMemoryRequirementsInfoNV->mlib = &lib; ann_VkAccelerationStructureMemoryRequirementsInfoNV->init(); ann_VkAccelerationStructureMemoryRequirementsInfoNV->mlib = nullptr;
#endif
#if defined(VK_KHR_acceleration_structure)
    ann_VkPhysicalDeviceAccelerationStructureFeaturesKHR->mlib = &lib; ann_VkPhysicalDeviceAccelerationStructureFeaturesKHR->init(); ann_VkPhysicalDeviceAccelerationStructureFeaturesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_ray_tracing_pipeline)
    ann_VkPhysicalDeviceRayTracingPipelineFeaturesKHR->mlib = &lib; ann_VkPhysicalDeviceRayTracingPipelineFeaturesKHR->init(); ann_VkPhysicalDeviceRayTracingPipelineFeaturesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_ray_query)
    ann_VkPhysicalDeviceRayQueryFeaturesKHR->mlib = &lib; ann_VkPhysicalDeviceRayQueryFeaturesKHR->init(); ann_VkPhysicalDeviceRayQueryFeaturesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_acceleration_structure)
    ann_VkPhysicalDeviceAccelerationStructurePropertiesKHR->mlib = &lib; ann_VkPhysicalDeviceAccelerationStructurePropertiesKHR->init(); ann_VkPhysicalDeviceAccelerationStructurePropertiesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_ray_tracing_pipeline)
    ann_VkPhysicalDeviceRayTracingPipelinePropertiesKHR->mlib = &lib; ann_VkPhysicalDeviceRayTracingPipelinePropertiesKHR->init(); ann_VkPhysicalDeviceRayTracingPipelinePropertiesKHR->mlib = nullptr;
#endif
#if defined(VK_NV_ray_tracing)
    ann_VkPhysicalDeviceRayTracingPropertiesNV->mlib = &lib; ann_VkPhysicalDeviceRayTracingPropertiesNV->init(); ann_VkPhysicalDeviceRayTracingPropertiesNV->mlib = nullptr;
#endif
#if defined(VK_KHR_ray_tracing_pipeline)
    ann_VkStridedDeviceAddressRegionKHR->mlib = &lib; ann_VkStridedDeviceAddressRegionKHR->init(); ann_VkStridedDeviceAddressRegionKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_ray_tracing_pipeline)
    ann_VkTraceRaysIndirectCommandKHR->mlib = &lib; ann_VkTraceRaysIndirectCommandKHR->init(); ann_VkTraceRaysIndirectCommandKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_ray_tracing_maintenance1)
    ann_VkTraceRaysIndirectCommand2KHR->mlib = &lib; ann_VkTraceRaysIndirectCommand2KHR->init(); ann_VkTraceRaysIndirectCommand2KHR->mlib = nullptr;
#endif
#if defined(VK_KHR_ray_tracing_maintenance1)
    ann_VkPhysicalDeviceRayTracingMaintenance1FeaturesKHR->mlib = &lib; ann_VkPhysicalDeviceRayTracingMaintenance1FeaturesKHR->init(); ann_VkPhysicalDeviceRayTracingMaintenance1FeaturesKHR->mlib = nullptr;
#endif
#if defined(VK_EXT_image_drm_format_modifier)
    ann_VkDrmFormatModifierPropertiesListEXT->mlib = &lib; ann_VkDrmFormatModifierPropertiesListEXT->init(); ann_VkDrmFormatModifierPropertiesListEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_image_drm_format_modifier)
    ann_VkDrmFormatModifierPropertiesEXT->mlib = &lib; ann_VkDrmFormatModifierPropertiesEXT->init(); ann_VkDrmFormatModifierPropertiesEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_image_drm_format_modifier)
    ann_VkPhysicalDeviceImageDrmFormatModifierInfoEXT->mlib = &lib; ann_VkPhysicalDeviceImageDrmFormatModifierInfoEXT->init(); ann_VkPhysicalDeviceImageDrmFormatModifierInfoEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_image_drm_format_modifier)
    ann_VkImageDrmFormatModifierListCreateInfoEXT->mlib = &lib; ann_VkImageDrmFormatModifierListCreateInfoEXT->init(); ann_VkImageDrmFormatModifierListCreateInfoEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_image_drm_format_modifier)
    ann_VkImageDrmFormatModifierExplicitCreateInfoEXT->mlib = &lib; ann_VkImageDrmFormatModifierExplicitCreateInfoEXT->init(); ann_VkImageDrmFormatModifierExplicitCreateInfoEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_image_drm_format_modifier)
    ann_VkImageDrmFormatModifierPropertiesEXT->mlib = &lib; ann_VkImageDrmFormatModifierPropertiesEXT->init(); ann_VkImageDrmFormatModifierPropertiesEXT->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_2)
    ann_VkImageStencilUsageCreateInfo->mlib = &lib; ann_VkImageStencilUsageCreateInfo->init(); ann_VkImageStencilUsageCreateInfo->mlib = nullptr;
#endif
#if defined(VK_AMD_memory_overallocation_behavior)
    ann_VkDeviceMemoryOverallocationCreateInfoAMD->mlib = &lib; ann_VkDeviceMemoryOverallocationCreateInfoAMD->init(); ann_VkDeviceMemoryOverallocationCreateInfoAMD->mlib = nullptr;
#endif
#if defined(VK_EXT_fragment_density_map)
    ann_VkPhysicalDeviceFragmentDensityMapFeaturesEXT->mlib = &lib; ann_VkPhysicalDeviceFragmentDensityMapFeaturesEXT->init(); ann_VkPhysicalDeviceFragmentDensityMapFeaturesEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_fragment_density_map2)
    ann_VkPhysicalDeviceFragmentDensityMap2FeaturesEXT->mlib = &lib; ann_VkPhysicalDeviceFragmentDensityMap2FeaturesEXT->init(); ann_VkPhysicalDeviceFragmentDensityMap2FeaturesEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_fragment_density_map_offset)
    ann_VkPhysicalDeviceFragmentDensityMapOffsetFeaturesEXT->mlib = &lib; ann_VkPhysicalDeviceFragmentDensityMapOffsetFeaturesEXT->init(); ann_VkPhysicalDeviceFragmentDensityMapOffsetFeaturesEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_fragment_density_map)
    ann_VkPhysicalDeviceFragmentDensityMapPropertiesEXT->mlib = &lib; ann_VkPhysicalDeviceFragmentDensityMapPropertiesEXT->init(); ann_VkPhysicalDeviceFragmentDensityMapPropertiesEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_fragment_density_map2)
    ann_VkPhysicalDeviceFragmentDensityMap2PropertiesEXT->mlib = &lib; ann_VkPhysicalDeviceFragmentDensityMap2PropertiesEXT->init(); ann_VkPhysicalDeviceFragmentDensityMap2PropertiesEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_fragment_density_map_offset)
    ann_VkPhysicalDeviceFragmentDensityMapOffsetPropertiesEXT->mlib = &lib; ann_VkPhysicalDeviceFragmentDensityMapOffsetPropertiesEXT->init(); ann_VkPhysicalDeviceFragmentDensityMapOffsetPropertiesEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_fragment_density_map)
    ann_VkRenderPassFragmentDensityMapCreateInfoEXT->mlib = &lib; ann_VkRenderPassFragmentDensityMapCreateInfoEXT->init(); ann_VkRenderPassFragmentDensityMapCreateInfoEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_fragment_density_map_offset)
    ann_VkRenderPassFragmentDensityMapOffsetEndInfoEXT->mlib = &lib; ann_VkRenderPassFragmentDensityMapOffsetEndInfoEXT->init(); ann_VkRenderPassFragmentDensityMapOffsetEndInfoEXT->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_2)
    ann_VkPhysicalDeviceScalarBlockLayoutFeatures->mlib = &lib; ann_VkPhysicalDeviceScalarBlockLayoutFeatures->init(); ann_VkPhysicalDeviceScalarBlockLayoutFeatures->mlib = nullptr;
#endif
#if defined(VK_KHR_surface_protected_capabilities)
    ann_VkSurfaceProtectedCapabilitiesKHR->mlib = &lib; ann_VkSurfaceProtectedCapabilitiesKHR->init(); ann_VkSurfaceProtectedCapabilitiesKHR->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_2)
    ann_VkPhysicalDeviceUniformBufferStandardLayoutFeatures->mlib = &lib; ann_VkPhysicalDeviceUniformBufferStandardLayoutFeatures->init(); ann_VkPhysicalDeviceUniformBufferStandardLayoutFeatures->mlib = nullptr;
#endif
#if defined(VK_EXT_depth_clip_enable)
    ann_VkPhysicalDeviceDepthClipEnableFeaturesEXT->mlib = &lib; ann_VkPhysicalDeviceDepthClipEnableFeaturesEXT->init(); ann_VkPhysicalDeviceDepthClipEnableFeaturesEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_depth_clip_enable)
    ann_VkPipelineRasterizationDepthClipStateCreateInfoEXT->mlib = &lib; ann_VkPipelineRasterizationDepthClipStateCreateInfoEXT->init(); ann_VkPipelineRasterizationDepthClipStateCreateInfoEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_memory_budget)
    ann_VkPhysicalDeviceMemoryBudgetPropertiesEXT->mlib = &lib; ann_VkPhysicalDeviceMemoryBudgetPropertiesEXT->init(); ann_VkPhysicalDeviceMemoryBudgetPropertiesEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_memory_priority)
    ann_VkPhysicalDeviceMemoryPriorityFeaturesEXT->mlib = &lib; ann_VkPhysicalDeviceMemoryPriorityFeaturesEXT->init(); ann_VkPhysicalDeviceMemoryPriorityFeaturesEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_memory_priority)
    ann_VkMemoryPriorityAllocateInfoEXT->mlib = &lib; ann_VkMemoryPriorityAllocateInfoEXT->init(); ann_VkMemoryPriorityAllocateInfoEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_pageable_device_local_memory)
    ann_VkPhysicalDevicePageableDeviceLocalMemoryFeaturesEXT->mlib = &lib; ann_VkPhysicalDevicePageableDeviceLocalMemoryFeaturesEXT->init(); ann_VkPhysicalDevicePageableDeviceLocalMemoryFeaturesEXT->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_2)
    ann_VkPhysicalDeviceBufferDeviceAddressFeatures->mlib = &lib; ann_VkPhysicalDeviceBufferDeviceAddressFeatures->init(); ann_VkPhysicalDeviceBufferDeviceAddressFeatures->mlib = nullptr;
#endif
#if defined(VK_EXT_buffer_device_address)
    ann_VkPhysicalDeviceBufferDeviceAddressFeaturesEXT->mlib = &lib; ann_VkPhysicalDeviceBufferDeviceAddressFeaturesEXT->init(); ann_VkPhysicalDeviceBufferDeviceAddressFeaturesEXT->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_2)
    ann_VkBufferDeviceAddressInfo->mlib = &lib; ann_VkBufferDeviceAddressInfo->init(); ann_VkBufferDeviceAddressInfo->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_2)
    ann_VkBufferOpaqueCaptureAddressCreateInfo->mlib = &lib; ann_VkBufferOpaqueCaptureAddressCreateInfo->init(); ann_VkBufferOpaqueCaptureAddressCreateInfo->mlib = nullptr;
#endif
#if defined(VK_EXT_buffer_device_address)
    ann_VkBufferDeviceAddressCreateInfoEXT->mlib = &lib; ann_VkBufferDeviceAddressCreateInfoEXT->init(); ann_VkBufferDeviceAddressCreateInfoEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_filter_cubic)
    ann_VkPhysicalDeviceImageViewImageFormatInfoEXT->mlib = &lib; ann_VkPhysicalDeviceImageViewImageFormatInfoEXT->init(); ann_VkPhysicalDeviceImageViewImageFormatInfoEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_filter_cubic)
    ann_VkFilterCubicImageViewImageFormatPropertiesEXT->mlib = &lib; ann_VkFilterCubicImageViewImageFormatPropertiesEXT->init(); ann_VkFilterCubicImageViewImageFormatPropertiesEXT->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_2)
    ann_VkPhysicalDeviceImagelessFramebufferFeatures->mlib = &lib; ann_VkPhysicalDeviceImagelessFramebufferFeatures->init(); ann_VkPhysicalDeviceImagelessFramebufferFeatures->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_2)
    ann_VkFramebufferAttachmentsCreateInfo->mlib = &lib; ann_VkFramebufferAttachmentsCreateInfo->init(); ann_VkFramebufferAttachmentsCreateInfo->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_2)
    ann_VkFramebufferAttachmentImageInfo->mlib = &lib; ann_VkFramebufferAttachmentImageInfo->init(); ann_VkFramebufferAttachmentImageInfo->mlib = nullptr;
#endif
}

}
