// generated by generator/generate.das -- DO NOT EDIT

#include "dasVULKAN.h"

namespace das {

#if defined(VK_VERSION_1_2)
struct VkRenderPassAttachmentBeginInfo_Ann : ManagedStructureAnnotation<VkRenderPassAttachmentBeginInfo> {
    VkRenderPassAttachmentBeginInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkRenderPassAttachmentBeginInfo", ml, "VkRenderPassAttachmentBeginInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkRenderPassAttachmentBeginInfo_Ann * ann_VkRenderPassAttachmentBeginInfo = nullptr;
void VkRenderPassAttachmentBeginInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkRenderPassAttachmentBeginInfo, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(attachmentCount)>("attachmentCount", "attachmentCount");
    addFieldEx("pAttachments", "pAttachments", offsetof(VkRenderPassAttachmentBeginInfo, pAttachments), makeType<VkImageView *>(*mlib));
}
#endif

#if defined(VK_VERSION_1_3)
struct VkPhysicalDeviceTextureCompressionASTCHDRFeatures_Ann : ManagedStructureAnnotation<VkPhysicalDeviceTextureCompressionASTCHDRFeatures> {
    VkPhysicalDeviceTextureCompressionASTCHDRFeatures_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceTextureCompressionASTCHDRFeatures", ml, "VkPhysicalDeviceTextureCompressionASTCHDRFeatures") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceTextureCompressionASTCHDRFeatures_Ann * ann_VkPhysicalDeviceTextureCompressionASTCHDRFeatures = nullptr;
void VkPhysicalDeviceTextureCompressionASTCHDRFeatures_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceTextureCompressionASTCHDRFeatures, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(textureCompressionASTC_HDR)>("textureCompressionASTC_HDR", "textureCompressionASTC_HDR");
}
#endif

#if defined(VK_NV_cooperative_matrix)
struct VkPhysicalDeviceCooperativeMatrixFeaturesNV_Ann : ManagedStructureAnnotation<VkPhysicalDeviceCooperativeMatrixFeaturesNV> {
    VkPhysicalDeviceCooperativeMatrixFeaturesNV_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceCooperativeMatrixFeaturesNV", ml, "VkPhysicalDeviceCooperativeMatrixFeaturesNV") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceCooperativeMatrixFeaturesNV_Ann * ann_VkPhysicalDeviceCooperativeMatrixFeaturesNV = nullptr;
void VkPhysicalDeviceCooperativeMatrixFeaturesNV_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceCooperativeMatrixFeaturesNV, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(cooperativeMatrix)>("cooperativeMatrix", "cooperativeMatrix");
    addField<DAS_BIND_MANAGED_FIELD(cooperativeMatrixRobustBufferAccess)>("cooperativeMatrixRobustBufferAccess", "cooperativeMatrixRobustBufferAccess");
}
#endif

#if defined(VK_NV_cooperative_matrix)
struct VkPhysicalDeviceCooperativeMatrixPropertiesNV_Ann : ManagedStructureAnnotation<VkPhysicalDeviceCooperativeMatrixPropertiesNV> {
    VkPhysicalDeviceCooperativeMatrixPropertiesNV_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceCooperativeMatrixPropertiesNV", ml, "VkPhysicalDeviceCooperativeMatrixPropertiesNV") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceCooperativeMatrixPropertiesNV_Ann * ann_VkPhysicalDeviceCooperativeMatrixPropertiesNV = nullptr;
void VkPhysicalDeviceCooperativeMatrixPropertiesNV_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceCooperativeMatrixPropertiesNV, pNext), makeType<void *>(*mlib));
    addFieldEx("cooperativeMatrixSupportedStages", "cooperativeMatrixSupportedStages", offsetof(VkPhysicalDeviceCooperativeMatrixPropertiesNV, cooperativeMatrixSupportedStages), makeVkFlags_VkShaderStageFlags());
}
#endif

#if defined(VK_EXT_ycbcr_image_arrays)
struct VkPhysicalDeviceYcbcrImageArraysFeaturesEXT_Ann : ManagedStructureAnnotation<VkPhysicalDeviceYcbcrImageArraysFeaturesEXT> {
    VkPhysicalDeviceYcbcrImageArraysFeaturesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceYcbcrImageArraysFeaturesEXT", ml, "VkPhysicalDeviceYcbcrImageArraysFeaturesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceYcbcrImageArraysFeaturesEXT_Ann * ann_VkPhysicalDeviceYcbcrImageArraysFeaturesEXT = nullptr;
void VkPhysicalDeviceYcbcrImageArraysFeaturesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceYcbcrImageArraysFeaturesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(ycbcrImageArrays)>("ycbcrImageArrays", "ycbcrImageArrays");
}
#endif

#if defined(VK_NVX_image_view_handle)
struct VkImageViewHandleInfoNVX_Ann : ManagedStructureAnnotation<VkImageViewHandleInfoNVX> {
    VkImageViewHandleInfoNVX_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkImageViewHandleInfoNVX", ml, "VkImageViewHandleInfoNVX") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkImageViewHandleInfoNVX_Ann * ann_VkImageViewHandleInfoNVX = nullptr;
void VkImageViewHandleInfoNVX_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkImageViewHandleInfoNVX, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(imageView)>("imageView", "imageView");
    addField<DAS_BIND_MANAGED_FIELD(descriptorType)>("descriptorType", "descriptorType");
    addField<DAS_BIND_MANAGED_FIELD(sampler)>("sampler", "sampler");
}
#endif

#if defined(VK_NVX_image_view_handle)
struct VkImageViewAddressPropertiesNVX_Ann : ManagedStructureAnnotation<VkImageViewAddressPropertiesNVX> {
    VkImageViewAddressPropertiesNVX_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkImageViewAddressPropertiesNVX", ml, "VkImageViewAddressPropertiesNVX") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkImageViewAddressPropertiesNVX_Ann * ann_VkImageViewAddressPropertiesNVX = nullptr;
void VkImageViewAddressPropertiesNVX_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkImageViewAddressPropertiesNVX, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(deviceAddress)>("deviceAddress", "deviceAddress");
    addField<DAS_BIND_MANAGED_FIELD(size)>("size", "size");
}
#endif

#if defined(VK_VERSION_1_3)
struct VkPipelineCreationFeedback_Ann : ManagedStructureAnnotation<VkPipelineCreationFeedback> {
    VkPipelineCreationFeedback_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPipelineCreationFeedback", ml, "VkPipelineCreationFeedback") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPipelineCreationFeedback_Ann * ann_VkPipelineCreationFeedback = nullptr;
void VkPipelineCreationFeedback_Ann::init() {
    addFieldEx("flags", "flags", offsetof(VkPipelineCreationFeedback, flags), makeVkFlags_VkPipelineCreationFeedbackFlags());
    addField<DAS_BIND_MANAGED_FIELD(duration)>("duration", "duration");
}
#endif

#if defined(VK_VERSION_1_3)
struct VkPipelineCreationFeedbackCreateInfo_Ann : ManagedStructureAnnotation<VkPipelineCreationFeedbackCreateInfo> {
    VkPipelineCreationFeedbackCreateInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPipelineCreationFeedbackCreateInfo", ml, "VkPipelineCreationFeedbackCreateInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPipelineCreationFeedbackCreateInfo_Ann * ann_VkPipelineCreationFeedbackCreateInfo = nullptr;
void VkPipelineCreationFeedbackCreateInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPipelineCreationFeedbackCreateInfo, pNext), makeType<void *>(*mlib));
    addFieldEx("pPipelineCreationFeedback", "pPipelineCreationFeedback", offsetof(VkPipelineCreationFeedbackCreateInfo, pPipelineCreationFeedback), makeType<VkPipelineCreationFeedback *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(pipelineStageCreationFeedbackCount)>("pipelineStageCreationFeedbackCount", "pipelineStageCreationFeedbackCount");
    addFieldEx("pPipelineStageCreationFeedbacks", "pPipelineStageCreationFeedbacks", offsetof(VkPipelineCreationFeedbackCreateInfo, pPipelineStageCreationFeedbacks), makeType<VkPipelineCreationFeedback *>(*mlib));
}
#endif

#if defined(VK_EXT_full_screen_exclusive) && defined(VK_USE_PLATFORM_WIN32_KHR)
struct VkSurfaceFullScreenExclusiveInfoEXT_Ann : ManagedStructureAnnotation<VkSurfaceFullScreenExclusiveInfoEXT> {
    VkSurfaceFullScreenExclusiveInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkSurfaceFullScreenExclusiveInfoEXT", ml, "VkSurfaceFullScreenExclusiveInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkSurfaceFullScreenExclusiveInfoEXT_Ann * ann_VkSurfaceFullScreenExclusiveInfoEXT = nullptr;
void VkSurfaceFullScreenExclusiveInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkSurfaceFullScreenExclusiveInfoEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(fullScreenExclusive)>("fullScreenExclusive", "fullScreenExclusive");
}
#endif

#if defined(VK_EXT_full_screen_exclusive) && defined(VK_USE_PLATFORM_WIN32_KHR)
struct VkSurfaceFullScreenExclusiveWin32InfoEXT_Ann : ManagedStructureAnnotation<VkSurfaceFullScreenExclusiveWin32InfoEXT> {
    VkSurfaceFullScreenExclusiveWin32InfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkSurfaceFullScreenExclusiveWin32InfoEXT", ml, "VkSurfaceFullScreenExclusiveWin32InfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkSurfaceFullScreenExclusiveWin32InfoEXT_Ann * ann_VkSurfaceFullScreenExclusiveWin32InfoEXT = nullptr;
void VkSurfaceFullScreenExclusiveWin32InfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkSurfaceFullScreenExclusiveWin32InfoEXT, pNext), makeType<void *>(*mlib));
    addFieldEx("hmonitor", "hmonitor", offsetof(VkSurfaceFullScreenExclusiveWin32InfoEXT, hmonitor), makeType<void *>(*mlib));
}
#endif

#if defined(VK_EXT_full_screen_exclusive) && defined(VK_USE_PLATFORM_WIN32_KHR)
struct VkSurfaceCapabilitiesFullScreenExclusiveEXT_Ann : ManagedStructureAnnotation<VkSurfaceCapabilitiesFullScreenExclusiveEXT> {
    VkSurfaceCapabilitiesFullScreenExclusiveEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkSurfaceCapabilitiesFullScreenExclusiveEXT", ml, "VkSurfaceCapabilitiesFullScreenExclusiveEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkSurfaceCapabilitiesFullScreenExclusiveEXT_Ann * ann_VkSurfaceCapabilitiesFullScreenExclusiveEXT = nullptr;
void VkSurfaceCapabilitiesFullScreenExclusiveEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkSurfaceCapabilitiesFullScreenExclusiveEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(fullScreenExclusiveSupported)>("fullScreenExclusiveSupported", "fullScreenExclusiveSupported");
}
#endif

#if defined(VK_NV_present_barrier)
struct VkPhysicalDevicePresentBarrierFeaturesNV_Ann : ManagedStructureAnnotation<VkPhysicalDevicePresentBarrierFeaturesNV> {
    VkPhysicalDevicePresentBarrierFeaturesNV_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDevicePresentBarrierFeaturesNV", ml, "VkPhysicalDevicePresentBarrierFeaturesNV") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDevicePresentBarrierFeaturesNV_Ann * ann_VkPhysicalDevicePresentBarrierFeaturesNV = nullptr;
void VkPhysicalDevicePresentBarrierFeaturesNV_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDevicePresentBarrierFeaturesNV, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(presentBarrier)>("presentBarrier", "presentBarrier");
}
#endif

#if defined(VK_NV_present_barrier)
struct VkSurfaceCapabilitiesPresentBarrierNV_Ann : ManagedStructureAnnotation<VkSurfaceCapabilitiesPresentBarrierNV> {
    VkSurfaceCapabilitiesPresentBarrierNV_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkSurfaceCapabilitiesPresentBarrierNV", ml, "VkSurfaceCapabilitiesPresentBarrierNV") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkSurfaceCapabilitiesPresentBarrierNV_Ann * ann_VkSurfaceCapabilitiesPresentBarrierNV = nullptr;
void VkSurfaceCapabilitiesPresentBarrierNV_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkSurfaceCapabilitiesPresentBarrierNV, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(presentBarrierSupported)>("presentBarrierSupported", "presentBarrierSupported");
}
#endif

#if defined(VK_NV_present_barrier)
struct VkSwapchainPresentBarrierCreateInfoNV_Ann : ManagedStructureAnnotation<VkSwapchainPresentBarrierCreateInfoNV> {
    VkSwapchainPresentBarrierCreateInfoNV_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkSwapchainPresentBarrierCreateInfoNV", ml, "VkSwapchainPresentBarrierCreateInfoNV") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkSwapchainPresentBarrierCreateInfoNV_Ann * ann_VkSwapchainPresentBarrierCreateInfoNV = nullptr;
void VkSwapchainPresentBarrierCreateInfoNV_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkSwapchainPresentBarrierCreateInfoNV, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(presentBarrierEnable)>("presentBarrierEnable", "presentBarrierEnable");
}
#endif

#if defined(VK_KHR_performance_query)
struct VkPhysicalDevicePerformanceQueryFeaturesKHR_Ann : ManagedStructureAnnotation<VkPhysicalDevicePerformanceQueryFeaturesKHR> {
    VkPhysicalDevicePerformanceQueryFeaturesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDevicePerformanceQueryFeaturesKHR", ml, "VkPhysicalDevicePerformanceQueryFeaturesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDevicePerformanceQueryFeaturesKHR_Ann * ann_VkPhysicalDevicePerformanceQueryFeaturesKHR = nullptr;
void VkPhysicalDevicePerformanceQueryFeaturesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDevicePerformanceQueryFeaturesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(performanceCounterQueryPools)>("performanceCounterQueryPools", "performanceCounterQueryPools");
    addField<DAS_BIND_MANAGED_FIELD(performanceCounterMultipleQueryPools)>("performanceCounterMultipleQueryPools", "performanceCounterMultipleQueryPools");
}
#endif

#if defined(VK_KHR_performance_query)
struct VkPhysicalDevicePerformanceQueryPropertiesKHR_Ann : ManagedStructureAnnotation<VkPhysicalDevicePerformanceQueryPropertiesKHR> {
    VkPhysicalDevicePerformanceQueryPropertiesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDevicePerformanceQueryPropertiesKHR", ml, "VkPhysicalDevicePerformanceQueryPropertiesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDevicePerformanceQueryPropertiesKHR_Ann * ann_VkPhysicalDevicePerformanceQueryPropertiesKHR = nullptr;
void VkPhysicalDevicePerformanceQueryPropertiesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDevicePerformanceQueryPropertiesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(allowCommandBufferQueryCopies)>("allowCommandBufferQueryCopies", "allowCommandBufferQueryCopies");
}
#endif

#if defined(VK_KHR_performance_query)
struct VkPerformanceCounterKHR_Ann : ManagedStructureAnnotation<VkPerformanceCounterKHR> {
    VkPerformanceCounterKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPerformanceCounterKHR", ml, "VkPerformanceCounterKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPerformanceCounterKHR_Ann * ann_VkPerformanceCounterKHR = nullptr;
void VkPerformanceCounterKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPerformanceCounterKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(unit)>("unit", "unit");
    addField<DAS_BIND_MANAGED_FIELD(scope)>("scope", "scope");
    addField<DAS_BIND_MANAGED_FIELD(storage)>("storage", "storage");
    addFieldEx("uuid", "uuid", offsetof(VkPerformanceCounterKHR, uuid), makeFixedArrayTypeDecl(int32_t(VK_UUID_SIZE), makeType<uint8_t>(*mlib)));
}
#endif

#if defined(VK_KHR_performance_query)
struct VkPerformanceCounterDescriptionKHR_Ann : ManagedStructureAnnotation<VkPerformanceCounterDescriptionKHR> {
    VkPerformanceCounterDescriptionKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPerformanceCounterDescriptionKHR", ml, "VkPerformanceCounterDescriptionKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPerformanceCounterDescriptionKHR_Ann * ann_VkPerformanceCounterDescriptionKHR = nullptr;
void VkPerformanceCounterDescriptionKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPerformanceCounterDescriptionKHR, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkPerformanceCounterDescriptionKHR, flags), makeVkFlags_VkPerformanceCounterDescriptionFlagsKHR());
    addFieldEx("name", "name", offsetof(VkPerformanceCounterDescriptionKHR, name), makeFixedArrayTypeDecl(int32_t(VK_MAX_DESCRIPTION_SIZE), makeType<int8_t>(*mlib)));
    addFieldEx("category", "category", offsetof(VkPerformanceCounterDescriptionKHR, category), makeFixedArrayTypeDecl(int32_t(VK_MAX_DESCRIPTION_SIZE), makeType<int8_t>(*mlib)));
    addFieldEx("description", "description", offsetof(VkPerformanceCounterDescriptionKHR, description), makeFixedArrayTypeDecl(int32_t(VK_MAX_DESCRIPTION_SIZE), makeType<int8_t>(*mlib)));
}
#endif

#if defined(VK_KHR_performance_query)
struct VkQueryPoolPerformanceCreateInfoKHR_Ann : ManagedStructureAnnotation<VkQueryPoolPerformanceCreateInfoKHR> {
    VkQueryPoolPerformanceCreateInfoKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkQueryPoolPerformanceCreateInfoKHR", ml, "VkQueryPoolPerformanceCreateInfoKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkQueryPoolPerformanceCreateInfoKHR_Ann * ann_VkQueryPoolPerformanceCreateInfoKHR = nullptr;
void VkQueryPoolPerformanceCreateInfoKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkQueryPoolPerformanceCreateInfoKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(queueFamilyIndex)>("queueFamilyIndex", "queueFamilyIndex");
    addField<DAS_BIND_MANAGED_FIELD(counterIndexCount)>("counterIndexCount", "counterIndexCount");
    addFieldEx("pCounterIndices", "pCounterIndices", offsetof(VkQueryPoolPerformanceCreateInfoKHR, pCounterIndices), makeType<uint32_t *>(*mlib));
}
#endif

#if defined(VK_KHR_performance_query)
struct VkPerformanceCounterResultKHR_Ann : ManagedStructureAnnotation<VkPerformanceCounterResultKHR> {
    VkPerformanceCounterResultKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPerformanceCounterResultKHR", ml, "VkPerformanceCounterResultKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPerformanceCounterResultKHR_Ann * ann_VkPerformanceCounterResultKHR = nullptr;
void VkPerformanceCounterResultKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(int32)>("int32", "int32");
    addField<DAS_BIND_MANAGED_FIELD(int64)>("int64", "int64");
    addField<DAS_BIND_MANAGED_FIELD(uint32)>("uint32", "uint32");
    addField<DAS_BIND_MANAGED_FIELD(uint64)>("uint64", "uint64");
    addField<DAS_BIND_MANAGED_FIELD(float32)>("float32", "float32");
    addField<DAS_BIND_MANAGED_FIELD(float64)>("float64", "float64");
}
#endif

#if defined(VK_KHR_performance_query)
struct VkAcquireProfilingLockInfoKHR_Ann : ManagedStructureAnnotation<VkAcquireProfilingLockInfoKHR> {
    VkAcquireProfilingLockInfoKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkAcquireProfilingLockInfoKHR", ml, "VkAcquireProfilingLockInfoKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkAcquireProfilingLockInfoKHR_Ann * ann_VkAcquireProfilingLockInfoKHR = nullptr;
void VkAcquireProfilingLockInfoKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkAcquireProfilingLockInfoKHR, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkAcquireProfilingLockInfoKHR, flags), makeVkFlags_VkAcquireProfilingLockFlagsKHR());
    addField<DAS_BIND_MANAGED_FIELD(timeout)>("timeout", "timeout");
}
#endif

#if defined(VK_KHR_performance_query)
struct VkPerformanceQuerySubmitInfoKHR_Ann : ManagedStructureAnnotation<VkPerformanceQuerySubmitInfoKHR> {
    VkPerformanceQuerySubmitInfoKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPerformanceQuerySubmitInfoKHR", ml, "VkPerformanceQuerySubmitInfoKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPerformanceQuerySubmitInfoKHR_Ann * ann_VkPerformanceQuerySubmitInfoKHR = nullptr;
void VkPerformanceQuerySubmitInfoKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPerformanceQuerySubmitInfoKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(counterPassIndex)>("counterPassIndex", "counterPassIndex");
}
#endif

#if defined(VK_EXT_headless_surface)
struct VkHeadlessSurfaceCreateInfoEXT_Ann : ManagedStructureAnnotation<VkHeadlessSurfaceCreateInfoEXT> {
    VkHeadlessSurfaceCreateInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkHeadlessSurfaceCreateInfoEXT", ml, "VkHeadlessSurfaceCreateInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkHeadlessSurfaceCreateInfoEXT_Ann * ann_VkHeadlessSurfaceCreateInfoEXT = nullptr;
void VkHeadlessSurfaceCreateInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkHeadlessSurfaceCreateInfoEXT, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkHeadlessSurfaceCreateInfoEXT, flags), makeVkFlags_VkHeadlessSurfaceCreateFlagsEXT());
}
#endif

#if defined(VK_NV_coverage_reduction_mode)
struct VkPhysicalDeviceCoverageReductionModeFeaturesNV_Ann : ManagedStructureAnnotation<VkPhysicalDeviceCoverageReductionModeFeaturesNV> {
    VkPhysicalDeviceCoverageReductionModeFeaturesNV_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceCoverageReductionModeFeaturesNV", ml, "VkPhysicalDeviceCoverageReductionModeFeaturesNV") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceCoverageReductionModeFeaturesNV_Ann * ann_VkPhysicalDeviceCoverageReductionModeFeaturesNV = nullptr;
void VkPhysicalDeviceCoverageReductionModeFeaturesNV_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceCoverageReductionModeFeaturesNV, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(coverageReductionMode)>("coverageReductionMode", "coverageReductionMode");
}
#endif

#if defined(VK_NV_coverage_reduction_mode)
struct VkPipelineCoverageReductionStateCreateInfoNV_Ann : ManagedStructureAnnotation<VkPipelineCoverageReductionStateCreateInfoNV> {
    VkPipelineCoverageReductionStateCreateInfoNV_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPipelineCoverageReductionStateCreateInfoNV", ml, "VkPipelineCoverageReductionStateCreateInfoNV") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPipelineCoverageReductionStateCreateInfoNV_Ann * ann_VkPipelineCoverageReductionStateCreateInfoNV = nullptr;
void VkPipelineCoverageReductionStateCreateInfoNV_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPipelineCoverageReductionStateCreateInfoNV, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkPipelineCoverageReductionStateCreateInfoNV, flags), makeVkFlags_VkPipelineCoverageReductionStateCreateFlagsNV());
    addField<DAS_BIND_MANAGED_FIELD(coverageReductionMode)>("coverageReductionMode", "coverageReductionMode");
}
#endif

#if defined(VK_NV_coverage_reduction_mode)
struct VkFramebufferMixedSamplesCombinationNV_Ann : ManagedStructureAnnotation<VkFramebufferMixedSamplesCombinationNV> {
    VkFramebufferMixedSamplesCombinationNV_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkFramebufferMixedSamplesCombinationNV", ml, "VkFramebufferMixedSamplesCombinationNV") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkFramebufferMixedSamplesCombinationNV_Ann * ann_VkFramebufferMixedSamplesCombinationNV = nullptr;
void VkFramebufferMixedSamplesCombinationNV_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkFramebufferMixedSamplesCombinationNV, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(coverageReductionMode)>("coverageReductionMode", "coverageReductionMode");
    addField<DAS_BIND_MANAGED_FIELD(rasterizationSamples)>("rasterizationSamples", "rasterizationSamples");
    addFieldEx("depthStencilSamples", "depthStencilSamples", offsetof(VkFramebufferMixedSamplesCombinationNV, depthStencilSamples), makeVkFlags_VkSampleCountFlags());
    addFieldEx("colorSamples", "colorSamples", offsetof(VkFramebufferMixedSamplesCombinationNV, colorSamples), makeVkFlags_VkSampleCountFlags());
}
#endif

#if defined(VK_INTEL_shader_integer_functions2)
struct VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL_Ann : ManagedStructureAnnotation<VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL> {
    VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL", ml, "VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL_Ann * ann_VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL = nullptr;
void VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(shaderIntegerFunctions2)>("shaderIntegerFunctions2", "shaderIntegerFunctions2");
}
#endif

#if defined(VK_INTEL_performance_query)
struct VkPerformanceValueDataINTEL_Ann : ManagedStructureAnnotation<VkPerformanceValueDataINTEL> {
    VkPerformanceValueDataINTEL_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPerformanceValueDataINTEL", ml, "VkPerformanceValueDataINTEL") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPerformanceValueDataINTEL_Ann * ann_VkPerformanceValueDataINTEL = nullptr;
void VkPerformanceValueDataINTEL_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(value32)>("value32", "value32");
    addField<DAS_BIND_MANAGED_FIELD(value64)>("value64", "value64");
    addField<DAS_BIND_MANAGED_FIELD(valueFloat)>("valueFloat", "valueFloat");
    addField<DAS_BIND_MANAGED_FIELD(valueBool)>("valueBool", "valueBool");
    addFieldEx("valueString", "valueString", offsetof(VkPerformanceValueDataINTEL, valueString), makeType<char *>(*mlib));
}
#endif

#if defined(VK_INTEL_performance_query)
struct VkPerformanceValueINTEL_Ann : ManagedStructureAnnotation<VkPerformanceValueINTEL> {
    VkPerformanceValueINTEL_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPerformanceValueINTEL", ml, "VkPerformanceValueINTEL") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPerformanceValueINTEL_Ann * ann_VkPerformanceValueINTEL = nullptr;
void VkPerformanceValueINTEL_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(type)>("type_", "type");
    addField<DAS_BIND_MANAGED_FIELD(data)>("data", "data");
}
#endif

#if defined(VK_INTEL_performance_query)
struct VkInitializePerformanceApiInfoINTEL_Ann : ManagedStructureAnnotation<VkInitializePerformanceApiInfoINTEL> {
    VkInitializePerformanceApiInfoINTEL_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkInitializePerformanceApiInfoINTEL", ml, "VkInitializePerformanceApiInfoINTEL") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkInitializePerformanceApiInfoINTEL_Ann * ann_VkInitializePerformanceApiInfoINTEL = nullptr;
void VkInitializePerformanceApiInfoINTEL_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkInitializePerformanceApiInfoINTEL, pNext), makeType<void *>(*mlib));
    addFieldEx("pUserData", "pUserData", offsetof(VkInitializePerformanceApiInfoINTEL, pUserData), makeType<void *>(*mlib));
}
#endif

#if defined(VK_INTEL_performance_query)
struct VkQueryPoolPerformanceQueryCreateInfoINTEL_Ann : ManagedStructureAnnotation<VkQueryPoolPerformanceQueryCreateInfoINTEL> {
    VkQueryPoolPerformanceQueryCreateInfoINTEL_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkQueryPoolPerformanceQueryCreateInfoINTEL", ml, "VkQueryPoolPerformanceQueryCreateInfoINTEL") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkQueryPoolPerformanceQueryCreateInfoINTEL_Ann * ann_VkQueryPoolPerformanceQueryCreateInfoINTEL = nullptr;
void VkQueryPoolPerformanceQueryCreateInfoINTEL_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkQueryPoolPerformanceQueryCreateInfoINTEL, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(performanceCountersSampling)>("performanceCountersSampling", "performanceCountersSampling");
}
#endif

#if defined(VK_INTEL_performance_query)
struct VkPerformanceMarkerInfoINTEL_Ann : ManagedStructureAnnotation<VkPerformanceMarkerInfoINTEL> {
    VkPerformanceMarkerInfoINTEL_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPerformanceMarkerInfoINTEL", ml, "VkPerformanceMarkerInfoINTEL") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPerformanceMarkerInfoINTEL_Ann * ann_VkPerformanceMarkerInfoINTEL = nullptr;
void VkPerformanceMarkerInfoINTEL_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPerformanceMarkerInfoINTEL, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(marker)>("marker", "marker");
}
#endif

#if defined(VK_INTEL_performance_query)
struct VkPerformanceStreamMarkerInfoINTEL_Ann : ManagedStructureAnnotation<VkPerformanceStreamMarkerInfoINTEL> {
    VkPerformanceStreamMarkerInfoINTEL_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPerformanceStreamMarkerInfoINTEL", ml, "VkPerformanceStreamMarkerInfoINTEL") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPerformanceStreamMarkerInfoINTEL_Ann * ann_VkPerformanceStreamMarkerInfoINTEL = nullptr;
void VkPerformanceStreamMarkerInfoINTEL_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPerformanceStreamMarkerInfoINTEL, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(marker)>("marker", "marker");
}
#endif

#if defined(VK_INTEL_performance_query)
struct VkPerformanceOverrideInfoINTEL_Ann : ManagedStructureAnnotation<VkPerformanceOverrideInfoINTEL> {
    VkPerformanceOverrideInfoINTEL_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPerformanceOverrideInfoINTEL", ml, "VkPerformanceOverrideInfoINTEL") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPerformanceOverrideInfoINTEL_Ann * ann_VkPerformanceOverrideInfoINTEL = nullptr;
void VkPerformanceOverrideInfoINTEL_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPerformanceOverrideInfoINTEL, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(type)>("type_", "type");
    addField<DAS_BIND_MANAGED_FIELD(enable)>("enable", "enable");
    addField<DAS_BIND_MANAGED_FIELD(parameter)>("parameter", "parameter");
}
#endif

#if defined(VK_INTEL_performance_query)
struct VkPerformanceConfigurationAcquireInfoINTEL_Ann : ManagedStructureAnnotation<VkPerformanceConfigurationAcquireInfoINTEL> {
    VkPerformanceConfigurationAcquireInfoINTEL_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPerformanceConfigurationAcquireInfoINTEL", ml, "VkPerformanceConfigurationAcquireInfoINTEL") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPerformanceConfigurationAcquireInfoINTEL_Ann * ann_VkPerformanceConfigurationAcquireInfoINTEL = nullptr;
void VkPerformanceConfigurationAcquireInfoINTEL_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPerformanceConfigurationAcquireInfoINTEL, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(type)>("type_", "type");
}
#endif

#if defined(VK_KHR_shader_clock)
struct VkPhysicalDeviceShaderClockFeaturesKHR_Ann : ManagedStructureAnnotation<VkPhysicalDeviceShaderClockFeaturesKHR> {
    VkPhysicalDeviceShaderClockFeaturesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceShaderClockFeaturesKHR", ml, "VkPhysicalDeviceShaderClockFeaturesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceShaderClockFeaturesKHR_Ann * ann_VkPhysicalDeviceShaderClockFeaturesKHR = nullptr;
void VkPhysicalDeviceShaderClockFeaturesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceShaderClockFeaturesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(shaderSubgroupClock)>("shaderSubgroupClock", "shaderSubgroupClock");
    addField<DAS_BIND_MANAGED_FIELD(shaderDeviceClock)>("shaderDeviceClock", "shaderDeviceClock");
}
#endif

#if defined(VK_VERSION_1_4)
struct VkPhysicalDeviceIndexTypeUint8Features_Ann : ManagedStructureAnnotation<VkPhysicalDeviceIndexTypeUint8Features> {
    VkPhysicalDeviceIndexTypeUint8Features_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceIndexTypeUint8Features", ml, "VkPhysicalDeviceIndexTypeUint8Features") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceIndexTypeUint8Features_Ann * ann_VkPhysicalDeviceIndexTypeUint8Features = nullptr;
void VkPhysicalDeviceIndexTypeUint8Features_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceIndexTypeUint8Features, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(indexTypeUint8)>("indexTypeUint8", "indexTypeUint8");
}
#endif

#if defined(VK_NV_shader_sm_builtins)
struct VkPhysicalDeviceShaderSMBuiltinsPropertiesNV_Ann : ManagedStructureAnnotation<VkPhysicalDeviceShaderSMBuiltinsPropertiesNV> {
    VkPhysicalDeviceShaderSMBuiltinsPropertiesNV_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceShaderSMBuiltinsPropertiesNV", ml, "VkPhysicalDeviceShaderSMBuiltinsPropertiesNV") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceShaderSMBuiltinsPropertiesNV_Ann * ann_VkPhysicalDeviceShaderSMBuiltinsPropertiesNV = nullptr;
void VkPhysicalDeviceShaderSMBuiltinsPropertiesNV_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceShaderSMBuiltinsPropertiesNV, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(shaderSMCount)>("shaderSMCount", "shaderSMCount");
    addField<DAS_BIND_MANAGED_FIELD(shaderWarpsPerSM)>("shaderWarpsPerSM", "shaderWarpsPerSM");
}
#endif

#if defined(VK_NV_shader_sm_builtins)
struct VkPhysicalDeviceShaderSMBuiltinsFeaturesNV_Ann : ManagedStructureAnnotation<VkPhysicalDeviceShaderSMBuiltinsFeaturesNV> {
    VkPhysicalDeviceShaderSMBuiltinsFeaturesNV_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceShaderSMBuiltinsFeaturesNV", ml, "VkPhysicalDeviceShaderSMBuiltinsFeaturesNV") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceShaderSMBuiltinsFeaturesNV_Ann * ann_VkPhysicalDeviceShaderSMBuiltinsFeaturesNV = nullptr;
void VkPhysicalDeviceShaderSMBuiltinsFeaturesNV_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceShaderSMBuiltinsFeaturesNV, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(shaderSMBuiltins)>("shaderSMBuiltins", "shaderSMBuiltins");
}
#endif

#if defined(VK_EXT_fragment_shader_interlock)
struct VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT_Ann : ManagedStructureAnnotation<VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT> {
    VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT", ml, "VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT_Ann * ann_VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT = nullptr;
void VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(fragmentShaderSampleInterlock)>("fragmentShaderSampleInterlock", "fragmentShaderSampleInterlock");
    addField<DAS_BIND_MANAGED_FIELD(fragmentShaderPixelInterlock)>("fragmentShaderPixelInterlock", "fragmentShaderPixelInterlock");
    addField<DAS_BIND_MANAGED_FIELD(fragmentShaderShadingRateInterlock)>("fragmentShaderShadingRateInterlock", "fragmentShaderShadingRateInterlock");
}
#endif

#if defined(VK_VERSION_1_2)
struct VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures_Ann : ManagedStructureAnnotation<VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures> {
    VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures", ml, "VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures_Ann * ann_VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures = nullptr;
void VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(separateDepthStencilLayouts)>("separateDepthStencilLayouts", "separateDepthStencilLayouts");
}
#endif

#if defined(VK_VERSION_1_2)
struct VkAttachmentReferenceStencilLayout_Ann : ManagedStructureAnnotation<VkAttachmentReferenceStencilLayout> {
    VkAttachmentReferenceStencilLayout_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkAttachmentReferenceStencilLayout", ml, "VkAttachmentReferenceStencilLayout") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkAttachmentReferenceStencilLayout_Ann * ann_VkAttachmentReferenceStencilLayout = nullptr;
void VkAttachmentReferenceStencilLayout_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkAttachmentReferenceStencilLayout, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(stencilLayout)>("stencilLayout", "stencilLayout");
}
#endif

#if defined(VK_EXT_primitive_topology_list_restart)
struct VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT_Ann : ManagedStructureAnnotation<VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT> {
    VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT", ml, "VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT_Ann * ann_VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT = nullptr;
void VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(primitiveTopologyListRestart)>("primitiveTopologyListRestart", "primitiveTopologyListRestart");
    addField<DAS_BIND_MANAGED_FIELD(primitiveTopologyPatchListRestart)>("primitiveTopologyPatchListRestart", "primitiveTopologyPatchListRestart");
}
#endif

#if defined(VK_VERSION_1_2)
struct VkAttachmentDescriptionStencilLayout_Ann : ManagedStructureAnnotation<VkAttachmentDescriptionStencilLayout> {
    VkAttachmentDescriptionStencilLayout_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkAttachmentDescriptionStencilLayout", ml, "VkAttachmentDescriptionStencilLayout") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkAttachmentDescriptionStencilLayout_Ann * ann_VkAttachmentDescriptionStencilLayout = nullptr;
void VkAttachmentDescriptionStencilLayout_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkAttachmentDescriptionStencilLayout, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(stencilInitialLayout)>("stencilInitialLayout", "stencilInitialLayout");
    addField<DAS_BIND_MANAGED_FIELD(stencilFinalLayout)>("stencilFinalLayout", "stencilFinalLayout");
}
#endif

#if defined(VK_KHR_pipeline_executable_properties)
struct VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR_Ann : ManagedStructureAnnotation<VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR> {
    VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR", ml, "VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR_Ann * ann_VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR = nullptr;
void VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(pipelineExecutableInfo)>("pipelineExecutableInfo", "pipelineExecutableInfo");
}
#endif

#if defined(VK_KHR_pipeline_executable_properties)
struct VkPipelineInfoKHR_Ann : ManagedStructureAnnotation<VkPipelineInfoKHR> {
    VkPipelineInfoKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPipelineInfoKHR", ml, "VkPipelineInfoKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPipelineInfoKHR_Ann * ann_VkPipelineInfoKHR = nullptr;
void VkPipelineInfoKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPipelineInfoKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(pipeline)>("pipeline", "pipeline");
}
#endif

#if defined(VK_KHR_pipeline_executable_properties)
struct VkPipelineExecutablePropertiesKHR_Ann : ManagedStructureAnnotation<VkPipelineExecutablePropertiesKHR> {
    VkPipelineExecutablePropertiesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPipelineExecutablePropertiesKHR", ml, "VkPipelineExecutablePropertiesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPipelineExecutablePropertiesKHR_Ann * ann_VkPipelineExecutablePropertiesKHR = nullptr;
void VkPipelineExecutablePropertiesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPipelineExecutablePropertiesKHR, pNext), makeType<void *>(*mlib));
    addFieldEx("stages", "stages", offsetof(VkPipelineExecutablePropertiesKHR, stages), makeVkFlags_VkShaderStageFlags());
    addFieldEx("name", "name", offsetof(VkPipelineExecutablePropertiesKHR, name), makeFixedArrayTypeDecl(int32_t(VK_MAX_DESCRIPTION_SIZE), makeType<int8_t>(*mlib)));
    addFieldEx("description", "description", offsetof(VkPipelineExecutablePropertiesKHR, description), makeFixedArrayTypeDecl(int32_t(VK_MAX_DESCRIPTION_SIZE), makeType<int8_t>(*mlib)));
    addField<DAS_BIND_MANAGED_FIELD(subgroupSize)>("subgroupSize", "subgroupSize");
}
#endif

#if defined(VK_KHR_pipeline_executable_properties)
struct VkPipelineExecutableInfoKHR_Ann : ManagedStructureAnnotation<VkPipelineExecutableInfoKHR> {
    VkPipelineExecutableInfoKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPipelineExecutableInfoKHR", ml, "VkPipelineExecutableInfoKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPipelineExecutableInfoKHR_Ann * ann_VkPipelineExecutableInfoKHR = nullptr;
void VkPipelineExecutableInfoKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPipelineExecutableInfoKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(pipeline)>("pipeline", "pipeline");
    addField<DAS_BIND_MANAGED_FIELD(executableIndex)>("executableIndex", "executableIndex");
}
#endif

#if defined(VK_KHR_pipeline_executable_properties)
struct VkPipelineExecutableStatisticValueKHR_Ann : ManagedStructureAnnotation<VkPipelineExecutableStatisticValueKHR> {
    VkPipelineExecutableStatisticValueKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPipelineExecutableStatisticValueKHR", ml, "VkPipelineExecutableStatisticValueKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPipelineExecutableStatisticValueKHR_Ann * ann_VkPipelineExecutableStatisticValueKHR = nullptr;
void VkPipelineExecutableStatisticValueKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(b32)>("b32", "b32");
    addField<DAS_BIND_MANAGED_FIELD(i64)>("i64", "i64");
    addField<DAS_BIND_MANAGED_FIELD(u64)>("u64", "u64");
    addField<DAS_BIND_MANAGED_FIELD(f64)>("f64", "f64");
}
#endif

void das_vulkan_add_structs_11(Module & mod, ModuleLibrary & lib) {
#if defined(VK_VERSION_1_2)
    ann_VkRenderPassAttachmentBeginInfo = new VkRenderPassAttachmentBeginInfo_Ann(lib); mod.addAnnotation(ann_VkRenderPassAttachmentBeginInfo);
#endif
#if defined(VK_VERSION_1_3)
    ann_VkPhysicalDeviceTextureCompressionASTCHDRFeatures = new VkPhysicalDeviceTextureCompressionASTCHDRFeatures_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceTextureCompressionASTCHDRFeatures);
#endif
#if defined(VK_NV_cooperative_matrix)
    ann_VkPhysicalDeviceCooperativeMatrixFeaturesNV = new VkPhysicalDeviceCooperativeMatrixFeaturesNV_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceCooperativeMatrixFeaturesNV);
#endif
#if defined(VK_NV_cooperative_matrix)
    ann_VkPhysicalDeviceCooperativeMatrixPropertiesNV = new VkPhysicalDeviceCooperativeMatrixPropertiesNV_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceCooperativeMatrixPropertiesNV);
#endif
#if defined(VK_EXT_ycbcr_image_arrays)
    ann_VkPhysicalDeviceYcbcrImageArraysFeaturesEXT = new VkPhysicalDeviceYcbcrImageArraysFeaturesEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceYcbcrImageArraysFeaturesEXT);
#endif
#if defined(VK_NVX_image_view_handle)
    ann_VkImageViewHandleInfoNVX = new VkImageViewHandleInfoNVX_Ann(lib); mod.addAnnotation(ann_VkImageViewHandleInfoNVX);
#endif
#if defined(VK_NVX_image_view_handle)
    ann_VkImageViewAddressPropertiesNVX = new VkImageViewAddressPropertiesNVX_Ann(lib); mod.addAnnotation(ann_VkImageViewAddressPropertiesNVX);
#endif
#if defined(VK_VERSION_1_3)
    ann_VkPipelineCreationFeedback = new VkPipelineCreationFeedback_Ann(lib); mod.addAnnotation(ann_VkPipelineCreationFeedback);
#endif
#if defined(VK_VERSION_1_3)
    ann_VkPipelineCreationFeedbackCreateInfo = new VkPipelineCreationFeedbackCreateInfo_Ann(lib); mod.addAnnotation(ann_VkPipelineCreationFeedbackCreateInfo);
#endif
#if defined(VK_EXT_full_screen_exclusive) && defined(VK_USE_PLATFORM_WIN32_KHR)
    ann_VkSurfaceFullScreenExclusiveInfoEXT = new VkSurfaceFullScreenExclusiveInfoEXT_Ann(lib); mod.addAnnotation(ann_VkSurfaceFullScreenExclusiveInfoEXT);
#endif
#if defined(VK_EXT_full_screen_exclusive) && defined(VK_USE_PLATFORM_WIN32_KHR)
    ann_VkSurfaceFullScreenExclusiveWin32InfoEXT = new VkSurfaceFullScreenExclusiveWin32InfoEXT_Ann(lib); mod.addAnnotation(ann_VkSurfaceFullScreenExclusiveWin32InfoEXT);
#endif
#if defined(VK_EXT_full_screen_exclusive) && defined(VK_USE_PLATFORM_WIN32_KHR)
    ann_VkSurfaceCapabilitiesFullScreenExclusiveEXT = new VkSurfaceCapabilitiesFullScreenExclusiveEXT_Ann(lib); mod.addAnnotation(ann_VkSurfaceCapabilitiesFullScreenExclusiveEXT);
#endif
#if defined(VK_NV_present_barrier)
    ann_VkPhysicalDevicePresentBarrierFeaturesNV = new VkPhysicalDevicePresentBarrierFeaturesNV_Ann(lib); mod.addAnnotation(ann_VkPhysicalDevicePresentBarrierFeaturesNV);
#endif
#if defined(VK_NV_present_barrier)
    ann_VkSurfaceCapabilitiesPresentBarrierNV = new VkSurfaceCapabilitiesPresentBarrierNV_Ann(lib); mod.addAnnotation(ann_VkSurfaceCapabilitiesPresentBarrierNV);
#endif
#if defined(VK_NV_present_barrier)
    ann_VkSwapchainPresentBarrierCreateInfoNV = new VkSwapchainPresentBarrierCreateInfoNV_Ann(lib); mod.addAnnotation(ann_VkSwapchainPresentBarrierCreateInfoNV);
#endif
#if defined(VK_KHR_performance_query)
    ann_VkPhysicalDevicePerformanceQueryFeaturesKHR = new VkPhysicalDevicePerformanceQueryFeaturesKHR_Ann(lib); mod.addAnnotation(ann_VkPhysicalDevicePerformanceQueryFeaturesKHR);
#endif
#if defined(VK_KHR_performance_query)
    ann_VkPhysicalDevicePerformanceQueryPropertiesKHR = new VkPhysicalDevicePerformanceQueryPropertiesKHR_Ann(lib); mod.addAnnotation(ann_VkPhysicalDevicePerformanceQueryPropertiesKHR);
#endif
#if defined(VK_KHR_performance_query)
    ann_VkPerformanceCounterKHR = new VkPerformanceCounterKHR_Ann(lib); mod.addAnnotation(ann_VkPerformanceCounterKHR);
#endif
#if defined(VK_KHR_performance_query)
    ann_VkPerformanceCounterDescriptionKHR = new VkPerformanceCounterDescriptionKHR_Ann(lib); mod.addAnnotation(ann_VkPerformanceCounterDescriptionKHR);
#endif
#if defined(VK_KHR_performance_query)
    ann_VkQueryPoolPerformanceCreateInfoKHR = new VkQueryPoolPerformanceCreateInfoKHR_Ann(lib); mod.addAnnotation(ann_VkQueryPoolPerformanceCreateInfoKHR);
#endif
#if defined(VK_KHR_performance_query)
    ann_VkPerformanceCounterResultKHR = new VkPerformanceCounterResultKHR_Ann(lib); mod.addAnnotation(ann_VkPerformanceCounterResultKHR);
#endif
#if defined(VK_KHR_performance_query)
    ann_VkAcquireProfilingLockInfoKHR = new VkAcquireProfilingLockInfoKHR_Ann(lib); mod.addAnnotation(ann_VkAcquireProfilingLockInfoKHR);
#endif
#if defined(VK_KHR_performance_query)
    ann_VkPerformanceQuerySubmitInfoKHR = new VkPerformanceQuerySubmitInfoKHR_Ann(lib); mod.addAnnotation(ann_VkPerformanceQuerySubmitInfoKHR);
#endif
#if defined(VK_EXT_headless_surface)
    ann_VkHeadlessSurfaceCreateInfoEXT = new VkHeadlessSurfaceCreateInfoEXT_Ann(lib); mod.addAnnotation(ann_VkHeadlessSurfaceCreateInfoEXT);
#endif
#if defined(VK_NV_coverage_reduction_mode)
    ann_VkPhysicalDeviceCoverageReductionModeFeaturesNV = new VkPhysicalDeviceCoverageReductionModeFeaturesNV_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceCoverageReductionModeFeaturesNV);
#endif
#if defined(VK_NV_coverage_reduction_mode)
    ann_VkPipelineCoverageReductionStateCreateInfoNV = new VkPipelineCoverageReductionStateCreateInfoNV_Ann(lib); mod.addAnnotation(ann_VkPipelineCoverageReductionStateCreateInfoNV);
#endif
#if defined(VK_NV_coverage_reduction_mode)
    ann_VkFramebufferMixedSamplesCombinationNV = new VkFramebufferMixedSamplesCombinationNV_Ann(lib); mod.addAnnotation(ann_VkFramebufferMixedSamplesCombinationNV);
#endif
#if defined(VK_INTEL_shader_integer_functions2)
    ann_VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL = new VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL);
#endif
#if defined(VK_INTEL_performance_query)
    ann_VkPerformanceValueDataINTEL = new VkPerformanceValueDataINTEL_Ann(lib); mod.addAnnotation(ann_VkPerformanceValueDataINTEL);
#endif
#if defined(VK_INTEL_performance_query)
    ann_VkPerformanceValueINTEL = new VkPerformanceValueINTEL_Ann(lib); mod.addAnnotation(ann_VkPerformanceValueINTEL);
#endif
#if defined(VK_INTEL_performance_query)
    ann_VkInitializePerformanceApiInfoINTEL = new VkInitializePerformanceApiInfoINTEL_Ann(lib); mod.addAnnotation(ann_VkInitializePerformanceApiInfoINTEL);
#endif
#if defined(VK_INTEL_performance_query)
    ann_VkQueryPoolPerformanceQueryCreateInfoINTEL = new VkQueryPoolPerformanceQueryCreateInfoINTEL_Ann(lib); mod.addAnnotation(ann_VkQueryPoolPerformanceQueryCreateInfoINTEL);
#endif
#if defined(VK_INTEL_performance_query)
    ann_VkPerformanceMarkerInfoINTEL = new VkPerformanceMarkerInfoINTEL_Ann(lib); mod.addAnnotation(ann_VkPerformanceMarkerInfoINTEL);
#endif
#if defined(VK_INTEL_performance_query)
    ann_VkPerformanceStreamMarkerInfoINTEL = new VkPerformanceStreamMarkerInfoINTEL_Ann(lib); mod.addAnnotation(ann_VkPerformanceStreamMarkerInfoINTEL);
#endif
#if defined(VK_INTEL_performance_query)
    ann_VkPerformanceOverrideInfoINTEL = new VkPerformanceOverrideInfoINTEL_Ann(lib); mod.addAnnotation(ann_VkPerformanceOverrideInfoINTEL);
#endif
#if defined(VK_INTEL_performance_query)
    ann_VkPerformanceConfigurationAcquireInfoINTEL = new VkPerformanceConfigurationAcquireInfoINTEL_Ann(lib); mod.addAnnotation(ann_VkPerformanceConfigurationAcquireInfoINTEL);
#endif
#if defined(VK_KHR_shader_clock)
    ann_VkPhysicalDeviceShaderClockFeaturesKHR = new VkPhysicalDeviceShaderClockFeaturesKHR_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceShaderClockFeaturesKHR);
#endif
#if defined(VK_VERSION_1_4)
    ann_VkPhysicalDeviceIndexTypeUint8Features = new VkPhysicalDeviceIndexTypeUint8Features_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceIndexTypeUint8Features);
#endif
#if defined(VK_NV_shader_sm_builtins)
    ann_VkPhysicalDeviceShaderSMBuiltinsPropertiesNV = new VkPhysicalDeviceShaderSMBuiltinsPropertiesNV_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceShaderSMBuiltinsPropertiesNV);
#endif
#if defined(VK_NV_shader_sm_builtins)
    ann_VkPhysicalDeviceShaderSMBuiltinsFeaturesNV = new VkPhysicalDeviceShaderSMBuiltinsFeaturesNV_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceShaderSMBuiltinsFeaturesNV);
#endif
#if defined(VK_EXT_fragment_shader_interlock)
    ann_VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT = new VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT);
#endif
#if defined(VK_VERSION_1_2)
    ann_VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures = new VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures);
#endif
#if defined(VK_VERSION_1_2)
    ann_VkAttachmentReferenceStencilLayout = new VkAttachmentReferenceStencilLayout_Ann(lib); mod.addAnnotation(ann_VkAttachmentReferenceStencilLayout);
#endif
#if defined(VK_EXT_primitive_topology_list_restart)
    ann_VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT = new VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT);
#endif
#if defined(VK_VERSION_1_2)
    ann_VkAttachmentDescriptionStencilLayout = new VkAttachmentDescriptionStencilLayout_Ann(lib); mod.addAnnotation(ann_VkAttachmentDescriptionStencilLayout);
#endif
#if defined(VK_KHR_pipeline_executable_properties)
    ann_VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR = new VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR_Ann(lib); mod.addAnnotation(ann_VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR);
#endif
#if defined(VK_KHR_pipeline_executable_properties)
    ann_VkPipelineInfoKHR = new VkPipelineInfoKHR_Ann(lib); mod.addAnnotation(ann_VkPipelineInfoKHR);
#endif
#if defined(VK_KHR_pipeline_executable_properties)
    ann_VkPipelineExecutablePropertiesKHR = new VkPipelineExecutablePropertiesKHR_Ann(lib); mod.addAnnotation(ann_VkPipelineExecutablePropertiesKHR);
#endif
#if defined(VK_KHR_pipeline_executable_properties)
    ann_VkPipelineExecutableInfoKHR = new VkPipelineExecutableInfoKHR_Ann(lib); mod.addAnnotation(ann_VkPipelineExecutableInfoKHR);
#endif
#if defined(VK_KHR_pipeline_executable_properties)
    ann_VkPipelineExecutableStatisticValueKHR = new VkPipelineExecutableStatisticValueKHR_Ann(lib); mod.addAnnotation(ann_VkPipelineExecutableStatisticValueKHR);
#endif
}

void das_vulkan_fill_structs_11(Module & mod, ModuleLibrary & lib) {
#if defined(VK_VERSION_1_2)
    ann_VkRenderPassAttachmentBeginInfo->mlib = &lib; ann_VkRenderPassAttachmentBeginInfo->init(); ann_VkRenderPassAttachmentBeginInfo->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_3)
    ann_VkPhysicalDeviceTextureCompressionASTCHDRFeatures->mlib = &lib; ann_VkPhysicalDeviceTextureCompressionASTCHDRFeatures->init(); ann_VkPhysicalDeviceTextureCompressionASTCHDRFeatures->mlib = nullptr;
#endif
#if defined(VK_NV_cooperative_matrix)
    ann_VkPhysicalDeviceCooperativeMatrixFeaturesNV->mlib = &lib; ann_VkPhysicalDeviceCooperativeMatrixFeaturesNV->init(); ann_VkPhysicalDeviceCooperativeMatrixFeaturesNV->mlib = nullptr;
#endif
#if defined(VK_NV_cooperative_matrix)
    ann_VkPhysicalDeviceCooperativeMatrixPropertiesNV->mlib = &lib; ann_VkPhysicalDeviceCooperativeMatrixPropertiesNV->init(); ann_VkPhysicalDeviceCooperativeMatrixPropertiesNV->mlib = nullptr;
#endif
#if defined(VK_EXT_ycbcr_image_arrays)
    ann_VkPhysicalDeviceYcbcrImageArraysFeaturesEXT->mlib = &lib; ann_VkPhysicalDeviceYcbcrImageArraysFeaturesEXT->init(); ann_VkPhysicalDeviceYcbcrImageArraysFeaturesEXT->mlib = nullptr;
#endif
#if defined(VK_NVX_image_view_handle)
    ann_VkImageViewHandleInfoNVX->mlib = &lib; ann_VkImageViewHandleInfoNVX->init(); ann_VkImageViewHandleInfoNVX->mlib = nullptr;
#endif
#if defined(VK_NVX_image_view_handle)
    ann_VkImageViewAddressPropertiesNVX->mlib = &lib; ann_VkImageViewAddressPropertiesNVX->init(); ann_VkImageViewAddressPropertiesNVX->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_3)
    ann_VkPipelineCreationFeedback->mlib = &lib; ann_VkPipelineCreationFeedback->init(); ann_VkPipelineCreationFeedback->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_3)
    ann_VkPipelineCreationFeedbackCreateInfo->mlib = &lib; ann_VkPipelineCreationFeedbackCreateInfo->init(); ann_VkPipelineCreationFeedbackCreateInfo->mlib = nullptr;
#endif
#if defined(VK_EXT_full_screen_exclusive) && defined(VK_USE_PLATFORM_WIN32_KHR)
    ann_VkSurfaceFullScreenExclusiveInfoEXT->mlib = &lib; ann_VkSurfaceFullScreenExclusiveInfoEXT->init(); ann_VkSurfaceFullScreenExclusiveInfoEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_full_screen_exclusive) && defined(VK_USE_PLATFORM_WIN32_KHR)
    ann_VkSurfaceFullScreenExclusiveWin32InfoEXT->mlib = &lib; ann_VkSurfaceFullScreenExclusiveWin32InfoEXT->init(); ann_VkSurfaceFullScreenExclusiveWin32InfoEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_full_screen_exclusive) && defined(VK_USE_PLATFORM_WIN32_KHR)
    ann_VkSurfaceCapabilitiesFullScreenExclusiveEXT->mlib = &lib; ann_VkSurfaceCapabilitiesFullScreenExclusiveEXT->init(); ann_VkSurfaceCapabilitiesFullScreenExclusiveEXT->mlib = nullptr;
#endif
#if defined(VK_NV_present_barrier)
    ann_VkPhysicalDevicePresentBarrierFeaturesNV->mlib = &lib; ann_VkPhysicalDevicePresentBarrierFeaturesNV->init(); ann_VkPhysicalDevicePresentBarrierFeaturesNV->mlib = nullptr;
#endif
#if defined(VK_NV_present_barrier)
    ann_VkSurfaceCapabilitiesPresentBarrierNV->mlib = &lib; ann_VkSurfaceCapabilitiesPresentBarrierNV->init(); ann_VkSurfaceCapabilitiesPresentBarrierNV->mlib = nullptr;
#endif
#if defined(VK_NV_present_barrier)
    ann_VkSwapchainPresentBarrierCreateInfoNV->mlib = &lib; ann_VkSwapchainPresentBarrierCreateInfoNV->init(); ann_VkSwapchainPresentBarrierCreateInfoNV->mlib = nullptr;
#endif
#if defined(VK_KHR_performance_query)
    ann_VkPhysicalDevicePerformanceQueryFeaturesKHR->mlib = &lib; ann_VkPhysicalDevicePerformanceQueryFeaturesKHR->init(); ann_VkPhysicalDevicePerformanceQueryFeaturesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_performance_query)
    ann_VkPhysicalDevicePerformanceQueryPropertiesKHR->mlib = &lib; ann_VkPhysicalDevicePerformanceQueryPropertiesKHR->init(); ann_VkPhysicalDevicePerformanceQueryPropertiesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_performance_query)
    ann_VkPerformanceCounterKHR->mlib = &lib; ann_VkPerformanceCounterKHR->init(); ann_VkPerformanceCounterKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_performance_query)
    ann_VkPerformanceCounterDescriptionKHR->mlib = &lib; ann_VkPerformanceCounterDescriptionKHR->init(); ann_VkPerformanceCounterDescriptionKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_performance_query)
    ann_VkQueryPoolPerformanceCreateInfoKHR->mlib = &lib; ann_VkQueryPoolPerformanceCreateInfoKHR->init(); ann_VkQueryPoolPerformanceCreateInfoKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_performance_query)
    ann_VkPerformanceCounterResultKHR->mlib = &lib; ann_VkPerformanceCounterResultKHR->init(); ann_VkPerformanceCounterResultKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_performance_query)
    ann_VkAcquireProfilingLockInfoKHR->mlib = &lib; ann_VkAcquireProfilingLockInfoKHR->init(); ann_VkAcquireProfilingLockInfoKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_performance_query)
    ann_VkPerformanceQuerySubmitInfoKHR->mlib = &lib; ann_VkPerformanceQuerySubmitInfoKHR->init(); ann_VkPerformanceQuerySubmitInfoKHR->mlib = nullptr;
#endif
#if defined(VK_EXT_headless_surface)
    ann_VkHeadlessSurfaceCreateInfoEXT->mlib = &lib; ann_VkHeadlessSurfaceCreateInfoEXT->init(); ann_VkHeadlessSurfaceCreateInfoEXT->mlib = nullptr;
#endif
#if defined(VK_NV_coverage_reduction_mode)
    ann_VkPhysicalDeviceCoverageReductionModeFeaturesNV->mlib = &lib; ann_VkPhysicalDeviceCoverageReductionModeFeaturesNV->init(); ann_VkPhysicalDeviceCoverageReductionModeFeaturesNV->mlib = nullptr;
#endif
#if defined(VK_NV_coverage_reduction_mode)
    ann_VkPipelineCoverageReductionStateCreateInfoNV->mlib = &lib; ann_VkPipelineCoverageReductionStateCreateInfoNV->init(); ann_VkPipelineCoverageReductionStateCreateInfoNV->mlib = nullptr;
#endif
#if defined(VK_NV_coverage_reduction_mode)
    ann_VkFramebufferMixedSamplesCombinationNV->mlib = &lib; ann_VkFramebufferMixedSamplesCombinationNV->init(); ann_VkFramebufferMixedSamplesCombinationNV->mlib = nullptr;
#endif
#if defined(VK_INTEL_shader_integer_functions2)
    ann_VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL->mlib = &lib; ann_VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL->init(); ann_VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL->mlib = nullptr;
#endif
#if defined(VK_INTEL_performance_query)
    ann_VkPerformanceValueDataINTEL->mlib = &lib; ann_VkPerformanceValueDataINTEL->init(); ann_VkPerformanceValueDataINTEL->mlib = nullptr;
#endif
#if defined(VK_INTEL_performance_query)
    ann_VkPerformanceValueINTEL->mlib = &lib; ann_VkPerformanceValueINTEL->init(); ann_VkPerformanceValueINTEL->mlib = nullptr;
#endif
#if defined(VK_INTEL_performance_query)
    ann_VkInitializePerformanceApiInfoINTEL->mlib = &lib; ann_VkInitializePerformanceApiInfoINTEL->init(); ann_VkInitializePerformanceApiInfoINTEL->mlib = nullptr;
#endif
#if defined(VK_INTEL_performance_query)
    ann_VkQueryPoolPerformanceQueryCreateInfoINTEL->mlib = &lib; ann_VkQueryPoolPerformanceQueryCreateInfoINTEL->init(); ann_VkQueryPoolPerformanceQueryCreateInfoINTEL->mlib = nullptr;
#endif
#if defined(VK_INTEL_performance_query)
    ann_VkPerformanceMarkerInfoINTEL->mlib = &lib; ann_VkPerformanceMarkerInfoINTEL->init(); ann_VkPerformanceMarkerInfoINTEL->mlib = nullptr;
#endif
#if defined(VK_INTEL_performance_query)
    ann_VkPerformanceStreamMarkerInfoINTEL->mlib = &lib; ann_VkPerformanceStreamMarkerInfoINTEL->init(); ann_VkPerformanceStreamMarkerInfoINTEL->mlib = nullptr;
#endif
#if defined(VK_INTEL_performance_query)
    ann_VkPerformanceOverrideInfoINTEL->mlib = &lib; ann_VkPerformanceOverrideInfoINTEL->init(); ann_VkPerformanceOverrideInfoINTEL->mlib = nullptr;
#endif
#if defined(VK_INTEL_performance_query)
    ann_VkPerformanceConfigurationAcquireInfoINTEL->mlib = &lib; ann_VkPerformanceConfigurationAcquireInfoINTEL->init(); ann_VkPerformanceConfigurationAcquireInfoINTEL->mlib = nullptr;
#endif
#if defined(VK_KHR_shader_clock)
    ann_VkPhysicalDeviceShaderClockFeaturesKHR->mlib = &lib; ann_VkPhysicalDeviceShaderClockFeaturesKHR->init(); ann_VkPhysicalDeviceShaderClockFeaturesKHR->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_4)
    ann_VkPhysicalDeviceIndexTypeUint8Features->mlib = &lib; ann_VkPhysicalDeviceIndexTypeUint8Features->init(); ann_VkPhysicalDeviceIndexTypeUint8Features->mlib = nullptr;
#endif
#if defined(VK_NV_shader_sm_builtins)
    ann_VkPhysicalDeviceShaderSMBuiltinsPropertiesNV->mlib = &lib; ann_VkPhysicalDeviceShaderSMBuiltinsPropertiesNV->init(); ann_VkPhysicalDeviceShaderSMBuiltinsPropertiesNV->mlib = nullptr;
#endif
#if defined(VK_NV_shader_sm_builtins)
    ann_VkPhysicalDeviceShaderSMBuiltinsFeaturesNV->mlib = &lib; ann_VkPhysicalDeviceShaderSMBuiltinsFeaturesNV->init(); ann_VkPhysicalDeviceShaderSMBuiltinsFeaturesNV->mlib = nullptr;
#endif
#if defined(VK_EXT_fragment_shader_interlock)
    ann_VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT->mlib = &lib; ann_VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT->init(); ann_VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_2)
    ann_VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures->mlib = &lib; ann_VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures->init(); ann_VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_2)
    ann_VkAttachmentReferenceStencilLayout->mlib = &lib; ann_VkAttachmentReferenceStencilLayout->init(); ann_VkAttachmentReferenceStencilLayout->mlib = nullptr;
#endif
#if defined(VK_EXT_primitive_topology_list_restart)
    ann_VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT->mlib = &lib; ann_VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT->init(); ann_VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_2)
    ann_VkAttachmentDescriptionStencilLayout->mlib = &lib; ann_VkAttachmentDescriptionStencilLayout->init(); ann_VkAttachmentDescriptionStencilLayout->mlib = nullptr;
#endif
#if defined(VK_KHR_pipeline_executable_properties)
    ann_VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR->mlib = &lib; ann_VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR->init(); ann_VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_pipeline_executable_properties)
    ann_VkPipelineInfoKHR->mlib = &lib; ann_VkPipelineInfoKHR->init(); ann_VkPipelineInfoKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_pipeline_executable_properties)
    ann_VkPipelineExecutablePropertiesKHR->mlib = &lib; ann_VkPipelineExecutablePropertiesKHR->init(); ann_VkPipelineExecutablePropertiesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_pipeline_executable_properties)
    ann_VkPipelineExecutableInfoKHR->mlib = &lib; ann_VkPipelineExecutableInfoKHR->init(); ann_VkPipelineExecutableInfoKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_pipeline_executable_properties)
    ann_VkPipelineExecutableStatisticValueKHR->mlib = &lib; ann_VkPipelineExecutableStatisticValueKHR->init(); ann_VkPipelineExecutableStatisticValueKHR->mlib = nullptr;
#endif
}

}
