// generated by generator/generate.das -- DO NOT EDIT

#include "dasVULKAN.h"

namespace das {

#if defined(VK_KHR_external_fence_win32) && defined(VK_USE_PLATFORM_WIN32_KHR)
struct VkFenceGetWin32HandleInfoKHR_Ann : ManagedStructureAnnotation<VkFenceGetWin32HandleInfoKHR> {
    VkFenceGetWin32HandleInfoKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkFenceGetWin32HandleInfoKHR", ml, "VkFenceGetWin32HandleInfoKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkFenceGetWin32HandleInfoKHR_Ann * ann_VkFenceGetWin32HandleInfoKHR = nullptr;
void VkFenceGetWin32HandleInfoKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkFenceGetWin32HandleInfoKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(fence)>("fence", "fence");
    addField<DAS_BIND_MANAGED_FIELD(handleType)>("handleType", "handleType");
}
#endif

#if defined(VK_KHR_external_fence_fd)
struct VkImportFenceFdInfoKHR_Ann : ManagedStructureAnnotation<VkImportFenceFdInfoKHR> {
    VkImportFenceFdInfoKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkImportFenceFdInfoKHR", ml, "VkImportFenceFdInfoKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkImportFenceFdInfoKHR_Ann * ann_VkImportFenceFdInfoKHR = nullptr;
void VkImportFenceFdInfoKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkImportFenceFdInfoKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(fence)>("fence", "fence");
    addFieldEx("flags", "flags", offsetof(VkImportFenceFdInfoKHR, flags), makeVkFlags_VkFenceImportFlags());
    addField<DAS_BIND_MANAGED_FIELD(handleType)>("handleType", "handleType");
    addField<DAS_BIND_MANAGED_FIELD(fd)>("fd", "fd");
}
#endif

#if defined(VK_KHR_external_fence_fd)
struct VkFenceGetFdInfoKHR_Ann : ManagedStructureAnnotation<VkFenceGetFdInfoKHR> {
    VkFenceGetFdInfoKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkFenceGetFdInfoKHR", ml, "VkFenceGetFdInfoKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkFenceGetFdInfoKHR_Ann * ann_VkFenceGetFdInfoKHR = nullptr;
void VkFenceGetFdInfoKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkFenceGetFdInfoKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(fence)>("fence", "fence");
    addField<DAS_BIND_MANAGED_FIELD(handleType)>("handleType", "handleType");
}
#endif

#if defined(VK_VERSION_1_1)
struct VkPhysicalDeviceMultiviewFeatures_Ann : ManagedStructureAnnotation<VkPhysicalDeviceMultiviewFeatures> {
    VkPhysicalDeviceMultiviewFeatures_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceMultiviewFeatures", ml, "VkPhysicalDeviceMultiviewFeatures") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceMultiviewFeatures_Ann * ann_VkPhysicalDeviceMultiviewFeatures = nullptr;
void VkPhysicalDeviceMultiviewFeatures_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceMultiviewFeatures, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(multiview)>("multiview", "multiview");
    addField<DAS_BIND_MANAGED_FIELD(multiviewGeometryShader)>("multiviewGeometryShader", "multiviewGeometryShader");
    addField<DAS_BIND_MANAGED_FIELD(multiviewTessellationShader)>("multiviewTessellationShader", "multiviewTessellationShader");
}
#endif

#if defined(VK_VERSION_1_1)
struct VkPhysicalDeviceMultiviewProperties_Ann : ManagedStructureAnnotation<VkPhysicalDeviceMultiviewProperties> {
    VkPhysicalDeviceMultiviewProperties_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceMultiviewProperties", ml, "VkPhysicalDeviceMultiviewProperties") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceMultiviewProperties_Ann * ann_VkPhysicalDeviceMultiviewProperties = nullptr;
void VkPhysicalDeviceMultiviewProperties_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceMultiviewProperties, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(maxMultiviewViewCount)>("maxMultiviewViewCount", "maxMultiviewViewCount");
    addField<DAS_BIND_MANAGED_FIELD(maxMultiviewInstanceIndex)>("maxMultiviewInstanceIndex", "maxMultiviewInstanceIndex");
}
#endif

#if defined(VK_VERSION_1_1)
struct VkRenderPassMultiviewCreateInfo_Ann : ManagedStructureAnnotation<VkRenderPassMultiviewCreateInfo> {
    VkRenderPassMultiviewCreateInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkRenderPassMultiviewCreateInfo", ml, "VkRenderPassMultiviewCreateInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkRenderPassMultiviewCreateInfo_Ann * ann_VkRenderPassMultiviewCreateInfo = nullptr;
void VkRenderPassMultiviewCreateInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkRenderPassMultiviewCreateInfo, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(subpassCount)>("subpassCount", "subpassCount");
    addFieldEx("pViewMasks", "pViewMasks", offsetof(VkRenderPassMultiviewCreateInfo, pViewMasks), makeType<uint32_t *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(dependencyCount)>("dependencyCount", "dependencyCount");
    addFieldEx("pViewOffsets", "pViewOffsets", offsetof(VkRenderPassMultiviewCreateInfo, pViewOffsets), makeType<int32_t *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(correlationMaskCount)>("correlationMaskCount", "correlationMaskCount");
    addFieldEx("pCorrelationMasks", "pCorrelationMasks", offsetof(VkRenderPassMultiviewCreateInfo, pCorrelationMasks), makeType<uint32_t *>(*mlib));
}
#endif

#if defined(VK_EXT_display_surface_counter)
struct VkSurfaceCapabilities2EXT_Ann : ManagedStructureAnnotation<VkSurfaceCapabilities2EXT> {
    VkSurfaceCapabilities2EXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkSurfaceCapabilities2EXT", ml, "VkSurfaceCapabilities2EXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkSurfaceCapabilities2EXT_Ann * ann_VkSurfaceCapabilities2EXT = nullptr;
void VkSurfaceCapabilities2EXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkSurfaceCapabilities2EXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(minImageCount)>("minImageCount", "minImageCount");
    addField<DAS_BIND_MANAGED_FIELD(maxImageCount)>("maxImageCount", "maxImageCount");
    addField<DAS_BIND_MANAGED_FIELD(currentExtent)>("currentExtent", "currentExtent");
    addField<DAS_BIND_MANAGED_FIELD(minImageExtent)>("minImageExtent", "minImageExtent");
    addField<DAS_BIND_MANAGED_FIELD(maxImageExtent)>("maxImageExtent", "maxImageExtent");
    addField<DAS_BIND_MANAGED_FIELD(maxImageArrayLayers)>("maxImageArrayLayers", "maxImageArrayLayers");
    addFieldEx("supportedTransforms", "supportedTransforms", offsetof(VkSurfaceCapabilities2EXT, supportedTransforms), makeVkFlags_VkSurfaceTransformFlagsKHR());
    addField<DAS_BIND_MANAGED_FIELD(currentTransform)>("currentTransform", "currentTransform");
    addFieldEx("supportedCompositeAlpha", "supportedCompositeAlpha", offsetof(VkSurfaceCapabilities2EXT, supportedCompositeAlpha), makeVkFlags_VkCompositeAlphaFlagsKHR());
    addFieldEx("supportedUsageFlags", "supportedUsageFlags", offsetof(VkSurfaceCapabilities2EXT, supportedUsageFlags), makeVkFlags_VkImageUsageFlags());
    addFieldEx("supportedSurfaceCounters", "supportedSurfaceCounters", offsetof(VkSurfaceCapabilities2EXT, supportedSurfaceCounters), makeVkFlags_VkSurfaceCounterFlagsEXT());
}
#endif

#if defined(VK_EXT_display_control)
struct VkDisplayPowerInfoEXT_Ann : ManagedStructureAnnotation<VkDisplayPowerInfoEXT> {
    VkDisplayPowerInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDisplayPowerInfoEXT", ml, "VkDisplayPowerInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDisplayPowerInfoEXT_Ann * ann_VkDisplayPowerInfoEXT = nullptr;
void VkDisplayPowerInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDisplayPowerInfoEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(powerState)>("powerState", "powerState");
}
#endif

#if defined(VK_EXT_display_control)
struct VkDeviceEventInfoEXT_Ann : ManagedStructureAnnotation<VkDeviceEventInfoEXT> {
    VkDeviceEventInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDeviceEventInfoEXT", ml, "VkDeviceEventInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDeviceEventInfoEXT_Ann * ann_VkDeviceEventInfoEXT = nullptr;
void VkDeviceEventInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDeviceEventInfoEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(deviceEvent)>("deviceEvent", "deviceEvent");
}
#endif

#if defined(VK_EXT_display_control)
struct VkDisplayEventInfoEXT_Ann : ManagedStructureAnnotation<VkDisplayEventInfoEXT> {
    VkDisplayEventInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDisplayEventInfoEXT", ml, "VkDisplayEventInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDisplayEventInfoEXT_Ann * ann_VkDisplayEventInfoEXT = nullptr;
void VkDisplayEventInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDisplayEventInfoEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(displayEvent)>("displayEvent", "displayEvent");
}
#endif

#if defined(VK_EXT_display_control)
struct VkSwapchainCounterCreateInfoEXT_Ann : ManagedStructureAnnotation<VkSwapchainCounterCreateInfoEXT> {
    VkSwapchainCounterCreateInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkSwapchainCounterCreateInfoEXT", ml, "VkSwapchainCounterCreateInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkSwapchainCounterCreateInfoEXT_Ann * ann_VkSwapchainCounterCreateInfoEXT = nullptr;
void VkSwapchainCounterCreateInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkSwapchainCounterCreateInfoEXT, pNext), makeType<void *>(*mlib));
    addFieldEx("surfaceCounters", "surfaceCounters", offsetof(VkSwapchainCounterCreateInfoEXT, surfaceCounters), makeVkFlags_VkSurfaceCounterFlagsEXT());
}
#endif

#if defined(VK_VERSION_1_1)
struct VkPhysicalDeviceGroupProperties_Ann : ManagedStructureAnnotation<VkPhysicalDeviceGroupProperties> {
    VkPhysicalDeviceGroupProperties_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceGroupProperties", ml, "VkPhysicalDeviceGroupProperties") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceGroupProperties_Ann * ann_VkPhysicalDeviceGroupProperties = nullptr;
void VkPhysicalDeviceGroupProperties_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceGroupProperties, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(physicalDeviceCount)>("physicalDeviceCount", "physicalDeviceCount");
    addFieldEx("physicalDevices", "physicalDevices", offsetof(VkPhysicalDeviceGroupProperties, physicalDevices), makeFixedArrayTypeDecl(int32_t(VK_MAX_DEVICE_GROUP_SIZE), makeType<VkPhysicalDevice>(*mlib)));
    addField<DAS_BIND_MANAGED_FIELD(subsetAllocation)>("subsetAllocation", "subsetAllocation");
}
#endif

#if defined(VK_VERSION_1_1)
struct VkMemoryAllocateFlagsInfo_Ann : ManagedStructureAnnotation<VkMemoryAllocateFlagsInfo> {
    VkMemoryAllocateFlagsInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkMemoryAllocateFlagsInfo", ml, "VkMemoryAllocateFlagsInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkMemoryAllocateFlagsInfo_Ann * ann_VkMemoryAllocateFlagsInfo = nullptr;
void VkMemoryAllocateFlagsInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkMemoryAllocateFlagsInfo, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkMemoryAllocateFlagsInfo, flags), makeVkFlags_VkMemoryAllocateFlags());
    addField<DAS_BIND_MANAGED_FIELD(deviceMask)>("deviceMask", "deviceMask");
}
#endif

#if defined(VK_VERSION_1_1)
struct VkBindBufferMemoryInfo_Ann : ManagedStructureAnnotation<VkBindBufferMemoryInfo> {
    VkBindBufferMemoryInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkBindBufferMemoryInfo", ml, "VkBindBufferMemoryInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkBindBufferMemoryInfo_Ann * ann_VkBindBufferMemoryInfo = nullptr;
void VkBindBufferMemoryInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkBindBufferMemoryInfo, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(buffer)>("buffer", "buffer");
    addField<DAS_BIND_MANAGED_FIELD(memory)>("memory", "memory");
    addField<DAS_BIND_MANAGED_FIELD(memoryOffset)>("memoryOffset", "memoryOffset");
}
#endif

#if defined(VK_VERSION_1_1)
struct VkBindBufferMemoryDeviceGroupInfo_Ann : ManagedStructureAnnotation<VkBindBufferMemoryDeviceGroupInfo> {
    VkBindBufferMemoryDeviceGroupInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkBindBufferMemoryDeviceGroupInfo", ml, "VkBindBufferMemoryDeviceGroupInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkBindBufferMemoryDeviceGroupInfo_Ann * ann_VkBindBufferMemoryDeviceGroupInfo = nullptr;
void VkBindBufferMemoryDeviceGroupInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkBindBufferMemoryDeviceGroupInfo, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(deviceIndexCount)>("deviceIndexCount", "deviceIndexCount");
    addFieldEx("pDeviceIndices", "pDeviceIndices", offsetof(VkBindBufferMemoryDeviceGroupInfo, pDeviceIndices), makeType<uint32_t *>(*mlib));
}
#endif

#if defined(VK_VERSION_1_1)
struct VkBindImageMemoryInfo_Ann : ManagedStructureAnnotation<VkBindImageMemoryInfo> {
    VkBindImageMemoryInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkBindImageMemoryInfo", ml, "VkBindImageMemoryInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkBindImageMemoryInfo_Ann * ann_VkBindImageMemoryInfo = nullptr;
void VkBindImageMemoryInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkBindImageMemoryInfo, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(image)>("image", "image");
    addField<DAS_BIND_MANAGED_FIELD(memory)>("memory", "memory");
    addField<DAS_BIND_MANAGED_FIELD(memoryOffset)>("memoryOffset", "memoryOffset");
}
#endif

#if defined(VK_VERSION_1_1)
struct VkBindImageMemoryDeviceGroupInfo_Ann : ManagedStructureAnnotation<VkBindImageMemoryDeviceGroupInfo> {
    VkBindImageMemoryDeviceGroupInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkBindImageMemoryDeviceGroupInfo", ml, "VkBindImageMemoryDeviceGroupInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkBindImageMemoryDeviceGroupInfo_Ann * ann_VkBindImageMemoryDeviceGroupInfo = nullptr;
void VkBindImageMemoryDeviceGroupInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkBindImageMemoryDeviceGroupInfo, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(deviceIndexCount)>("deviceIndexCount", "deviceIndexCount");
    addFieldEx("pDeviceIndices", "pDeviceIndices", offsetof(VkBindImageMemoryDeviceGroupInfo, pDeviceIndices), makeType<uint32_t *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(splitInstanceBindRegionCount)>("splitInstanceBindRegionCount", "splitInstanceBindRegionCount");
    addFieldEx("pSplitInstanceBindRegions", "pSplitInstanceBindRegions", offsetof(VkBindImageMemoryDeviceGroupInfo, pSplitInstanceBindRegions), makeType<VkRect2D *>(*mlib));
}
#endif

#if defined(VK_VERSION_1_1)
struct VkDeviceGroupRenderPassBeginInfo_Ann : ManagedStructureAnnotation<VkDeviceGroupRenderPassBeginInfo> {
    VkDeviceGroupRenderPassBeginInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDeviceGroupRenderPassBeginInfo", ml, "VkDeviceGroupRenderPassBeginInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDeviceGroupRenderPassBeginInfo_Ann * ann_VkDeviceGroupRenderPassBeginInfo = nullptr;
void VkDeviceGroupRenderPassBeginInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDeviceGroupRenderPassBeginInfo, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(deviceMask)>("deviceMask", "deviceMask");
    addField<DAS_BIND_MANAGED_FIELD(deviceRenderAreaCount)>("deviceRenderAreaCount", "deviceRenderAreaCount");
    addFieldEx("pDeviceRenderAreas", "pDeviceRenderAreas", offsetof(VkDeviceGroupRenderPassBeginInfo, pDeviceRenderAreas), makeType<VkRect2D *>(*mlib));
}
#endif

#if defined(VK_VERSION_1_1)
struct VkDeviceGroupCommandBufferBeginInfo_Ann : ManagedStructureAnnotation<VkDeviceGroupCommandBufferBeginInfo> {
    VkDeviceGroupCommandBufferBeginInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDeviceGroupCommandBufferBeginInfo", ml, "VkDeviceGroupCommandBufferBeginInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDeviceGroupCommandBufferBeginInfo_Ann * ann_VkDeviceGroupCommandBufferBeginInfo = nullptr;
void VkDeviceGroupCommandBufferBeginInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDeviceGroupCommandBufferBeginInfo, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(deviceMask)>("deviceMask", "deviceMask");
}
#endif

#if defined(VK_VERSION_1_1)
struct VkDeviceGroupSubmitInfo_Ann : ManagedStructureAnnotation<VkDeviceGroupSubmitInfo> {
    VkDeviceGroupSubmitInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDeviceGroupSubmitInfo", ml, "VkDeviceGroupSubmitInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDeviceGroupSubmitInfo_Ann * ann_VkDeviceGroupSubmitInfo = nullptr;
void VkDeviceGroupSubmitInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDeviceGroupSubmitInfo, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(waitSemaphoreCount)>("waitSemaphoreCount", "waitSemaphoreCount");
    addFieldEx("pWaitSemaphoreDeviceIndices", "pWaitSemaphoreDeviceIndices", offsetof(VkDeviceGroupSubmitInfo, pWaitSemaphoreDeviceIndices), makeType<uint32_t *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(commandBufferCount)>("commandBufferCount", "commandBufferCount");
    addFieldEx("pCommandBufferDeviceMasks", "pCommandBufferDeviceMasks", offsetof(VkDeviceGroupSubmitInfo, pCommandBufferDeviceMasks), makeType<uint32_t *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(signalSemaphoreCount)>("signalSemaphoreCount", "signalSemaphoreCount");
    addFieldEx("pSignalSemaphoreDeviceIndices", "pSignalSemaphoreDeviceIndices", offsetof(VkDeviceGroupSubmitInfo, pSignalSemaphoreDeviceIndices), makeType<uint32_t *>(*mlib));
}
#endif

#if defined(VK_VERSION_1_1)
struct VkDeviceGroupBindSparseInfo_Ann : ManagedStructureAnnotation<VkDeviceGroupBindSparseInfo> {
    VkDeviceGroupBindSparseInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDeviceGroupBindSparseInfo", ml, "VkDeviceGroupBindSparseInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDeviceGroupBindSparseInfo_Ann * ann_VkDeviceGroupBindSparseInfo = nullptr;
void VkDeviceGroupBindSparseInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDeviceGroupBindSparseInfo, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(resourceDeviceIndex)>("resourceDeviceIndex", "resourceDeviceIndex");
    addField<DAS_BIND_MANAGED_FIELD(memoryDeviceIndex)>("memoryDeviceIndex", "memoryDeviceIndex");
}
#endif

#if defined(VK_KHR_swapchain)
struct VkDeviceGroupPresentCapabilitiesKHR_Ann : ManagedStructureAnnotation<VkDeviceGroupPresentCapabilitiesKHR> {
    VkDeviceGroupPresentCapabilitiesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDeviceGroupPresentCapabilitiesKHR", ml, "VkDeviceGroupPresentCapabilitiesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDeviceGroupPresentCapabilitiesKHR_Ann * ann_VkDeviceGroupPresentCapabilitiesKHR = nullptr;
void VkDeviceGroupPresentCapabilitiesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDeviceGroupPresentCapabilitiesKHR, pNext), makeType<void *>(*mlib));
    addFieldEx("presentMask", "presentMask", offsetof(VkDeviceGroupPresentCapabilitiesKHR, presentMask), makeFixedArrayTypeDecl(int32_t(VK_MAX_DEVICE_GROUP_SIZE), makeType<uint32_t>(*mlib)));
    addFieldEx("modes", "modes", offsetof(VkDeviceGroupPresentCapabilitiesKHR, modes), makeVkFlags_VkDeviceGroupPresentModeFlagsKHR());
}
#endif

#if defined(VK_KHR_swapchain)
struct VkImageSwapchainCreateInfoKHR_Ann : ManagedStructureAnnotation<VkImageSwapchainCreateInfoKHR> {
    VkImageSwapchainCreateInfoKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkImageSwapchainCreateInfoKHR", ml, "VkImageSwapchainCreateInfoKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkImageSwapchainCreateInfoKHR_Ann * ann_VkImageSwapchainCreateInfoKHR = nullptr;
void VkImageSwapchainCreateInfoKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkImageSwapchainCreateInfoKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(swapchain)>("swapchain", "swapchain");
}
#endif

#if defined(VK_KHR_swapchain)
struct VkBindImageMemorySwapchainInfoKHR_Ann : ManagedStructureAnnotation<VkBindImageMemorySwapchainInfoKHR> {
    VkBindImageMemorySwapchainInfoKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkBindImageMemorySwapchainInfoKHR", ml, "VkBindImageMemorySwapchainInfoKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkBindImageMemorySwapchainInfoKHR_Ann * ann_VkBindImageMemorySwapchainInfoKHR = nullptr;
void VkBindImageMemorySwapchainInfoKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkBindImageMemorySwapchainInfoKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(swapchain)>("swapchain", "swapchain");
    addField<DAS_BIND_MANAGED_FIELD(imageIndex)>("imageIndex", "imageIndex");
}
#endif

#if defined(VK_KHR_swapchain)
struct VkAcquireNextImageInfoKHR_Ann : ManagedStructureAnnotation<VkAcquireNextImageInfoKHR> {
    VkAcquireNextImageInfoKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkAcquireNextImageInfoKHR", ml, "VkAcquireNextImageInfoKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkAcquireNextImageInfoKHR_Ann * ann_VkAcquireNextImageInfoKHR = nullptr;
void VkAcquireNextImageInfoKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkAcquireNextImageInfoKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(swapchain)>("swapchain", "swapchain");
    addField<DAS_BIND_MANAGED_FIELD(timeout)>("timeout", "timeout");
    addField<DAS_BIND_MANAGED_FIELD(semaphore)>("semaphore", "semaphore");
    addField<DAS_BIND_MANAGED_FIELD(fence)>("fence", "fence");
    addField<DAS_BIND_MANAGED_FIELD(deviceMask)>("deviceMask", "deviceMask");
}
#endif

#if defined(VK_KHR_swapchain)
struct VkDeviceGroupPresentInfoKHR_Ann : ManagedStructureAnnotation<VkDeviceGroupPresentInfoKHR> {
    VkDeviceGroupPresentInfoKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDeviceGroupPresentInfoKHR", ml, "VkDeviceGroupPresentInfoKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDeviceGroupPresentInfoKHR_Ann * ann_VkDeviceGroupPresentInfoKHR = nullptr;
void VkDeviceGroupPresentInfoKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDeviceGroupPresentInfoKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(swapchainCount)>("swapchainCount", "swapchainCount");
    addFieldEx("pDeviceMasks", "pDeviceMasks", offsetof(VkDeviceGroupPresentInfoKHR, pDeviceMasks), makeType<uint32_t *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(mode)>("mode", "mode");
}
#endif

#if defined(VK_VERSION_1_1)
struct VkDeviceGroupDeviceCreateInfo_Ann : ManagedStructureAnnotation<VkDeviceGroupDeviceCreateInfo> {
    VkDeviceGroupDeviceCreateInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDeviceGroupDeviceCreateInfo", ml, "VkDeviceGroupDeviceCreateInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDeviceGroupDeviceCreateInfo_Ann * ann_VkDeviceGroupDeviceCreateInfo = nullptr;
void VkDeviceGroupDeviceCreateInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDeviceGroupDeviceCreateInfo, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(physicalDeviceCount)>("physicalDeviceCount", "physicalDeviceCount");
    addFieldEx("pPhysicalDevices", "pPhysicalDevices", offsetof(VkDeviceGroupDeviceCreateInfo, pPhysicalDevices), makeType<VkPhysicalDevice *>(*mlib));
}
#endif

#if defined(VK_KHR_swapchain)
struct VkDeviceGroupSwapchainCreateInfoKHR_Ann : ManagedStructureAnnotation<VkDeviceGroupSwapchainCreateInfoKHR> {
    VkDeviceGroupSwapchainCreateInfoKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDeviceGroupSwapchainCreateInfoKHR", ml, "VkDeviceGroupSwapchainCreateInfoKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDeviceGroupSwapchainCreateInfoKHR_Ann * ann_VkDeviceGroupSwapchainCreateInfoKHR = nullptr;
void VkDeviceGroupSwapchainCreateInfoKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDeviceGroupSwapchainCreateInfoKHR, pNext), makeType<void *>(*mlib));
    addFieldEx("modes", "modes", offsetof(VkDeviceGroupSwapchainCreateInfoKHR, modes), makeVkFlags_VkDeviceGroupPresentModeFlagsKHR());
}
#endif

#if defined(VK_VERSION_1_1)
struct VkDescriptorUpdateTemplateEntry_Ann : ManagedStructureAnnotation<VkDescriptorUpdateTemplateEntry> {
    VkDescriptorUpdateTemplateEntry_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDescriptorUpdateTemplateEntry", ml, "VkDescriptorUpdateTemplateEntry") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDescriptorUpdateTemplateEntry_Ann * ann_VkDescriptorUpdateTemplateEntry = nullptr;
void VkDescriptorUpdateTemplateEntry_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(dstBinding)>("dstBinding", "dstBinding");
    addField<DAS_BIND_MANAGED_FIELD(dstArrayElement)>("dstArrayElement", "dstArrayElement");
    addField<DAS_BIND_MANAGED_FIELD(descriptorCount)>("descriptorCount", "descriptorCount");
    addField<DAS_BIND_MANAGED_FIELD(descriptorType)>("descriptorType", "descriptorType");
    addFieldEx("offset", "offset", offsetof(VkDescriptorUpdateTemplateEntry, offset), makeType<uint64_t>(*mlib));
    addFieldEx("stride", "stride", offsetof(VkDescriptorUpdateTemplateEntry, stride), makeType<uint64_t>(*mlib));
}
#endif

#if defined(VK_VERSION_1_1)
struct VkDescriptorUpdateTemplateCreateInfo_Ann : ManagedStructureAnnotation<VkDescriptorUpdateTemplateCreateInfo> {
    VkDescriptorUpdateTemplateCreateInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDescriptorUpdateTemplateCreateInfo", ml, "VkDescriptorUpdateTemplateCreateInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDescriptorUpdateTemplateCreateInfo_Ann * ann_VkDescriptorUpdateTemplateCreateInfo = nullptr;
void VkDescriptorUpdateTemplateCreateInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDescriptorUpdateTemplateCreateInfo, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkDescriptorUpdateTemplateCreateInfo, flags), makeVkFlags_VkDescriptorUpdateTemplateCreateFlags());
    addField<DAS_BIND_MANAGED_FIELD(descriptorUpdateEntryCount)>("descriptorUpdateEntryCount", "descriptorUpdateEntryCount");
    addFieldEx("pDescriptorUpdateEntries", "pDescriptorUpdateEntries", offsetof(VkDescriptorUpdateTemplateCreateInfo, pDescriptorUpdateEntries), makeType<VkDescriptorUpdateTemplateEntry *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(templateType)>("templateType", "templateType");
    addField<DAS_BIND_MANAGED_FIELD(descriptorSetLayout)>("descriptorSetLayout", "descriptorSetLayout");
    addField<DAS_BIND_MANAGED_FIELD(pipelineBindPoint)>("pipelineBindPoint", "pipelineBindPoint");
    addField<DAS_BIND_MANAGED_FIELD(pipelineLayout)>("pipelineLayout", "pipelineLayout");
    addField<DAS_BIND_MANAGED_FIELD(set)>("set", "set");
}
#endif

#if defined(VK_EXT_hdr_metadata)
struct VkXYColorEXT_Ann : ManagedStructureAnnotation<VkXYColorEXT> {
    VkXYColorEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkXYColorEXT", ml, "VkXYColorEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkXYColorEXT_Ann * ann_VkXYColorEXT = nullptr;
void VkXYColorEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(x)>("x", "x");
    addField<DAS_BIND_MANAGED_FIELD(y)>("y", "y");
}
#endif

#if defined(VK_KHR_present_id)
struct VkPhysicalDevicePresentIdFeaturesKHR_Ann : ManagedStructureAnnotation<VkPhysicalDevicePresentIdFeaturesKHR> {
    VkPhysicalDevicePresentIdFeaturesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDevicePresentIdFeaturesKHR", ml, "VkPhysicalDevicePresentIdFeaturesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDevicePresentIdFeaturesKHR_Ann * ann_VkPhysicalDevicePresentIdFeaturesKHR = nullptr;
void VkPhysicalDevicePresentIdFeaturesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDevicePresentIdFeaturesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(presentId)>("presentId", "presentId");
}
#endif

#if defined(VK_KHR_present_id)
struct VkPresentIdKHR_Ann : ManagedStructureAnnotation<VkPresentIdKHR> {
    VkPresentIdKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPresentIdKHR", ml, "VkPresentIdKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPresentIdKHR_Ann * ann_VkPresentIdKHR = nullptr;
void VkPresentIdKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPresentIdKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(swapchainCount)>("swapchainCount", "swapchainCount");
    addFieldEx("pPresentIds", "pPresentIds", offsetof(VkPresentIdKHR, pPresentIds), makeType<uint64_t *>(*mlib));
}
#endif

#if defined(VK_KHR_present_id2)
struct VkPhysicalDevicePresentId2FeaturesKHR_Ann : ManagedStructureAnnotation<VkPhysicalDevicePresentId2FeaturesKHR> {
    VkPhysicalDevicePresentId2FeaturesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDevicePresentId2FeaturesKHR", ml, "VkPhysicalDevicePresentId2FeaturesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDevicePresentId2FeaturesKHR_Ann * ann_VkPhysicalDevicePresentId2FeaturesKHR = nullptr;
void VkPhysicalDevicePresentId2FeaturesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDevicePresentId2FeaturesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(presentId2)>("presentId2", "presentId2");
}
#endif

#if defined(VK_KHR_present_id2)
struct VkPresentId2KHR_Ann : ManagedStructureAnnotation<VkPresentId2KHR> {
    VkPresentId2KHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPresentId2KHR", ml, "VkPresentId2KHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPresentId2KHR_Ann * ann_VkPresentId2KHR = nullptr;
void VkPresentId2KHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPresentId2KHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(swapchainCount)>("swapchainCount", "swapchainCount");
    addFieldEx("pPresentIds", "pPresentIds", offsetof(VkPresentId2KHR, pPresentIds), makeType<uint64_t *>(*mlib));
}
#endif

#if defined(VK_KHR_present_wait2)
struct VkPresentWait2InfoKHR_Ann : ManagedStructureAnnotation<VkPresentWait2InfoKHR> {
    VkPresentWait2InfoKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPresentWait2InfoKHR", ml, "VkPresentWait2InfoKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPresentWait2InfoKHR_Ann * ann_VkPresentWait2InfoKHR = nullptr;
void VkPresentWait2InfoKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPresentWait2InfoKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(presentId)>("presentId", "presentId");
    addField<DAS_BIND_MANAGED_FIELD(timeout)>("timeout", "timeout");
}
#endif

#if defined(VK_KHR_present_wait)
struct VkPhysicalDevicePresentWaitFeaturesKHR_Ann : ManagedStructureAnnotation<VkPhysicalDevicePresentWaitFeaturesKHR> {
    VkPhysicalDevicePresentWaitFeaturesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDevicePresentWaitFeaturesKHR", ml, "VkPhysicalDevicePresentWaitFeaturesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDevicePresentWaitFeaturesKHR_Ann * ann_VkPhysicalDevicePresentWaitFeaturesKHR = nullptr;
void VkPhysicalDevicePresentWaitFeaturesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDevicePresentWaitFeaturesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(presentWait)>("presentWait", "presentWait");
}
#endif

#if defined(VK_KHR_present_wait2)
struct VkPhysicalDevicePresentWait2FeaturesKHR_Ann : ManagedStructureAnnotation<VkPhysicalDevicePresentWait2FeaturesKHR> {
    VkPhysicalDevicePresentWait2FeaturesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDevicePresentWait2FeaturesKHR", ml, "VkPhysicalDevicePresentWait2FeaturesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDevicePresentWait2FeaturesKHR_Ann * ann_VkPhysicalDevicePresentWait2FeaturesKHR = nullptr;
void VkPhysicalDevicePresentWait2FeaturesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDevicePresentWait2FeaturesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(presentWait2)>("presentWait2", "presentWait2");
}
#endif

#if defined(VK_EXT_present_timing)
struct VkPhysicalDevicePresentTimingFeaturesEXT_Ann : ManagedStructureAnnotation<VkPhysicalDevicePresentTimingFeaturesEXT> {
    VkPhysicalDevicePresentTimingFeaturesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDevicePresentTimingFeaturesEXT", ml, "VkPhysicalDevicePresentTimingFeaturesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDevicePresentTimingFeaturesEXT_Ann * ann_VkPhysicalDevicePresentTimingFeaturesEXT = nullptr;
void VkPhysicalDevicePresentTimingFeaturesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDevicePresentTimingFeaturesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(presentTiming)>("presentTiming", "presentTiming");
    addField<DAS_BIND_MANAGED_FIELD(presentAtAbsoluteTime)>("presentAtAbsoluteTime", "presentAtAbsoluteTime");
    addField<DAS_BIND_MANAGED_FIELD(presentAtRelativeTime)>("presentAtRelativeTime", "presentAtRelativeTime");
}
#endif

#if defined(VK_EXT_present_timing)
struct VkPresentTimingSurfaceCapabilitiesEXT_Ann : ManagedStructureAnnotation<VkPresentTimingSurfaceCapabilitiesEXT> {
    VkPresentTimingSurfaceCapabilitiesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPresentTimingSurfaceCapabilitiesEXT", ml, "VkPresentTimingSurfaceCapabilitiesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPresentTimingSurfaceCapabilitiesEXT_Ann * ann_VkPresentTimingSurfaceCapabilitiesEXT = nullptr;
void VkPresentTimingSurfaceCapabilitiesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPresentTimingSurfaceCapabilitiesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(presentTimingSupported)>("presentTimingSupported", "presentTimingSupported");
    addField<DAS_BIND_MANAGED_FIELD(presentAtAbsoluteTimeSupported)>("presentAtAbsoluteTimeSupported", "presentAtAbsoluteTimeSupported");
    addField<DAS_BIND_MANAGED_FIELD(presentAtRelativeTimeSupported)>("presentAtRelativeTimeSupported", "presentAtRelativeTimeSupported");
    addFieldEx("presentStageQueries", "presentStageQueries", offsetof(VkPresentTimingSurfaceCapabilitiesEXT, presentStageQueries), makeVkFlags_VkPresentStageFlagsEXT());
}
#endif

#if defined(VK_EXT_present_timing)
struct VkSwapchainTimingPropertiesEXT_Ann : ManagedStructureAnnotation<VkSwapchainTimingPropertiesEXT> {
    VkSwapchainTimingPropertiesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkSwapchainTimingPropertiesEXT", ml, "VkSwapchainTimingPropertiesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkSwapchainTimingPropertiesEXT_Ann * ann_VkSwapchainTimingPropertiesEXT = nullptr;
void VkSwapchainTimingPropertiesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkSwapchainTimingPropertiesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(refreshDuration)>("refreshDuration", "refreshDuration");
    addField<DAS_BIND_MANAGED_FIELD(refreshInterval)>("refreshInterval", "refreshInterval");
}
#endif

#if defined(VK_EXT_present_timing)
struct VkSwapchainTimeDomainPropertiesEXT_Ann : ManagedStructureAnnotation<VkSwapchainTimeDomainPropertiesEXT> {
    VkSwapchainTimeDomainPropertiesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkSwapchainTimeDomainPropertiesEXT", ml, "VkSwapchainTimeDomainPropertiesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkSwapchainTimeDomainPropertiesEXT_Ann * ann_VkSwapchainTimeDomainPropertiesEXT = nullptr;
void VkSwapchainTimeDomainPropertiesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkSwapchainTimeDomainPropertiesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(timeDomainCount)>("timeDomainCount", "timeDomainCount");
    addFieldEx("pTimeDomains", "pTimeDomains", offsetof(VkSwapchainTimeDomainPropertiesEXT, pTimeDomains), makeType<VkTimeDomainKHR *>(*mlib));
    addFieldEx("pTimeDomainIds", "pTimeDomainIds", offsetof(VkSwapchainTimeDomainPropertiesEXT, pTimeDomainIds), makeType<uint64_t *>(*mlib));
}
#endif

#if defined(VK_EXT_present_timing)
struct VkPresentStageTimeEXT_Ann : ManagedStructureAnnotation<VkPresentStageTimeEXT> {
    VkPresentStageTimeEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPresentStageTimeEXT", ml, "VkPresentStageTimeEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPresentStageTimeEXT_Ann * ann_VkPresentStageTimeEXT = nullptr;
void VkPresentStageTimeEXT_Ann::init() {
    addFieldEx("stage", "stage", offsetof(VkPresentStageTimeEXT, stage), makeVkFlags_VkPresentStageFlagsEXT());
    addField<DAS_BIND_MANAGED_FIELD(time)>("time", "time");
}
#endif

#if defined(VK_EXT_present_timing)
struct VkPastPresentationTimingInfoEXT_Ann : ManagedStructureAnnotation<VkPastPresentationTimingInfoEXT> {
    VkPastPresentationTimingInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPastPresentationTimingInfoEXT", ml, "VkPastPresentationTimingInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPastPresentationTimingInfoEXT_Ann * ann_VkPastPresentationTimingInfoEXT = nullptr;
void VkPastPresentationTimingInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPastPresentationTimingInfoEXT, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkPastPresentationTimingInfoEXT, flags), makeVkFlags_VkPastPresentationTimingFlagsEXT());
    addField<DAS_BIND_MANAGED_FIELD(swapchain)>("swapchain", "swapchain");
}
#endif

#if defined(VK_EXT_present_timing)
struct VkPastPresentationTimingPropertiesEXT_Ann : ManagedStructureAnnotation<VkPastPresentationTimingPropertiesEXT> {
    VkPastPresentationTimingPropertiesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPastPresentationTimingPropertiesEXT", ml, "VkPastPresentationTimingPropertiesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPastPresentationTimingPropertiesEXT_Ann * ann_VkPastPresentationTimingPropertiesEXT = nullptr;
void VkPastPresentationTimingPropertiesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPastPresentationTimingPropertiesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(timingPropertiesCounter)>("timingPropertiesCounter", "timingPropertiesCounter");
    addField<DAS_BIND_MANAGED_FIELD(timeDomainsCounter)>("timeDomainsCounter", "timeDomainsCounter");
    addField<DAS_BIND_MANAGED_FIELD(presentationTimingCount)>("presentationTimingCount", "presentationTimingCount");
    addFieldEx("pPresentationTimings", "pPresentationTimings", offsetof(VkPastPresentationTimingPropertiesEXT, pPresentationTimings), makeType<VkPastPresentationTimingEXT *>(*mlib));
}
#endif

#if defined(VK_EXT_present_timing)
struct VkPastPresentationTimingEXT_Ann : ManagedStructureAnnotation<VkPastPresentationTimingEXT> {
    VkPastPresentationTimingEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPastPresentationTimingEXT", ml, "VkPastPresentationTimingEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPastPresentationTimingEXT_Ann * ann_VkPastPresentationTimingEXT = nullptr;
void VkPastPresentationTimingEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPastPresentationTimingEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(presentId)>("presentId", "presentId");
    addField<DAS_BIND_MANAGED_FIELD(targetTime)>("targetTime", "targetTime");
    addField<DAS_BIND_MANAGED_FIELD(presentStageCount)>("presentStageCount", "presentStageCount");
    addFieldEx("pPresentStages", "pPresentStages", offsetof(VkPastPresentationTimingEXT, pPresentStages), makeType<VkPresentStageTimeEXT *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(timeDomain)>("timeDomain", "timeDomain");
    addField<DAS_BIND_MANAGED_FIELD(timeDomainId)>("timeDomainId", "timeDomainId");
    addField<DAS_BIND_MANAGED_FIELD(reportComplete)>("reportComplete", "reportComplete");
}
#endif

#if defined(VK_EXT_present_timing)
struct VkPresentTimingsInfoEXT_Ann : ManagedStructureAnnotation<VkPresentTimingsInfoEXT> {
    VkPresentTimingsInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPresentTimingsInfoEXT", ml, "VkPresentTimingsInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPresentTimingsInfoEXT_Ann * ann_VkPresentTimingsInfoEXT = nullptr;
void VkPresentTimingsInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPresentTimingsInfoEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(swapchainCount)>("swapchainCount", "swapchainCount");
    addFieldEx("pTimingInfos", "pTimingInfos", offsetof(VkPresentTimingsInfoEXT, pTimingInfos), makeType<VkPresentTimingInfoEXT *>(*mlib));
}
#endif

#if defined(VK_EXT_present_timing)
struct VkPresentTimingInfoEXT_Ann : ManagedStructureAnnotation<VkPresentTimingInfoEXT> {
    VkPresentTimingInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPresentTimingInfoEXT", ml, "VkPresentTimingInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPresentTimingInfoEXT_Ann * ann_VkPresentTimingInfoEXT = nullptr;
void VkPresentTimingInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPresentTimingInfoEXT, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkPresentTimingInfoEXT, flags), makeVkFlags_VkPresentTimingInfoFlagsEXT());
    addField<DAS_BIND_MANAGED_FIELD(targetTime)>("targetTime", "targetTime");
    addField<DAS_BIND_MANAGED_FIELD(timeDomainId)>("timeDomainId", "timeDomainId");
    addFieldEx("presentStageQueries", "presentStageQueries", offsetof(VkPresentTimingInfoEXT, presentStageQueries), makeVkFlags_VkPresentStageFlagsEXT());
    addFieldEx("targetTimeDomainPresentStage", "targetTimeDomainPresentStage", offsetof(VkPresentTimingInfoEXT, targetTimeDomainPresentStage), makeVkFlags_VkPresentStageFlagsEXT());
}
#endif

#if defined(VK_EXT_present_timing)
struct VkSwapchainCalibratedTimestampInfoEXT_Ann : ManagedStructureAnnotation<VkSwapchainCalibratedTimestampInfoEXT> {
    VkSwapchainCalibratedTimestampInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkSwapchainCalibratedTimestampInfoEXT", ml, "VkSwapchainCalibratedTimestampInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkSwapchainCalibratedTimestampInfoEXT_Ann * ann_VkSwapchainCalibratedTimestampInfoEXT = nullptr;
void VkSwapchainCalibratedTimestampInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkSwapchainCalibratedTimestampInfoEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(swapchain)>("swapchain", "swapchain");
    addFieldEx("presentStage", "presentStage", offsetof(VkSwapchainCalibratedTimestampInfoEXT, presentStage), makeVkFlags_VkPresentStageFlagsEXT());
    addField<DAS_BIND_MANAGED_FIELD(timeDomainId)>("timeDomainId", "timeDomainId");
}
#endif

#if defined(VK_EXT_hdr_metadata)
struct VkHdrMetadataEXT_Ann : ManagedStructureAnnotation<VkHdrMetadataEXT> {
    VkHdrMetadataEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkHdrMetadataEXT", ml, "VkHdrMetadataEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkHdrMetadataEXT_Ann * ann_VkHdrMetadataEXT = nullptr;
void VkHdrMetadataEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkHdrMetadataEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(displayPrimaryRed)>("displayPrimaryRed", "displayPrimaryRed");
    addField<DAS_BIND_MANAGED_FIELD(displayPrimaryGreen)>("displayPrimaryGreen", "displayPrimaryGreen");
    addField<DAS_BIND_MANAGED_FIELD(displayPrimaryBlue)>("displayPrimaryBlue", "displayPrimaryBlue");
    addField<DAS_BIND_MANAGED_FIELD(whitePoint)>("whitePoint", "whitePoint");
    addField<DAS_BIND_MANAGED_FIELD(maxLuminance)>("maxLuminance", "maxLuminance");
    addField<DAS_BIND_MANAGED_FIELD(minLuminance)>("minLuminance", "minLuminance");
    addField<DAS_BIND_MANAGED_FIELD(maxContentLightLevel)>("maxContentLightLevel", "maxContentLightLevel");
    addField<DAS_BIND_MANAGED_FIELD(maxFrameAverageLightLevel)>("maxFrameAverageLightLevel", "maxFrameAverageLightLevel");
}
#endif

void das_vulkan_add_structs_5(Module & mod, ModuleLibrary & lib) {
#if defined(VK_KHR_external_fence_win32) && defined(VK_USE_PLATFORM_WIN32_KHR)
    ann_VkFenceGetWin32HandleInfoKHR = new VkFenceGetWin32HandleInfoKHR_Ann(lib); mod.addAnnotation(ann_VkFenceGetWin32HandleInfoKHR);
#endif
#if defined(VK_KHR_external_fence_fd)
    ann_VkImportFenceFdInfoKHR = new VkImportFenceFdInfoKHR_Ann(lib); mod.addAnnotation(ann_VkImportFenceFdInfoKHR);
#endif
#if defined(VK_KHR_external_fence_fd)
    ann_VkFenceGetFdInfoKHR = new VkFenceGetFdInfoKHR_Ann(lib); mod.addAnnotation(ann_VkFenceGetFdInfoKHR);
#endif
#if defined(VK_VERSION_1_1)
    ann_VkPhysicalDeviceMultiviewFeatures = new VkPhysicalDeviceMultiviewFeatures_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceMultiviewFeatures);
#endif
#if defined(VK_VERSION_1_1)
    ann_VkPhysicalDeviceMultiviewProperties = new VkPhysicalDeviceMultiviewProperties_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceMultiviewProperties);
#endif
#if defined(VK_VERSION_1_1)
    ann_VkRenderPassMultiviewCreateInfo = new VkRenderPassMultiviewCreateInfo_Ann(lib); mod.addAnnotation(ann_VkRenderPassMultiviewCreateInfo);
#endif
#if defined(VK_EXT_display_surface_counter)
    ann_VkSurfaceCapabilities2EXT = new VkSurfaceCapabilities2EXT_Ann(lib); mod.addAnnotation(ann_VkSurfaceCapabilities2EXT);
#endif
#if defined(VK_EXT_display_control)
    ann_VkDisplayPowerInfoEXT = new VkDisplayPowerInfoEXT_Ann(lib); mod.addAnnotation(ann_VkDisplayPowerInfoEXT);
#endif
#if defined(VK_EXT_display_control)
    ann_VkDeviceEventInfoEXT = new VkDeviceEventInfoEXT_Ann(lib); mod.addAnnotation(ann_VkDeviceEventInfoEXT);
#endif
#if defined(VK_EXT_display_control)
    ann_VkDisplayEventInfoEXT = new VkDisplayEventInfoEXT_Ann(lib); mod.addAnnotation(ann_VkDisplayEventInfoEXT);
#endif
#if defined(VK_EXT_display_control)
    ann_VkSwapchainCounterCreateInfoEXT = new VkSwapchainCounterCreateInfoEXT_Ann(lib); mod.addAnnotation(ann_VkSwapchainCounterCreateInfoEXT);
#endif
#if defined(VK_VERSION_1_1)
    ann_VkPhysicalDeviceGroupProperties = new VkPhysicalDeviceGroupProperties_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceGroupProperties);
#endif
#if defined(VK_VERSION_1_1)
    ann_VkMemoryAllocateFlagsInfo = new VkMemoryAllocateFlagsInfo_Ann(lib); mod.addAnnotation(ann_VkMemoryAllocateFlagsInfo);
#endif
#if defined(VK_VERSION_1_1)
    ann_VkBindBufferMemoryInfo = new VkBindBufferMemoryInfo_Ann(lib); mod.addAnnotation(ann_VkBindBufferMemoryInfo);
#endif
#if defined(VK_VERSION_1_1)
    ann_VkBindBufferMemoryDeviceGroupInfo = new VkBindBufferMemoryDeviceGroupInfo_Ann(lib); mod.addAnnotation(ann_VkBindBufferMemoryDeviceGroupInfo);
#endif
#if defined(VK_VERSION_1_1)
    ann_VkBindImageMemoryInfo = new VkBindImageMemoryInfo_Ann(lib); mod.addAnnotation(ann_VkBindImageMemoryInfo);
#endif
#if defined(VK_VERSION_1_1)
    ann_VkBindImageMemoryDeviceGroupInfo = new VkBindImageMemoryDeviceGroupInfo_Ann(lib); mod.addAnnotation(ann_VkBindImageMemoryDeviceGroupInfo);
#endif
#if defined(VK_VERSION_1_1)
    ann_VkDeviceGroupRenderPassBeginInfo = new VkDeviceGroupRenderPassBeginInfo_Ann(lib); mod.addAnnotation(ann_VkDeviceGroupRenderPassBeginInfo);
#endif
#if defined(VK_VERSION_1_1)
    ann_VkDeviceGroupCommandBufferBeginInfo = new VkDeviceGroupCommandBufferBeginInfo_Ann(lib); mod.addAnnotation(ann_VkDeviceGroupCommandBufferBeginInfo);
#endif
#if defined(VK_VERSION_1_1)
    ann_VkDeviceGroupSubmitInfo = new VkDeviceGroupSubmitInfo_Ann(lib); mod.addAnnotation(ann_VkDeviceGroupSubmitInfo);
#endif
#if defined(VK_VERSION_1_1)
    ann_VkDeviceGroupBindSparseInfo = new VkDeviceGroupBindSparseInfo_Ann(lib); mod.addAnnotation(ann_VkDeviceGroupBindSparseInfo);
#endif
#if defined(VK_KHR_swapchain)
    ann_VkDeviceGroupPresentCapabilitiesKHR = new VkDeviceGroupPresentCapabilitiesKHR_Ann(lib); mod.addAnnotation(ann_VkDeviceGroupPresentCapabilitiesKHR);
#endif
#if defined(VK_KHR_swapchain)
    ann_VkImageSwapchainCreateInfoKHR = new VkImageSwapchainCreateInfoKHR_Ann(lib); mod.addAnnotation(ann_VkImageSwapchainCreateInfoKHR);
#endif
#if defined(VK_KHR_swapchain)
    ann_VkBindImageMemorySwapchainInfoKHR = new VkBindImageMemorySwapchainInfoKHR_Ann(lib); mod.addAnnotation(ann_VkBindImageMemorySwapchainInfoKHR);
#endif
#if defined(VK_KHR_swapchain)
    ann_VkAcquireNextImageInfoKHR = new VkAcquireNextImageInfoKHR_Ann(lib); mod.addAnnotation(ann_VkAcquireNextImageInfoKHR);
#endif
#if defined(VK_KHR_swapchain)
    ann_VkDeviceGroupPresentInfoKHR = new VkDeviceGroupPresentInfoKHR_Ann(lib); mod.addAnnotation(ann_VkDeviceGroupPresentInfoKHR);
#endif
#if defined(VK_VERSION_1_1)
    ann_VkDeviceGroupDeviceCreateInfo = new VkDeviceGroupDeviceCreateInfo_Ann(lib); mod.addAnnotation(ann_VkDeviceGroupDeviceCreateInfo);
#endif
#if defined(VK_KHR_swapchain)
    ann_VkDeviceGroupSwapchainCreateInfoKHR = new VkDeviceGroupSwapchainCreateInfoKHR_Ann(lib); mod.addAnnotation(ann_VkDeviceGroupSwapchainCreateInfoKHR);
#endif
#if defined(VK_VERSION_1_1)
    ann_VkDescriptorUpdateTemplateEntry = new VkDescriptorUpdateTemplateEntry_Ann(lib); mod.addAnnotation(ann_VkDescriptorUpdateTemplateEntry);
#endif
#if defined(VK_VERSION_1_1)
    ann_VkDescriptorUpdateTemplateCreateInfo = new VkDescriptorUpdateTemplateCreateInfo_Ann(lib); mod.addAnnotation(ann_VkDescriptorUpdateTemplateCreateInfo);
#endif
#if defined(VK_EXT_hdr_metadata)
    ann_VkXYColorEXT = new VkXYColorEXT_Ann(lib); mod.addAnnotation(ann_VkXYColorEXT);
#endif
#if defined(VK_KHR_present_id)
    ann_VkPhysicalDevicePresentIdFeaturesKHR = new VkPhysicalDevicePresentIdFeaturesKHR_Ann(lib); mod.addAnnotation(ann_VkPhysicalDevicePresentIdFeaturesKHR);
#endif
#if defined(VK_KHR_present_id)
    ann_VkPresentIdKHR = new VkPresentIdKHR_Ann(lib); mod.addAnnotation(ann_VkPresentIdKHR);
#endif
#if defined(VK_KHR_present_id2)
    ann_VkPhysicalDevicePresentId2FeaturesKHR = new VkPhysicalDevicePresentId2FeaturesKHR_Ann(lib); mod.addAnnotation(ann_VkPhysicalDevicePresentId2FeaturesKHR);
#endif
#if defined(VK_KHR_present_id2)
    ann_VkPresentId2KHR = new VkPresentId2KHR_Ann(lib); mod.addAnnotation(ann_VkPresentId2KHR);
#endif
#if defined(VK_KHR_present_wait2)
    ann_VkPresentWait2InfoKHR = new VkPresentWait2InfoKHR_Ann(lib); mod.addAnnotation(ann_VkPresentWait2InfoKHR);
#endif
#if defined(VK_KHR_present_wait)
    ann_VkPhysicalDevicePresentWaitFeaturesKHR = new VkPhysicalDevicePresentWaitFeaturesKHR_Ann(lib); mod.addAnnotation(ann_VkPhysicalDevicePresentWaitFeaturesKHR);
#endif
#if defined(VK_KHR_present_wait2)
    ann_VkPhysicalDevicePresentWait2FeaturesKHR = new VkPhysicalDevicePresentWait2FeaturesKHR_Ann(lib); mod.addAnnotation(ann_VkPhysicalDevicePresentWait2FeaturesKHR);
#endif
#if defined(VK_EXT_present_timing)
    ann_VkPhysicalDevicePresentTimingFeaturesEXT = new VkPhysicalDevicePresentTimingFeaturesEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDevicePresentTimingFeaturesEXT);
#endif
#if defined(VK_EXT_present_timing)
    ann_VkPresentTimingSurfaceCapabilitiesEXT = new VkPresentTimingSurfaceCapabilitiesEXT_Ann(lib); mod.addAnnotation(ann_VkPresentTimingSurfaceCapabilitiesEXT);
#endif
#if defined(VK_EXT_present_timing)
    ann_VkSwapchainTimingPropertiesEXT = new VkSwapchainTimingPropertiesEXT_Ann(lib); mod.addAnnotation(ann_VkSwapchainTimingPropertiesEXT);
#endif
#if defined(VK_EXT_present_timing)
    ann_VkSwapchainTimeDomainPropertiesEXT = new VkSwapchainTimeDomainPropertiesEXT_Ann(lib); mod.addAnnotation(ann_VkSwapchainTimeDomainPropertiesEXT);
#endif
#if defined(VK_EXT_present_timing)
    ann_VkPresentStageTimeEXT = new VkPresentStageTimeEXT_Ann(lib); mod.addAnnotation(ann_VkPresentStageTimeEXT);
#endif
#if defined(VK_EXT_present_timing)
    ann_VkPastPresentationTimingInfoEXT = new VkPastPresentationTimingInfoEXT_Ann(lib); mod.addAnnotation(ann_VkPastPresentationTimingInfoEXT);
#endif
#if defined(VK_EXT_present_timing)
    ann_VkPastPresentationTimingPropertiesEXT = new VkPastPresentationTimingPropertiesEXT_Ann(lib); mod.addAnnotation(ann_VkPastPresentationTimingPropertiesEXT);
#endif
#if defined(VK_EXT_present_timing)
    ann_VkPastPresentationTimingEXT = new VkPastPresentationTimingEXT_Ann(lib); mod.addAnnotation(ann_VkPastPresentationTimingEXT);
#endif
#if defined(VK_EXT_present_timing)
    ann_VkPresentTimingsInfoEXT = new VkPresentTimingsInfoEXT_Ann(lib); mod.addAnnotation(ann_VkPresentTimingsInfoEXT);
#endif
#if defined(VK_EXT_present_timing)
    ann_VkPresentTimingInfoEXT = new VkPresentTimingInfoEXT_Ann(lib); mod.addAnnotation(ann_VkPresentTimingInfoEXT);
#endif
#if defined(VK_EXT_present_timing)
    ann_VkSwapchainCalibratedTimestampInfoEXT = new VkSwapchainCalibratedTimestampInfoEXT_Ann(lib); mod.addAnnotation(ann_VkSwapchainCalibratedTimestampInfoEXT);
#endif
#if defined(VK_EXT_hdr_metadata)
    ann_VkHdrMetadataEXT = new VkHdrMetadataEXT_Ann(lib); mod.addAnnotation(ann_VkHdrMetadataEXT);
#endif
}

void das_vulkan_fill_structs_5(Module & mod, ModuleLibrary & lib) {
#if defined(VK_KHR_external_fence_win32) && defined(VK_USE_PLATFORM_WIN32_KHR)
    ann_VkFenceGetWin32HandleInfoKHR->mlib = &lib; ann_VkFenceGetWin32HandleInfoKHR->init(); ann_VkFenceGetWin32HandleInfoKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_external_fence_fd)
    ann_VkImportFenceFdInfoKHR->mlib = &lib; ann_VkImportFenceFdInfoKHR->init(); ann_VkImportFenceFdInfoKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_external_fence_fd)
    ann_VkFenceGetFdInfoKHR->mlib = &lib; ann_VkFenceGetFdInfoKHR->init(); ann_VkFenceGetFdInfoKHR->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_1)
    ann_VkPhysicalDeviceMultiviewFeatures->mlib = &lib; ann_VkPhysicalDeviceMultiviewFeatures->init(); ann_VkPhysicalDeviceMultiviewFeatures->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_1)
    ann_VkPhysicalDeviceMultiviewProperties->mlib = &lib; ann_VkPhysicalDeviceMultiviewProperties->init(); ann_VkPhysicalDeviceMultiviewProperties->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_1)
    ann_VkRenderPassMultiviewCreateInfo->mlib = &lib; ann_VkRenderPassMultiviewCreateInfo->init(); ann_VkRenderPassMultiviewCreateInfo->mlib = nullptr;
#endif
#if defined(VK_EXT_display_surface_counter)
    ann_VkSurfaceCapabilities2EXT->mlib = &lib; ann_VkSurfaceCapabilities2EXT->init(); ann_VkSurfaceCapabilities2EXT->mlib = nullptr;
#endif
#if defined(VK_EXT_display_control)
    ann_VkDisplayPowerInfoEXT->mlib = &lib; ann_VkDisplayPowerInfoEXT->init(); ann_VkDisplayPowerInfoEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_display_control)
    ann_VkDeviceEventInfoEXT->mlib = &lib; ann_VkDeviceEventInfoEXT->init(); ann_VkDeviceEventInfoEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_display_control)
    ann_VkDisplayEventInfoEXT->mlib = &lib; ann_VkDisplayEventInfoEXT->init(); ann_VkDisplayEventInfoEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_display_control)
    ann_VkSwapchainCounterCreateInfoEXT->mlib = &lib; ann_VkSwapchainCounterCreateInfoEXT->init(); ann_VkSwapchainCounterCreateInfoEXT->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_1)
    ann_VkPhysicalDeviceGroupProperties->mlib = &lib; ann_VkPhysicalDeviceGroupProperties->init(); ann_VkPhysicalDeviceGroupProperties->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_1)
    ann_VkMemoryAllocateFlagsInfo->mlib = &lib; ann_VkMemoryAllocateFlagsInfo->init(); ann_VkMemoryAllocateFlagsInfo->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_1)
    ann_VkBindBufferMemoryInfo->mlib = &lib; ann_VkBindBufferMemoryInfo->init(); ann_VkBindBufferMemoryInfo->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_1)
    ann_VkBindBufferMemoryDeviceGroupInfo->mlib = &lib; ann_VkBindBufferMemoryDeviceGroupInfo->init(); ann_VkBindBufferMemoryDeviceGroupInfo->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_1)
    ann_VkBindImageMemoryInfo->mlib = &lib; ann_VkBindImageMemoryInfo->init(); ann_VkBindImageMemoryInfo->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_1)
    ann_VkBindImageMemoryDeviceGroupInfo->mlib = &lib; ann_VkBindImageMemoryDeviceGroupInfo->init(); ann_VkBindImageMemoryDeviceGroupInfo->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_1)
    ann_VkDeviceGroupRenderPassBeginInfo->mlib = &lib; ann_VkDeviceGroupRenderPassBeginInfo->init(); ann_VkDeviceGroupRenderPassBeginInfo->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_1)
    ann_VkDeviceGroupCommandBufferBeginInfo->mlib = &lib; ann_VkDeviceGroupCommandBufferBeginInfo->init(); ann_VkDeviceGroupCommandBufferBeginInfo->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_1)
    ann_VkDeviceGroupSubmitInfo->mlib = &lib; ann_VkDeviceGroupSubmitInfo->init(); ann_VkDeviceGroupSubmitInfo->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_1)
    ann_VkDeviceGroupBindSparseInfo->mlib = &lib; ann_VkDeviceGroupBindSparseInfo->init(); ann_VkDeviceGroupBindSparseInfo->mlib = nullptr;
#endif
#if defined(VK_KHR_swapchain)
    ann_VkDeviceGroupPresentCapabilitiesKHR->mlib = &lib; ann_VkDeviceGroupPresentCapabilitiesKHR->init(); ann_VkDeviceGroupPresentCapabilitiesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_swapchain)
    ann_VkImageSwapchainCreateInfoKHR->mlib = &lib; ann_VkImageSwapchainCreateInfoKHR->init(); ann_VkImageSwapchainCreateInfoKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_swapchain)
    ann_VkBindImageMemorySwapchainInfoKHR->mlib = &lib; ann_VkBindImageMemorySwapchainInfoKHR->init(); ann_VkBindImageMemorySwapchainInfoKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_swapchain)
    ann_VkAcquireNextImageInfoKHR->mlib = &lib; ann_VkAcquireNextImageInfoKHR->init(); ann_VkAcquireNextImageInfoKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_swapchain)
    ann_VkDeviceGroupPresentInfoKHR->mlib = &lib; ann_VkDeviceGroupPresentInfoKHR->init(); ann_VkDeviceGroupPresentInfoKHR->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_1)
    ann_VkDeviceGroupDeviceCreateInfo->mlib = &lib; ann_VkDeviceGroupDeviceCreateInfo->init(); ann_VkDeviceGroupDeviceCreateInfo->mlib = nullptr;
#endif
#if defined(VK_KHR_swapchain)
    ann_VkDeviceGroupSwapchainCreateInfoKHR->mlib = &lib; ann_VkDeviceGroupSwapchainCreateInfoKHR->init(); ann_VkDeviceGroupSwapchainCreateInfoKHR->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_1)
    ann_VkDescriptorUpdateTemplateEntry->mlib = &lib; ann_VkDescriptorUpdateTemplateEntry->init(); ann_VkDescriptorUpdateTemplateEntry->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_1)
    ann_VkDescriptorUpdateTemplateCreateInfo->mlib = &lib; ann_VkDescriptorUpdateTemplateCreateInfo->init(); ann_VkDescriptorUpdateTemplateCreateInfo->mlib = nullptr;
#endif
#if defined(VK_EXT_hdr_metadata)
    ann_VkXYColorEXT->mlib = &lib; ann_VkXYColorEXT->init(); ann_VkXYColorEXT->mlib = nullptr;
#endif
#if defined(VK_KHR_present_id)
    ann_VkPhysicalDevicePresentIdFeaturesKHR->mlib = &lib; ann_VkPhysicalDevicePresentIdFeaturesKHR->init(); ann_VkPhysicalDevicePresentIdFeaturesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_present_id)
    ann_VkPresentIdKHR->mlib = &lib; ann_VkPresentIdKHR->init(); ann_VkPresentIdKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_present_id2)
    ann_VkPhysicalDevicePresentId2FeaturesKHR->mlib = &lib; ann_VkPhysicalDevicePresentId2FeaturesKHR->init(); ann_VkPhysicalDevicePresentId2FeaturesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_present_id2)
    ann_VkPresentId2KHR->mlib = &lib; ann_VkPresentId2KHR->init(); ann_VkPresentId2KHR->mlib = nullptr;
#endif
#if defined(VK_KHR_present_wait2)
    ann_VkPresentWait2InfoKHR->mlib = &lib; ann_VkPresentWait2InfoKHR->init(); ann_VkPresentWait2InfoKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_present_wait)
    ann_VkPhysicalDevicePresentWaitFeaturesKHR->mlib = &lib; ann_VkPhysicalDevicePresentWaitFeaturesKHR->init(); ann_VkPhysicalDevicePresentWaitFeaturesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_present_wait2)
    ann_VkPhysicalDevicePresentWait2FeaturesKHR->mlib = &lib; ann_VkPhysicalDevicePresentWait2FeaturesKHR->init(); ann_VkPhysicalDevicePresentWait2FeaturesKHR->mlib = nullptr;
#endif
#if defined(VK_EXT_present_timing)
    ann_VkPhysicalDevicePresentTimingFeaturesEXT->mlib = &lib; ann_VkPhysicalDevicePresentTimingFeaturesEXT->init(); ann_VkPhysicalDevicePresentTimingFeaturesEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_present_timing)
    ann_VkPresentTimingSurfaceCapabilitiesEXT->mlib = &lib; ann_VkPresentTimingSurfaceCapabilitiesEXT->init(); ann_VkPresentTimingSurfaceCapabilitiesEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_present_timing)
    ann_VkSwapchainTimingPropertiesEXT->mlib = &lib; ann_VkSwapchainTimingPropertiesEXT->init(); ann_VkSwapchainTimingPropertiesEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_present_timing)
    ann_VkSwapchainTimeDomainPropertiesEXT->mlib = &lib; ann_VkSwapchainTimeDomainPropertiesEXT->init(); ann_VkSwapchainTimeDomainPropertiesEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_present_timing)
    ann_VkPresentStageTimeEXT->mlib = &lib; ann_VkPresentStageTimeEXT->init(); ann_VkPresentStageTimeEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_present_timing)
    ann_VkPastPresentationTimingInfoEXT->mlib = &lib; ann_VkPastPresentationTimingInfoEXT->init(); ann_VkPastPresentationTimingInfoEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_present_timing)
    ann_VkPastPresentationTimingPropertiesEXT->mlib = &lib; ann_VkPastPresentationTimingPropertiesEXT->init(); ann_VkPastPresentationTimingPropertiesEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_present_timing)
    ann_VkPastPresentationTimingEXT->mlib = &lib; ann_VkPastPresentationTimingEXT->init(); ann_VkPastPresentationTimingEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_present_timing)
    ann_VkPresentTimingsInfoEXT->mlib = &lib; ann_VkPresentTimingsInfoEXT->init(); ann_VkPresentTimingsInfoEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_present_timing)
    ann_VkPresentTimingInfoEXT->mlib = &lib; ann_VkPresentTimingInfoEXT->init(); ann_VkPresentTimingInfoEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_present_timing)
    ann_VkSwapchainCalibratedTimestampInfoEXT->mlib = &lib; ann_VkSwapchainCalibratedTimestampInfoEXT->init(); ann_VkSwapchainCalibratedTimestampInfoEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_hdr_metadata)
    ann_VkHdrMetadataEXT->mlib = &lib; ann_VkHdrMetadataEXT->init(); ann_VkHdrMetadataEXT->mlib = nullptr;
#endif
}

}
