// generated by generator/generate.das -- DO NOT EDIT

#include "dasVULKAN.h"

namespace das {

#if defined(VK_SEC_throttle_hint)
struct VkThrottleHintSubmitInfoSEC_Ann : ManagedStructureAnnotation<VkThrottleHintSubmitInfoSEC> {
    VkThrottleHintSubmitInfoSEC_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkThrottleHintSubmitInfoSEC", ml, "VkThrottleHintSubmitInfoSEC") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkThrottleHintSubmitInfoSEC_Ann * ann_VkThrottleHintSubmitInfoSEC = nullptr;
void VkThrottleHintSubmitInfoSEC_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkThrottleHintSubmitInfoSEC, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(throttleHint)>("throttleHint", "throttleHint");
}
#endif

#if defined(VK_ARM_tensors)
struct VkTensorDescriptionARM_Ann : ManagedStructureAnnotation<VkTensorDescriptionARM> {
    VkTensorDescriptionARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkTensorDescriptionARM", ml, "VkTensorDescriptionARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkTensorDescriptionARM_Ann * ann_VkTensorDescriptionARM = nullptr;
void VkTensorDescriptionARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkTensorDescriptionARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(tiling)>("tiling", "tiling");
    addField<DAS_BIND_MANAGED_FIELD(format)>("format", "format");
    addField<DAS_BIND_MANAGED_FIELD(dimensionCount)>("dimensionCount", "dimensionCount");
    addFieldEx("pDimensions", "pDimensions", offsetof(VkTensorDescriptionARM, pDimensions), makeType<int64_t *>(*mlib));
    addFieldEx("pStrides", "pStrides", offsetof(VkTensorDescriptionARM, pStrides), makeType<int64_t *>(*mlib));
    addFieldEx("usage", "usage", offsetof(VkTensorDescriptionARM, usage), makeVkFlags_VkTensorUsageFlagsARM());
}
#endif

#if defined(VK_ARM_tensors)
struct VkTensorCreateInfoARM_Ann : ManagedStructureAnnotation<VkTensorCreateInfoARM> {
    VkTensorCreateInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkTensorCreateInfoARM", ml, "VkTensorCreateInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkTensorCreateInfoARM_Ann * ann_VkTensorCreateInfoARM = nullptr;
void VkTensorCreateInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkTensorCreateInfoARM, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkTensorCreateInfoARM, flags), makeVkFlags_VkTensorCreateFlagsARM());
    addFieldEx("pDescription", "pDescription", offsetof(VkTensorCreateInfoARM, pDescription), makeType<VkTensorDescriptionARM *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(sharingMode)>("sharingMode", "sharingMode");
    addField<DAS_BIND_MANAGED_FIELD(queueFamilyIndexCount)>("queueFamilyIndexCount", "queueFamilyIndexCount");
    addFieldEx("pQueueFamilyIndices", "pQueueFamilyIndices", offsetof(VkTensorCreateInfoARM, pQueueFamilyIndices), makeType<uint32_t *>(*mlib));
}
#endif

#if defined(VK_EXT_descriptor_heap)
struct VkTensorViewCreateInfoARM_Ann : ManagedStructureAnnotation<VkTensorViewCreateInfoARM> {
    VkTensorViewCreateInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkTensorViewCreateInfoARM", ml, "VkTensorViewCreateInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkTensorViewCreateInfoARM_Ann * ann_VkTensorViewCreateInfoARM = nullptr;
void VkTensorViewCreateInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkTensorViewCreateInfoARM, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkTensorViewCreateInfoARM, flags), makeVkFlags_VkTensorViewCreateFlagsARM());
    addField<DAS_BIND_MANAGED_FIELD(tensor)>("tensor", "tensor");
    addField<DAS_BIND_MANAGED_FIELD(format)>("format", "format");
}
#endif

#if defined(VK_ARM_tensors)
struct VkTensorMemoryRequirementsInfoARM_Ann : ManagedStructureAnnotation<VkTensorMemoryRequirementsInfoARM> {
    VkTensorMemoryRequirementsInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkTensorMemoryRequirementsInfoARM", ml, "VkTensorMemoryRequirementsInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkTensorMemoryRequirementsInfoARM_Ann * ann_VkTensorMemoryRequirementsInfoARM = nullptr;
void VkTensorMemoryRequirementsInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkTensorMemoryRequirementsInfoARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(tensor)>("tensor", "tensor");
}
#endif

#if defined(VK_ARM_tensors)
struct VkBindTensorMemoryInfoARM_Ann : ManagedStructureAnnotation<VkBindTensorMemoryInfoARM> {
    VkBindTensorMemoryInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkBindTensorMemoryInfoARM", ml, "VkBindTensorMemoryInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkBindTensorMemoryInfoARM_Ann * ann_VkBindTensorMemoryInfoARM = nullptr;
void VkBindTensorMemoryInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkBindTensorMemoryInfoARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(tensor)>("tensor", "tensor");
    addField<DAS_BIND_MANAGED_FIELD(memory)>("memory", "memory");
    addField<DAS_BIND_MANAGED_FIELD(memoryOffset)>("memoryOffset", "memoryOffset");
}
#endif

#if defined(VK_ARM_tensors)
struct VkWriteDescriptorSetTensorARM_Ann : ManagedStructureAnnotation<VkWriteDescriptorSetTensorARM> {
    VkWriteDescriptorSetTensorARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkWriteDescriptorSetTensorARM", ml, "VkWriteDescriptorSetTensorARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkWriteDescriptorSetTensorARM_Ann * ann_VkWriteDescriptorSetTensorARM = nullptr;
void VkWriteDescriptorSetTensorARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkWriteDescriptorSetTensorARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(tensorViewCount)>("tensorViewCount", "tensorViewCount");
    addFieldEx("pTensorViews", "pTensorViews", offsetof(VkWriteDescriptorSetTensorARM, pTensorViews), makeType<VkTensorViewARM *>(*mlib));
}
#endif

#if defined(VK_ARM_tensors)
struct VkTensorFormatPropertiesARM_Ann : ManagedStructureAnnotation<VkTensorFormatPropertiesARM> {
    VkTensorFormatPropertiesARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkTensorFormatPropertiesARM", ml, "VkTensorFormatPropertiesARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkTensorFormatPropertiesARM_Ann * ann_VkTensorFormatPropertiesARM = nullptr;
void VkTensorFormatPropertiesARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkTensorFormatPropertiesARM, pNext), makeType<void *>(*mlib));
    addFieldEx("optimalTilingTensorFeatures", "optimalTilingTensorFeatures", offsetof(VkTensorFormatPropertiesARM, optimalTilingTensorFeatures), makeVkFlags_VkFormatFeatureFlags2());
    addFieldEx("linearTilingTensorFeatures", "linearTilingTensorFeatures", offsetof(VkTensorFormatPropertiesARM, linearTilingTensorFeatures), makeVkFlags_VkFormatFeatureFlags2());
}
#endif

#if defined(VK_ARM_tensors)
struct VkPhysicalDeviceTensorPropertiesARM_Ann : ManagedStructureAnnotation<VkPhysicalDeviceTensorPropertiesARM> {
    VkPhysicalDeviceTensorPropertiesARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceTensorPropertiesARM", ml, "VkPhysicalDeviceTensorPropertiesARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceTensorPropertiesARM_Ann * ann_VkPhysicalDeviceTensorPropertiesARM = nullptr;
void VkPhysicalDeviceTensorPropertiesARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceTensorPropertiesARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(maxTensorDimensionCount)>("maxTensorDimensionCount", "maxTensorDimensionCount");
    addField<DAS_BIND_MANAGED_FIELD(maxTensorElements)>("maxTensorElements", "maxTensorElements");
    addField<DAS_BIND_MANAGED_FIELD(maxPerDimensionTensorElements)>("maxPerDimensionTensorElements", "maxPerDimensionTensorElements");
    addField<DAS_BIND_MANAGED_FIELD(maxTensorStride)>("maxTensorStride", "maxTensorStride");
    addField<DAS_BIND_MANAGED_FIELD(maxTensorSize)>("maxTensorSize", "maxTensorSize");
    addField<DAS_BIND_MANAGED_FIELD(maxTensorShaderAccessArrayLength)>("maxTensorShaderAccessArrayLength", "maxTensorShaderAccessArrayLength");
    addField<DAS_BIND_MANAGED_FIELD(maxTensorShaderAccessSize)>("maxTensorShaderAccessSize", "maxTensorShaderAccessSize");
    addField<DAS_BIND_MANAGED_FIELD(maxDescriptorSetStorageTensors)>("maxDescriptorSetStorageTensors", "maxDescriptorSetStorageTensors");
    addField<DAS_BIND_MANAGED_FIELD(maxPerStageDescriptorSetStorageTensors)>("maxPerStageDescriptorSetStorageTensors", "maxPerStageDescriptorSetStorageTensors");
    addField<DAS_BIND_MANAGED_FIELD(maxDescriptorSetUpdateAfterBindStorageTensors)>("maxDescriptorSetUpdateAfterBindStorageTensors", "maxDescriptorSetUpdateAfterBindStorageTensors");
    addField<DAS_BIND_MANAGED_FIELD(maxPerStageDescriptorUpdateAfterBindStorageTensors)>("maxPerStageDescriptorUpdateAfterBindStorageTensors", "maxPerStageDescriptorUpdateAfterBindStorageTensors");
    addField<DAS_BIND_MANAGED_FIELD(shaderStorageTensorArrayNonUniformIndexingNative)>("shaderStorageTensorArrayNonUniformIndexingNative", "shaderStorageTensorArrayNonUniformIndexingNative");
    addFieldEx("shaderTensorSupportedStages", "shaderTensorSupportedStages", offsetof(VkPhysicalDeviceTensorPropertiesARM, shaderTensorSupportedStages), makeVkFlags_VkShaderStageFlags());
}
#endif

#if defined(VK_ARM_tensors)
struct VkTensorMemoryBarrierARM_Ann : ManagedStructureAnnotation<VkTensorMemoryBarrierARM> {
    VkTensorMemoryBarrierARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkTensorMemoryBarrierARM", ml, "VkTensorMemoryBarrierARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkTensorMemoryBarrierARM_Ann * ann_VkTensorMemoryBarrierARM = nullptr;
void VkTensorMemoryBarrierARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkTensorMemoryBarrierARM, pNext), makeType<void *>(*mlib));
    addFieldEx("srcStageMask", "srcStageMask", offsetof(VkTensorMemoryBarrierARM, srcStageMask), makeVkFlags_VkPipelineStageFlags2());
    addFieldEx("srcAccessMask", "srcAccessMask", offsetof(VkTensorMemoryBarrierARM, srcAccessMask), makeVkFlags_VkAccessFlags2());
    addFieldEx("dstStageMask", "dstStageMask", offsetof(VkTensorMemoryBarrierARM, dstStageMask), makeVkFlags_VkPipelineStageFlags2());
    addFieldEx("dstAccessMask", "dstAccessMask", offsetof(VkTensorMemoryBarrierARM, dstAccessMask), makeVkFlags_VkAccessFlags2());
    addField<DAS_BIND_MANAGED_FIELD(srcQueueFamilyIndex)>("srcQueueFamilyIndex", "srcQueueFamilyIndex");
    addField<DAS_BIND_MANAGED_FIELD(dstQueueFamilyIndex)>("dstQueueFamilyIndex", "dstQueueFamilyIndex");
    addField<DAS_BIND_MANAGED_FIELD(tensor)>("tensor", "tensor");
}
#endif

#if defined(VK_ARM_tensors)
struct VkTensorDependencyInfoARM_Ann : ManagedStructureAnnotation<VkTensorDependencyInfoARM> {
    VkTensorDependencyInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkTensorDependencyInfoARM", ml, "VkTensorDependencyInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkTensorDependencyInfoARM_Ann * ann_VkTensorDependencyInfoARM = nullptr;
void VkTensorDependencyInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkTensorDependencyInfoARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(tensorMemoryBarrierCount)>("tensorMemoryBarrierCount", "tensorMemoryBarrierCount");
    addFieldEx("pTensorMemoryBarriers", "pTensorMemoryBarriers", offsetof(VkTensorDependencyInfoARM, pTensorMemoryBarriers), makeType<VkTensorMemoryBarrierARM *>(*mlib));
}
#endif

#if defined(VK_ARM_tensors)
struct VkPhysicalDeviceTensorFeaturesARM_Ann : ManagedStructureAnnotation<VkPhysicalDeviceTensorFeaturesARM> {
    VkPhysicalDeviceTensorFeaturesARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceTensorFeaturesARM", ml, "VkPhysicalDeviceTensorFeaturesARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceTensorFeaturesARM_Ann * ann_VkPhysicalDeviceTensorFeaturesARM = nullptr;
void VkPhysicalDeviceTensorFeaturesARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceTensorFeaturesARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(tensorNonPacked)>("tensorNonPacked", "tensorNonPacked");
    addField<DAS_BIND_MANAGED_FIELD(shaderTensorAccess)>("shaderTensorAccess", "shaderTensorAccess");
    addField<DAS_BIND_MANAGED_FIELD(shaderStorageTensorArrayDynamicIndexing)>("shaderStorageTensorArrayDynamicIndexing", "shaderStorageTensorArrayDynamicIndexing");
    addField<DAS_BIND_MANAGED_FIELD(shaderStorageTensorArrayNonUniformIndexing)>("shaderStorageTensorArrayNonUniformIndexing", "shaderStorageTensorArrayNonUniformIndexing");
    addField<DAS_BIND_MANAGED_FIELD(descriptorBindingStorageTensorUpdateAfterBind)>("descriptorBindingStorageTensorUpdateAfterBind", "descriptorBindingStorageTensorUpdateAfterBind");
    addField<DAS_BIND_MANAGED_FIELD(tensors)>("tensors", "tensors");
}
#endif

#if defined(VK_ARM_tensors)
struct VkDeviceTensorMemoryRequirementsARM_Ann : ManagedStructureAnnotation<VkDeviceTensorMemoryRequirementsARM> {
    VkDeviceTensorMemoryRequirementsARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDeviceTensorMemoryRequirementsARM", ml, "VkDeviceTensorMemoryRequirementsARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDeviceTensorMemoryRequirementsARM_Ann * ann_VkDeviceTensorMemoryRequirementsARM = nullptr;
void VkDeviceTensorMemoryRequirementsARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDeviceTensorMemoryRequirementsARM, pNext), makeType<void *>(*mlib));
    addFieldEx("pCreateInfo", "pCreateInfo", offsetof(VkDeviceTensorMemoryRequirementsARM, pCreateInfo), makeType<VkTensorCreateInfoARM *>(*mlib));
}
#endif

#if defined(VK_ARM_tensors)
struct VkCopyTensorInfoARM_Ann : ManagedStructureAnnotation<VkCopyTensorInfoARM> {
    VkCopyTensorInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkCopyTensorInfoARM", ml, "VkCopyTensorInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkCopyTensorInfoARM_Ann * ann_VkCopyTensorInfoARM = nullptr;
void VkCopyTensorInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkCopyTensorInfoARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(srcTensor)>("srcTensor", "srcTensor");
    addField<DAS_BIND_MANAGED_FIELD(dstTensor)>("dstTensor", "dstTensor");
    addField<DAS_BIND_MANAGED_FIELD(regionCount)>("regionCount", "regionCount");
    addFieldEx("pRegions", "pRegions", offsetof(VkCopyTensorInfoARM, pRegions), makeType<VkTensorCopyARM *>(*mlib));
}
#endif

#if defined(VK_ARM_tensors)
struct VkTensorCopyARM_Ann : ManagedStructureAnnotation<VkTensorCopyARM> {
    VkTensorCopyARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkTensorCopyARM", ml, "VkTensorCopyARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkTensorCopyARM_Ann * ann_VkTensorCopyARM = nullptr;
void VkTensorCopyARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkTensorCopyARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(dimensionCount)>("dimensionCount", "dimensionCount");
    addFieldEx("pSrcOffset", "pSrcOffset", offsetof(VkTensorCopyARM, pSrcOffset), makeType<uint64_t *>(*mlib));
    addFieldEx("pDstOffset", "pDstOffset", offsetof(VkTensorCopyARM, pDstOffset), makeType<uint64_t *>(*mlib));
    addFieldEx("pExtent", "pExtent", offsetof(VkTensorCopyARM, pExtent), makeType<uint64_t *>(*mlib));
}
#endif

#if defined(VK_ARM_tensors)
struct VkMemoryDedicatedAllocateInfoTensorARM_Ann : ManagedStructureAnnotation<VkMemoryDedicatedAllocateInfoTensorARM> {
    VkMemoryDedicatedAllocateInfoTensorARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkMemoryDedicatedAllocateInfoTensorARM", ml, "VkMemoryDedicatedAllocateInfoTensorARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkMemoryDedicatedAllocateInfoTensorARM_Ann * ann_VkMemoryDedicatedAllocateInfoTensorARM = nullptr;
void VkMemoryDedicatedAllocateInfoTensorARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkMemoryDedicatedAllocateInfoTensorARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(tensor)>("tensor", "tensor");
}
#endif

#if defined(VK_ARM_tensors)
struct VkPhysicalDeviceDescriptorBufferTensorPropertiesARM_Ann : ManagedStructureAnnotation<VkPhysicalDeviceDescriptorBufferTensorPropertiesARM> {
    VkPhysicalDeviceDescriptorBufferTensorPropertiesARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceDescriptorBufferTensorPropertiesARM", ml, "VkPhysicalDeviceDescriptorBufferTensorPropertiesARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceDescriptorBufferTensorPropertiesARM_Ann * ann_VkPhysicalDeviceDescriptorBufferTensorPropertiesARM = nullptr;
void VkPhysicalDeviceDescriptorBufferTensorPropertiesARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceDescriptorBufferTensorPropertiesARM, pNext), makeType<void *>(*mlib));
    addFieldEx("tensorCaptureReplayDescriptorDataSize", "tensorCaptureReplayDescriptorDataSize", offsetof(VkPhysicalDeviceDescriptorBufferTensorPropertiesARM, tensorCaptureReplayDescriptorDataSize), makeType<uint64_t>(*mlib));
    addFieldEx("tensorViewCaptureReplayDescriptorDataSize", "tensorViewCaptureReplayDescriptorDataSize", offsetof(VkPhysicalDeviceDescriptorBufferTensorPropertiesARM, tensorViewCaptureReplayDescriptorDataSize), makeType<uint64_t>(*mlib));
    addFieldEx("tensorDescriptorSize", "tensorDescriptorSize", offsetof(VkPhysicalDeviceDescriptorBufferTensorPropertiesARM, tensorDescriptorSize), makeType<uint64_t>(*mlib));
}
#endif

#if defined(VK_ARM_tensors)
struct VkPhysicalDeviceDescriptorBufferTensorFeaturesARM_Ann : ManagedStructureAnnotation<VkPhysicalDeviceDescriptorBufferTensorFeaturesARM> {
    VkPhysicalDeviceDescriptorBufferTensorFeaturesARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceDescriptorBufferTensorFeaturesARM", ml, "VkPhysicalDeviceDescriptorBufferTensorFeaturesARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceDescriptorBufferTensorFeaturesARM_Ann * ann_VkPhysicalDeviceDescriptorBufferTensorFeaturesARM = nullptr;
void VkPhysicalDeviceDescriptorBufferTensorFeaturesARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceDescriptorBufferTensorFeaturesARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(descriptorBufferTensorDescriptors)>("descriptorBufferTensorDescriptors", "descriptorBufferTensorDescriptors");
}
#endif

#if defined(VK_ARM_tensors)
struct VkTensorCaptureDescriptorDataInfoARM_Ann : ManagedStructureAnnotation<VkTensorCaptureDescriptorDataInfoARM> {
    VkTensorCaptureDescriptorDataInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkTensorCaptureDescriptorDataInfoARM", ml, "VkTensorCaptureDescriptorDataInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkTensorCaptureDescriptorDataInfoARM_Ann * ann_VkTensorCaptureDescriptorDataInfoARM = nullptr;
void VkTensorCaptureDescriptorDataInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkTensorCaptureDescriptorDataInfoARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(tensor)>("tensor", "tensor");
}
#endif

#if defined(VK_ARM_tensors)
struct VkTensorViewCaptureDescriptorDataInfoARM_Ann : ManagedStructureAnnotation<VkTensorViewCaptureDescriptorDataInfoARM> {
    VkTensorViewCaptureDescriptorDataInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkTensorViewCaptureDescriptorDataInfoARM", ml, "VkTensorViewCaptureDescriptorDataInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkTensorViewCaptureDescriptorDataInfoARM_Ann * ann_VkTensorViewCaptureDescriptorDataInfoARM = nullptr;
void VkTensorViewCaptureDescriptorDataInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkTensorViewCaptureDescriptorDataInfoARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(tensorView)>("tensorView", "tensorView");
}
#endif

#if defined(VK_ARM_tensors)
struct VkDescriptorGetTensorInfoARM_Ann : ManagedStructureAnnotation<VkDescriptorGetTensorInfoARM> {
    VkDescriptorGetTensorInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDescriptorGetTensorInfoARM", ml, "VkDescriptorGetTensorInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDescriptorGetTensorInfoARM_Ann * ann_VkDescriptorGetTensorInfoARM = nullptr;
void VkDescriptorGetTensorInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDescriptorGetTensorInfoARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(tensorView)>("tensorView", "tensorView");
}
#endif

#if defined(VK_ARM_tensors)
struct VkFrameBoundaryTensorsARM_Ann : ManagedStructureAnnotation<VkFrameBoundaryTensorsARM> {
    VkFrameBoundaryTensorsARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkFrameBoundaryTensorsARM", ml, "VkFrameBoundaryTensorsARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkFrameBoundaryTensorsARM_Ann * ann_VkFrameBoundaryTensorsARM = nullptr;
void VkFrameBoundaryTensorsARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkFrameBoundaryTensorsARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(tensorCount)>("tensorCount", "tensorCount");
    addFieldEx("pTensors", "pTensors", offsetof(VkFrameBoundaryTensorsARM, pTensors), makeType<VkTensorARM *>(*mlib));
}
#endif

#if defined(VK_ARM_tensors)
struct VkPhysicalDeviceExternalTensorInfoARM_Ann : ManagedStructureAnnotation<VkPhysicalDeviceExternalTensorInfoARM> {
    VkPhysicalDeviceExternalTensorInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceExternalTensorInfoARM", ml, "VkPhysicalDeviceExternalTensorInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceExternalTensorInfoARM_Ann * ann_VkPhysicalDeviceExternalTensorInfoARM = nullptr;
void VkPhysicalDeviceExternalTensorInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceExternalTensorInfoARM, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkPhysicalDeviceExternalTensorInfoARM, flags), makeVkFlags_VkTensorCreateFlagsARM());
    addFieldEx("pDescription", "pDescription", offsetof(VkPhysicalDeviceExternalTensorInfoARM, pDescription), makeType<VkTensorDescriptionARM *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(handleType)>("handleType", "handleType");
}
#endif

#if defined(VK_ARM_tensors)
struct VkExternalTensorPropertiesARM_Ann : ManagedStructureAnnotation<VkExternalTensorPropertiesARM> {
    VkExternalTensorPropertiesARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkExternalTensorPropertiesARM", ml, "VkExternalTensorPropertiesARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkExternalTensorPropertiesARM_Ann * ann_VkExternalTensorPropertiesARM = nullptr;
void VkExternalTensorPropertiesARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkExternalTensorPropertiesARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(externalMemoryProperties)>("externalMemoryProperties", "externalMemoryProperties");
}
#endif

#if defined(VK_ARM_tensors)
struct VkExternalMemoryTensorCreateInfoARM_Ann : ManagedStructureAnnotation<VkExternalMemoryTensorCreateInfoARM> {
    VkExternalMemoryTensorCreateInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkExternalMemoryTensorCreateInfoARM", ml, "VkExternalMemoryTensorCreateInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkExternalMemoryTensorCreateInfoARM_Ann * ann_VkExternalMemoryTensorCreateInfoARM = nullptr;
void VkExternalMemoryTensorCreateInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkExternalMemoryTensorCreateInfoARM, pNext), makeType<void *>(*mlib));
    addFieldEx("handleTypes", "handleTypes", offsetof(VkExternalMemoryTensorCreateInfoARM, handleTypes), makeVkFlags_VkExternalMemoryHandleTypeFlags());
}
#endif

#if defined(VK_EXT_shader_float8)
struct VkPhysicalDeviceShaderFloat8FeaturesEXT_Ann : ManagedStructureAnnotation<VkPhysicalDeviceShaderFloat8FeaturesEXT> {
    VkPhysicalDeviceShaderFloat8FeaturesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceShaderFloat8FeaturesEXT", ml, "VkPhysicalDeviceShaderFloat8FeaturesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceShaderFloat8FeaturesEXT_Ann * ann_VkPhysicalDeviceShaderFloat8FeaturesEXT = nullptr;
void VkPhysicalDeviceShaderFloat8FeaturesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceShaderFloat8FeaturesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(shaderFloat8)>("shaderFloat8", "shaderFloat8");
    addField<DAS_BIND_MANAGED_FIELD(shaderFloat8CooperativeMatrix)>("shaderFloat8CooperativeMatrix", "shaderFloat8CooperativeMatrix");
}
#endif

#if defined(VK_ARM_data_graph)
struct VkPhysicalDeviceDataGraphFeaturesARM_Ann : ManagedStructureAnnotation<VkPhysicalDeviceDataGraphFeaturesARM> {
    VkPhysicalDeviceDataGraphFeaturesARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceDataGraphFeaturesARM", ml, "VkPhysicalDeviceDataGraphFeaturesARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceDataGraphFeaturesARM_Ann * ann_VkPhysicalDeviceDataGraphFeaturesARM = nullptr;
void VkPhysicalDeviceDataGraphFeaturesARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceDataGraphFeaturesARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(dataGraph)>("dataGraph", "dataGraph");
    addField<DAS_BIND_MANAGED_FIELD(dataGraphUpdateAfterBind)>("dataGraphUpdateAfterBind", "dataGraphUpdateAfterBind");
    addField<DAS_BIND_MANAGED_FIELD(dataGraphSpecializationConstants)>("dataGraphSpecializationConstants", "dataGraphSpecializationConstants");
    addField<DAS_BIND_MANAGED_FIELD(dataGraphDescriptorBuffer)>("dataGraphDescriptorBuffer", "dataGraphDescriptorBuffer");
    addField<DAS_BIND_MANAGED_FIELD(dataGraphShaderModule)>("dataGraphShaderModule", "dataGraphShaderModule");
}
#endif

#if defined(VK_ARM_data_graph)
struct VkDataGraphPipelineConstantTensorSemiStructuredSparsityInfoARM_Ann : ManagedStructureAnnotation<VkDataGraphPipelineConstantTensorSemiStructuredSparsityInfoARM> {
    VkDataGraphPipelineConstantTensorSemiStructuredSparsityInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDataGraphPipelineConstantTensorSemiStructuredSparsityInfoARM", ml, "VkDataGraphPipelineConstantTensorSemiStructuredSparsityInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDataGraphPipelineConstantTensorSemiStructuredSparsityInfoARM_Ann * ann_VkDataGraphPipelineConstantTensorSemiStructuredSparsityInfoARM = nullptr;
void VkDataGraphPipelineConstantTensorSemiStructuredSparsityInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDataGraphPipelineConstantTensorSemiStructuredSparsityInfoARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(dimension)>("dimension", "dimension");
    addField<DAS_BIND_MANAGED_FIELD(zeroCount)>("zeroCount", "zeroCount");
    addField<DAS_BIND_MANAGED_FIELD(groupSize)>("groupSize", "groupSize");
}
#endif

#if defined(VK_ARM_data_graph)
struct VkDataGraphPipelineConstantARM_Ann : ManagedStructureAnnotation<VkDataGraphPipelineConstantARM> {
    VkDataGraphPipelineConstantARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDataGraphPipelineConstantARM", ml, "VkDataGraphPipelineConstantARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDataGraphPipelineConstantARM_Ann * ann_VkDataGraphPipelineConstantARM = nullptr;
void VkDataGraphPipelineConstantARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDataGraphPipelineConstantARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(id)>("id", "id");
    addFieldEx("pConstantData", "pConstantData", offsetof(VkDataGraphPipelineConstantARM, pConstantData), makeType<void *>(*mlib));
}
#endif

#if defined(VK_ARM_data_graph)
struct VkDataGraphPipelineResourceInfoARM_Ann : ManagedStructureAnnotation<VkDataGraphPipelineResourceInfoARM> {
    VkDataGraphPipelineResourceInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDataGraphPipelineResourceInfoARM", ml, "VkDataGraphPipelineResourceInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDataGraphPipelineResourceInfoARM_Ann * ann_VkDataGraphPipelineResourceInfoARM = nullptr;
void VkDataGraphPipelineResourceInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDataGraphPipelineResourceInfoARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(descriptorSet)>("descriptorSet", "descriptorSet");
    addField<DAS_BIND_MANAGED_FIELD(binding)>("binding", "binding");
    addField<DAS_BIND_MANAGED_FIELD(arrayElement)>("arrayElement", "arrayElement");
}
#endif

#if defined(VK_ARM_data_graph_optical_flow)
struct VkDataGraphPipelineResourceInfoImageLayoutARM_Ann : ManagedStructureAnnotation<VkDataGraphPipelineResourceInfoImageLayoutARM> {
    VkDataGraphPipelineResourceInfoImageLayoutARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDataGraphPipelineResourceInfoImageLayoutARM", ml, "VkDataGraphPipelineResourceInfoImageLayoutARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDataGraphPipelineResourceInfoImageLayoutARM_Ann * ann_VkDataGraphPipelineResourceInfoImageLayoutARM = nullptr;
void VkDataGraphPipelineResourceInfoImageLayoutARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDataGraphPipelineResourceInfoImageLayoutARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(layout)>("layout", "layout");
}
#endif

#if defined(VK_ARM_data_graph)
struct VkDataGraphPipelineCompilerControlCreateInfoARM_Ann : ManagedStructureAnnotation<VkDataGraphPipelineCompilerControlCreateInfoARM> {
    VkDataGraphPipelineCompilerControlCreateInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDataGraphPipelineCompilerControlCreateInfoARM", ml, "VkDataGraphPipelineCompilerControlCreateInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDataGraphPipelineCompilerControlCreateInfoARM_Ann * ann_VkDataGraphPipelineCompilerControlCreateInfoARM = nullptr;
void VkDataGraphPipelineCompilerControlCreateInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDataGraphPipelineCompilerControlCreateInfoARM, pNext), makeType<void *>(*mlib));
    addFieldEx("pVendorOptions", "pVendorOptions", offsetof(VkDataGraphPipelineCompilerControlCreateInfoARM, pVendorOptions), makeType<char *>(*mlib));
}
#endif

#if defined(VK_ARM_data_graph)
struct VkDataGraphPipelineCreateInfoARM_Ann : ManagedStructureAnnotation<VkDataGraphPipelineCreateInfoARM> {
    VkDataGraphPipelineCreateInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDataGraphPipelineCreateInfoARM", ml, "VkDataGraphPipelineCreateInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDataGraphPipelineCreateInfoARM_Ann * ann_VkDataGraphPipelineCreateInfoARM = nullptr;
void VkDataGraphPipelineCreateInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDataGraphPipelineCreateInfoARM, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkDataGraphPipelineCreateInfoARM, flags), makeVkFlags_VkPipelineCreateFlags2());
    addField<DAS_BIND_MANAGED_FIELD(layout)>("layout", "layout");
    addField<DAS_BIND_MANAGED_FIELD(resourceInfoCount)>("resourceInfoCount", "resourceInfoCount");
    addFieldEx("pResourceInfos", "pResourceInfos", offsetof(VkDataGraphPipelineCreateInfoARM, pResourceInfos), makeType<VkDataGraphPipelineResourceInfoARM *>(*mlib));
}
#endif

#if defined(VK_ARM_data_graph)
struct VkDataGraphPipelineShaderModuleCreateInfoARM_Ann : ManagedStructureAnnotation<VkDataGraphPipelineShaderModuleCreateInfoARM> {
    VkDataGraphPipelineShaderModuleCreateInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDataGraphPipelineShaderModuleCreateInfoARM", ml, "VkDataGraphPipelineShaderModuleCreateInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDataGraphPipelineShaderModuleCreateInfoARM_Ann * ann_VkDataGraphPipelineShaderModuleCreateInfoARM = nullptr;
void VkDataGraphPipelineShaderModuleCreateInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDataGraphPipelineShaderModuleCreateInfoARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(module)>("module_", "module");
    addFieldEx("pName", "pName", offsetof(VkDataGraphPipelineShaderModuleCreateInfoARM, pName), makeType<char *>(*mlib));
    addFieldEx("pSpecializationInfo", "pSpecializationInfo", offsetof(VkDataGraphPipelineShaderModuleCreateInfoARM, pSpecializationInfo), makeType<VkSpecializationInfo *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(constantCount)>("constantCount", "constantCount");
    addFieldEx("pConstants", "pConstants", offsetof(VkDataGraphPipelineShaderModuleCreateInfoARM, pConstants), makeType<VkDataGraphPipelineConstantARM *>(*mlib));
}
#endif

#if defined(VK_ARM_data_graph)
struct VkDataGraphPipelineSessionCreateInfoARM_Ann : ManagedStructureAnnotation<VkDataGraphPipelineSessionCreateInfoARM> {
    VkDataGraphPipelineSessionCreateInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDataGraphPipelineSessionCreateInfoARM", ml, "VkDataGraphPipelineSessionCreateInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDataGraphPipelineSessionCreateInfoARM_Ann * ann_VkDataGraphPipelineSessionCreateInfoARM = nullptr;
void VkDataGraphPipelineSessionCreateInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDataGraphPipelineSessionCreateInfoARM, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkDataGraphPipelineSessionCreateInfoARM, flags), makeVkFlags_VkDataGraphPipelineSessionCreateFlagsARM());
    addField<DAS_BIND_MANAGED_FIELD(dataGraphPipeline)>("dataGraphPipeline", "dataGraphPipeline");
}
#endif

#if defined(VK_ARM_data_graph)
struct VkDataGraphPipelineSessionBindPointRequirementsInfoARM_Ann : ManagedStructureAnnotation<VkDataGraphPipelineSessionBindPointRequirementsInfoARM> {
    VkDataGraphPipelineSessionBindPointRequirementsInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDataGraphPipelineSessionBindPointRequirementsInfoARM", ml, "VkDataGraphPipelineSessionBindPointRequirementsInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDataGraphPipelineSessionBindPointRequirementsInfoARM_Ann * ann_VkDataGraphPipelineSessionBindPointRequirementsInfoARM = nullptr;
void VkDataGraphPipelineSessionBindPointRequirementsInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDataGraphPipelineSessionBindPointRequirementsInfoARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(session)>("session", "session");
}
#endif

#if defined(VK_ARM_data_graph)
struct VkDataGraphPipelineSessionBindPointRequirementARM_Ann : ManagedStructureAnnotation<VkDataGraphPipelineSessionBindPointRequirementARM> {
    VkDataGraphPipelineSessionBindPointRequirementARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDataGraphPipelineSessionBindPointRequirementARM", ml, "VkDataGraphPipelineSessionBindPointRequirementARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDataGraphPipelineSessionBindPointRequirementARM_Ann * ann_VkDataGraphPipelineSessionBindPointRequirementARM = nullptr;
void VkDataGraphPipelineSessionBindPointRequirementARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDataGraphPipelineSessionBindPointRequirementARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(bindPoint)>("bindPoint", "bindPoint");
    addField<DAS_BIND_MANAGED_FIELD(bindPointType)>("bindPointType", "bindPointType");
    addField<DAS_BIND_MANAGED_FIELD(numObjects)>("numObjects", "numObjects");
}
#endif

#if defined(VK_ARM_data_graph)
struct VkDataGraphPipelineSessionMemoryRequirementsInfoARM_Ann : ManagedStructureAnnotation<VkDataGraphPipelineSessionMemoryRequirementsInfoARM> {
    VkDataGraphPipelineSessionMemoryRequirementsInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDataGraphPipelineSessionMemoryRequirementsInfoARM", ml, "VkDataGraphPipelineSessionMemoryRequirementsInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDataGraphPipelineSessionMemoryRequirementsInfoARM_Ann * ann_VkDataGraphPipelineSessionMemoryRequirementsInfoARM = nullptr;
void VkDataGraphPipelineSessionMemoryRequirementsInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDataGraphPipelineSessionMemoryRequirementsInfoARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(session)>("session", "session");
    addField<DAS_BIND_MANAGED_FIELD(bindPoint)>("bindPoint", "bindPoint");
    addField<DAS_BIND_MANAGED_FIELD(objectIndex)>("objectIndex", "objectIndex");
}
#endif

#if defined(VK_ARM_data_graph)
struct VkBindDataGraphPipelineSessionMemoryInfoARM_Ann : ManagedStructureAnnotation<VkBindDataGraphPipelineSessionMemoryInfoARM> {
    VkBindDataGraphPipelineSessionMemoryInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkBindDataGraphPipelineSessionMemoryInfoARM", ml, "VkBindDataGraphPipelineSessionMemoryInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkBindDataGraphPipelineSessionMemoryInfoARM_Ann * ann_VkBindDataGraphPipelineSessionMemoryInfoARM = nullptr;
void VkBindDataGraphPipelineSessionMemoryInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkBindDataGraphPipelineSessionMemoryInfoARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(session)>("session", "session");
    addField<DAS_BIND_MANAGED_FIELD(bindPoint)>("bindPoint", "bindPoint");
    addField<DAS_BIND_MANAGED_FIELD(objectIndex)>("objectIndex", "objectIndex");
    addField<DAS_BIND_MANAGED_FIELD(memory)>("memory", "memory");
    addField<DAS_BIND_MANAGED_FIELD(memoryOffset)>("memoryOffset", "memoryOffset");
}
#endif

#if defined(VK_ARM_data_graph)
struct VkDataGraphPipelineInfoARM_Ann : ManagedStructureAnnotation<VkDataGraphPipelineInfoARM> {
    VkDataGraphPipelineInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDataGraphPipelineInfoARM", ml, "VkDataGraphPipelineInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDataGraphPipelineInfoARM_Ann * ann_VkDataGraphPipelineInfoARM = nullptr;
void VkDataGraphPipelineInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDataGraphPipelineInfoARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(dataGraphPipeline)>("dataGraphPipeline", "dataGraphPipeline");
}
#endif

#if defined(VK_ARM_data_graph)
struct VkDataGraphPipelinePropertyQueryResultARM_Ann : ManagedStructureAnnotation<VkDataGraphPipelinePropertyQueryResultARM> {
    VkDataGraphPipelinePropertyQueryResultARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDataGraphPipelinePropertyQueryResultARM", ml, "VkDataGraphPipelinePropertyQueryResultARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDataGraphPipelinePropertyQueryResultARM_Ann * ann_VkDataGraphPipelinePropertyQueryResultARM = nullptr;
void VkDataGraphPipelinePropertyQueryResultARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDataGraphPipelinePropertyQueryResultARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(property)>("property", "property");
    addField<DAS_BIND_MANAGED_FIELD(isText)>("isText", "isText");
    addFieldEx("dataSize", "dataSize", offsetof(VkDataGraphPipelinePropertyQueryResultARM, dataSize), makeType<uint64_t>(*mlib));
    addFieldEx("pData", "pData", offsetof(VkDataGraphPipelinePropertyQueryResultARM, pData), makeType<void *>(*mlib));
}
#endif

#if defined(VK_ARM_data_graph)
struct VkDataGraphPipelineIdentifierCreateInfoARM_Ann : ManagedStructureAnnotation<VkDataGraphPipelineIdentifierCreateInfoARM> {
    VkDataGraphPipelineIdentifierCreateInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDataGraphPipelineIdentifierCreateInfoARM", ml, "VkDataGraphPipelineIdentifierCreateInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDataGraphPipelineIdentifierCreateInfoARM_Ann * ann_VkDataGraphPipelineIdentifierCreateInfoARM = nullptr;
void VkDataGraphPipelineIdentifierCreateInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDataGraphPipelineIdentifierCreateInfoARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(identifierSize)>("identifierSize", "identifierSize");
    addFieldEx("pIdentifier", "pIdentifier", offsetof(VkDataGraphPipelineIdentifierCreateInfoARM, pIdentifier), makeType<uint8_t *>(*mlib));
}
#endif

#if defined(VK_ARM_data_graph)
struct VkDataGraphPipelineDispatchInfoARM_Ann : ManagedStructureAnnotation<VkDataGraphPipelineDispatchInfoARM> {
    VkDataGraphPipelineDispatchInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDataGraphPipelineDispatchInfoARM", ml, "VkDataGraphPipelineDispatchInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDataGraphPipelineDispatchInfoARM_Ann * ann_VkDataGraphPipelineDispatchInfoARM = nullptr;
void VkDataGraphPipelineDispatchInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDataGraphPipelineDispatchInfoARM, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkDataGraphPipelineDispatchInfoARM, flags), makeVkFlags_VkDataGraphPipelineDispatchFlagsARM());
}
#endif

#if defined(VK_ARM_data_graph)
struct VkPhysicalDeviceDataGraphProcessingEngineARM_Ann : ManagedStructureAnnotation<VkPhysicalDeviceDataGraphProcessingEngineARM> {
    VkPhysicalDeviceDataGraphProcessingEngineARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceDataGraphProcessingEngineARM", ml, "VkPhysicalDeviceDataGraphProcessingEngineARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceDataGraphProcessingEngineARM_Ann * ann_VkPhysicalDeviceDataGraphProcessingEngineARM = nullptr;
void VkPhysicalDeviceDataGraphProcessingEngineARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(type)>("type_", "type");
    addField<DAS_BIND_MANAGED_FIELD(isForeign)>("isForeign", "isForeign");
}
#endif

#if defined(VK_ARM_data_graph)
struct VkPhysicalDeviceDataGraphOperationSupportARM_Ann : ManagedStructureAnnotation<VkPhysicalDeviceDataGraphOperationSupportARM> {
    VkPhysicalDeviceDataGraphOperationSupportARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceDataGraphOperationSupportARM", ml, "VkPhysicalDeviceDataGraphOperationSupportARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceDataGraphOperationSupportARM_Ann * ann_VkPhysicalDeviceDataGraphOperationSupportARM = nullptr;
void VkPhysicalDeviceDataGraphOperationSupportARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(operationType)>("operationType", "operationType");
    addFieldEx("name", "name", offsetof(VkPhysicalDeviceDataGraphOperationSupportARM, name), makeFixedArrayTypeDecl(int32_t(VK_MAX_PHYSICAL_DEVICE_DATA_GRAPH_OPERATION_SET_NAME_SIZE_ARM), makeType<int8_t>(*mlib)));
    addField<DAS_BIND_MANAGED_FIELD(version)>("version", "version");
}
#endif

#if defined(VK_ARM_data_graph)
struct VkQueueFamilyDataGraphPropertiesARM_Ann : ManagedStructureAnnotation<VkQueueFamilyDataGraphPropertiesARM> {
    VkQueueFamilyDataGraphPropertiesARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkQueueFamilyDataGraphPropertiesARM", ml, "VkQueueFamilyDataGraphPropertiesARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkQueueFamilyDataGraphPropertiesARM_Ann * ann_VkQueueFamilyDataGraphPropertiesARM = nullptr;
void VkQueueFamilyDataGraphPropertiesARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkQueueFamilyDataGraphPropertiesARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(engine)>("engine", "engine");
    addField<DAS_BIND_MANAGED_FIELD(operation)>("operation", "operation");
}
#endif

#if defined(VK_ARM_data_graph)
struct VkPhysicalDeviceQueueFamilyDataGraphProcessingEngineInfoARM_Ann : ManagedStructureAnnotation<VkPhysicalDeviceQueueFamilyDataGraphProcessingEngineInfoARM> {
    VkPhysicalDeviceQueueFamilyDataGraphProcessingEngineInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceQueueFamilyDataGraphProcessingEngineInfoARM", ml, "VkPhysicalDeviceQueueFamilyDataGraphProcessingEngineInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceQueueFamilyDataGraphProcessingEngineInfoARM_Ann * ann_VkPhysicalDeviceQueueFamilyDataGraphProcessingEngineInfoARM = nullptr;
void VkPhysicalDeviceQueueFamilyDataGraphProcessingEngineInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceQueueFamilyDataGraphProcessingEngineInfoARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(queueFamilyIndex)>("queueFamilyIndex", "queueFamilyIndex");
    addField<DAS_BIND_MANAGED_FIELD(engineType)>("engineType", "engineType");
}
#endif

#if defined(VK_ARM_data_graph)
struct VkQueueFamilyDataGraphProcessingEnginePropertiesARM_Ann : ManagedStructureAnnotation<VkQueueFamilyDataGraphProcessingEnginePropertiesARM> {
    VkQueueFamilyDataGraphProcessingEnginePropertiesARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkQueueFamilyDataGraphProcessingEnginePropertiesARM", ml, "VkQueueFamilyDataGraphProcessingEnginePropertiesARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkQueueFamilyDataGraphProcessingEnginePropertiesARM_Ann * ann_VkQueueFamilyDataGraphProcessingEnginePropertiesARM = nullptr;
void VkQueueFamilyDataGraphProcessingEnginePropertiesARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkQueueFamilyDataGraphProcessingEnginePropertiesARM, pNext), makeType<void *>(*mlib));
    addFieldEx("foreignSemaphoreHandleTypes", "foreignSemaphoreHandleTypes", offsetof(VkQueueFamilyDataGraphProcessingEnginePropertiesARM, foreignSemaphoreHandleTypes), makeVkFlags_VkExternalSemaphoreHandleTypeFlags());
    addFieldEx("foreignMemoryHandleTypes", "foreignMemoryHandleTypes", offsetof(VkQueueFamilyDataGraphProcessingEnginePropertiesARM, foreignMemoryHandleTypes), makeVkFlags_VkExternalMemoryHandleTypeFlags());
}
#endif

#if defined(VK_ARM_data_graph)
struct VkDataGraphProcessingEngineCreateInfoARM_Ann : ManagedStructureAnnotation<VkDataGraphProcessingEngineCreateInfoARM> {
    VkDataGraphProcessingEngineCreateInfoARM_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDataGraphProcessingEngineCreateInfoARM", ml, "VkDataGraphProcessingEngineCreateInfoARM") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDataGraphProcessingEngineCreateInfoARM_Ann * ann_VkDataGraphProcessingEngineCreateInfoARM = nullptr;
void VkDataGraphProcessingEngineCreateInfoARM_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDataGraphProcessingEngineCreateInfoARM, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(processingEngineCount)>("processingEngineCount", "processingEngineCount");
    addFieldEx("pProcessingEngines", "pProcessingEngines", offsetof(VkDataGraphProcessingEngineCreateInfoARM, pProcessingEngines), makeType<VkPhysicalDeviceDataGraphProcessingEngineARM *>(*mlib));
}
#endif

#if defined(VK_SEC_pipeline_cache_incremental_mode)
struct VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC_Ann : ManagedStructureAnnotation<VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC> {
    VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC", ml, "VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC_Ann * ann_VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC = nullptr;
void VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(pipelineCacheIncrementalMode)>("pipelineCacheIncrementalMode", "pipelineCacheIncrementalMode");
}
#endif

void das_vulkan_add_structs_23(Module & mod, ModuleLibrary & lib) {
#if defined(VK_SEC_throttle_hint)
    ann_VkThrottleHintSubmitInfoSEC = new VkThrottleHintSubmitInfoSEC_Ann(lib); mod.addAnnotation(ann_VkThrottleHintSubmitInfoSEC);
#endif
#if defined(VK_ARM_tensors)
    ann_VkTensorDescriptionARM = new VkTensorDescriptionARM_Ann(lib); mod.addAnnotation(ann_VkTensorDescriptionARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkTensorCreateInfoARM = new VkTensorCreateInfoARM_Ann(lib); mod.addAnnotation(ann_VkTensorCreateInfoARM);
#endif
#if defined(VK_EXT_descriptor_heap)
    ann_VkTensorViewCreateInfoARM = new VkTensorViewCreateInfoARM_Ann(lib); mod.addAnnotation(ann_VkTensorViewCreateInfoARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkTensorMemoryRequirementsInfoARM = new VkTensorMemoryRequirementsInfoARM_Ann(lib); mod.addAnnotation(ann_VkTensorMemoryRequirementsInfoARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkBindTensorMemoryInfoARM = new VkBindTensorMemoryInfoARM_Ann(lib); mod.addAnnotation(ann_VkBindTensorMemoryInfoARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkWriteDescriptorSetTensorARM = new VkWriteDescriptorSetTensorARM_Ann(lib); mod.addAnnotation(ann_VkWriteDescriptorSetTensorARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkTensorFormatPropertiesARM = new VkTensorFormatPropertiesARM_Ann(lib); mod.addAnnotation(ann_VkTensorFormatPropertiesARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkPhysicalDeviceTensorPropertiesARM = new VkPhysicalDeviceTensorPropertiesARM_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceTensorPropertiesARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkTensorMemoryBarrierARM = new VkTensorMemoryBarrierARM_Ann(lib); mod.addAnnotation(ann_VkTensorMemoryBarrierARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkTensorDependencyInfoARM = new VkTensorDependencyInfoARM_Ann(lib); mod.addAnnotation(ann_VkTensorDependencyInfoARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkPhysicalDeviceTensorFeaturesARM = new VkPhysicalDeviceTensorFeaturesARM_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceTensorFeaturesARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkDeviceTensorMemoryRequirementsARM = new VkDeviceTensorMemoryRequirementsARM_Ann(lib); mod.addAnnotation(ann_VkDeviceTensorMemoryRequirementsARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkCopyTensorInfoARM = new VkCopyTensorInfoARM_Ann(lib); mod.addAnnotation(ann_VkCopyTensorInfoARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkTensorCopyARM = new VkTensorCopyARM_Ann(lib); mod.addAnnotation(ann_VkTensorCopyARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkMemoryDedicatedAllocateInfoTensorARM = new VkMemoryDedicatedAllocateInfoTensorARM_Ann(lib); mod.addAnnotation(ann_VkMemoryDedicatedAllocateInfoTensorARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkPhysicalDeviceDescriptorBufferTensorPropertiesARM = new VkPhysicalDeviceDescriptorBufferTensorPropertiesARM_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceDescriptorBufferTensorPropertiesARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkPhysicalDeviceDescriptorBufferTensorFeaturesARM = new VkPhysicalDeviceDescriptorBufferTensorFeaturesARM_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceDescriptorBufferTensorFeaturesARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkTensorCaptureDescriptorDataInfoARM = new VkTensorCaptureDescriptorDataInfoARM_Ann(lib); mod.addAnnotation(ann_VkTensorCaptureDescriptorDataInfoARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkTensorViewCaptureDescriptorDataInfoARM = new VkTensorViewCaptureDescriptorDataInfoARM_Ann(lib); mod.addAnnotation(ann_VkTensorViewCaptureDescriptorDataInfoARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkDescriptorGetTensorInfoARM = new VkDescriptorGetTensorInfoARM_Ann(lib); mod.addAnnotation(ann_VkDescriptorGetTensorInfoARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkFrameBoundaryTensorsARM = new VkFrameBoundaryTensorsARM_Ann(lib); mod.addAnnotation(ann_VkFrameBoundaryTensorsARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkPhysicalDeviceExternalTensorInfoARM = new VkPhysicalDeviceExternalTensorInfoARM_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceExternalTensorInfoARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkExternalTensorPropertiesARM = new VkExternalTensorPropertiesARM_Ann(lib); mod.addAnnotation(ann_VkExternalTensorPropertiesARM);
#endif
#if defined(VK_ARM_tensors)
    ann_VkExternalMemoryTensorCreateInfoARM = new VkExternalMemoryTensorCreateInfoARM_Ann(lib); mod.addAnnotation(ann_VkExternalMemoryTensorCreateInfoARM);
#endif
#if defined(VK_EXT_shader_float8)
    ann_VkPhysicalDeviceShaderFloat8FeaturesEXT = new VkPhysicalDeviceShaderFloat8FeaturesEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceShaderFloat8FeaturesEXT);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkPhysicalDeviceDataGraphFeaturesARM = new VkPhysicalDeviceDataGraphFeaturesARM_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceDataGraphFeaturesARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineConstantTensorSemiStructuredSparsityInfoARM = new VkDataGraphPipelineConstantTensorSemiStructuredSparsityInfoARM_Ann(lib); mod.addAnnotation(ann_VkDataGraphPipelineConstantTensorSemiStructuredSparsityInfoARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineConstantARM = new VkDataGraphPipelineConstantARM_Ann(lib); mod.addAnnotation(ann_VkDataGraphPipelineConstantARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineResourceInfoARM = new VkDataGraphPipelineResourceInfoARM_Ann(lib); mod.addAnnotation(ann_VkDataGraphPipelineResourceInfoARM);
#endif
#if defined(VK_ARM_data_graph_optical_flow)
    ann_VkDataGraphPipelineResourceInfoImageLayoutARM = new VkDataGraphPipelineResourceInfoImageLayoutARM_Ann(lib); mod.addAnnotation(ann_VkDataGraphPipelineResourceInfoImageLayoutARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineCompilerControlCreateInfoARM = new VkDataGraphPipelineCompilerControlCreateInfoARM_Ann(lib); mod.addAnnotation(ann_VkDataGraphPipelineCompilerControlCreateInfoARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineCreateInfoARM = new VkDataGraphPipelineCreateInfoARM_Ann(lib); mod.addAnnotation(ann_VkDataGraphPipelineCreateInfoARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineShaderModuleCreateInfoARM = new VkDataGraphPipelineShaderModuleCreateInfoARM_Ann(lib); mod.addAnnotation(ann_VkDataGraphPipelineShaderModuleCreateInfoARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineSessionCreateInfoARM = new VkDataGraphPipelineSessionCreateInfoARM_Ann(lib); mod.addAnnotation(ann_VkDataGraphPipelineSessionCreateInfoARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineSessionBindPointRequirementsInfoARM = new VkDataGraphPipelineSessionBindPointRequirementsInfoARM_Ann(lib); mod.addAnnotation(ann_VkDataGraphPipelineSessionBindPointRequirementsInfoARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineSessionBindPointRequirementARM = new VkDataGraphPipelineSessionBindPointRequirementARM_Ann(lib); mod.addAnnotation(ann_VkDataGraphPipelineSessionBindPointRequirementARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineSessionMemoryRequirementsInfoARM = new VkDataGraphPipelineSessionMemoryRequirementsInfoARM_Ann(lib); mod.addAnnotation(ann_VkDataGraphPipelineSessionMemoryRequirementsInfoARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkBindDataGraphPipelineSessionMemoryInfoARM = new VkBindDataGraphPipelineSessionMemoryInfoARM_Ann(lib); mod.addAnnotation(ann_VkBindDataGraphPipelineSessionMemoryInfoARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineInfoARM = new VkDataGraphPipelineInfoARM_Ann(lib); mod.addAnnotation(ann_VkDataGraphPipelineInfoARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelinePropertyQueryResultARM = new VkDataGraphPipelinePropertyQueryResultARM_Ann(lib); mod.addAnnotation(ann_VkDataGraphPipelinePropertyQueryResultARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineIdentifierCreateInfoARM = new VkDataGraphPipelineIdentifierCreateInfoARM_Ann(lib); mod.addAnnotation(ann_VkDataGraphPipelineIdentifierCreateInfoARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineDispatchInfoARM = new VkDataGraphPipelineDispatchInfoARM_Ann(lib); mod.addAnnotation(ann_VkDataGraphPipelineDispatchInfoARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkPhysicalDeviceDataGraphProcessingEngineARM = new VkPhysicalDeviceDataGraphProcessingEngineARM_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceDataGraphProcessingEngineARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkPhysicalDeviceDataGraphOperationSupportARM = new VkPhysicalDeviceDataGraphOperationSupportARM_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceDataGraphOperationSupportARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkQueueFamilyDataGraphPropertiesARM = new VkQueueFamilyDataGraphPropertiesARM_Ann(lib); mod.addAnnotation(ann_VkQueueFamilyDataGraphPropertiesARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkPhysicalDeviceQueueFamilyDataGraphProcessingEngineInfoARM = new VkPhysicalDeviceQueueFamilyDataGraphProcessingEngineInfoARM_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceQueueFamilyDataGraphProcessingEngineInfoARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkQueueFamilyDataGraphProcessingEnginePropertiesARM = new VkQueueFamilyDataGraphProcessingEnginePropertiesARM_Ann(lib); mod.addAnnotation(ann_VkQueueFamilyDataGraphProcessingEnginePropertiesARM);
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphProcessingEngineCreateInfoARM = new VkDataGraphProcessingEngineCreateInfoARM_Ann(lib); mod.addAnnotation(ann_VkDataGraphProcessingEngineCreateInfoARM);
#endif
#if defined(VK_SEC_pipeline_cache_incremental_mode)
    ann_VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC = new VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC_Ann(lib); mod.addAnnotation(ann_VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC);
#endif
}

void das_vulkan_fill_structs_23(Module & mod, ModuleLibrary & lib) {
#if defined(VK_SEC_throttle_hint)
    ann_VkThrottleHintSubmitInfoSEC->mlib = &lib; ann_VkThrottleHintSubmitInfoSEC->init(); ann_VkThrottleHintSubmitInfoSEC->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkTensorDescriptionARM->mlib = &lib; ann_VkTensorDescriptionARM->init(); ann_VkTensorDescriptionARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkTensorCreateInfoARM->mlib = &lib; ann_VkTensorCreateInfoARM->init(); ann_VkTensorCreateInfoARM->mlib = nullptr;
#endif
#if defined(VK_EXT_descriptor_heap)
    ann_VkTensorViewCreateInfoARM->mlib = &lib; ann_VkTensorViewCreateInfoARM->init(); ann_VkTensorViewCreateInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkTensorMemoryRequirementsInfoARM->mlib = &lib; ann_VkTensorMemoryRequirementsInfoARM->init(); ann_VkTensorMemoryRequirementsInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkBindTensorMemoryInfoARM->mlib = &lib; ann_VkBindTensorMemoryInfoARM->init(); ann_VkBindTensorMemoryInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkWriteDescriptorSetTensorARM->mlib = &lib; ann_VkWriteDescriptorSetTensorARM->init(); ann_VkWriteDescriptorSetTensorARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkTensorFormatPropertiesARM->mlib = &lib; ann_VkTensorFormatPropertiesARM->init(); ann_VkTensorFormatPropertiesARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkPhysicalDeviceTensorPropertiesARM->mlib = &lib; ann_VkPhysicalDeviceTensorPropertiesARM->init(); ann_VkPhysicalDeviceTensorPropertiesARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkTensorMemoryBarrierARM->mlib = &lib; ann_VkTensorMemoryBarrierARM->init(); ann_VkTensorMemoryBarrierARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkTensorDependencyInfoARM->mlib = &lib; ann_VkTensorDependencyInfoARM->init(); ann_VkTensorDependencyInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkPhysicalDeviceTensorFeaturesARM->mlib = &lib; ann_VkPhysicalDeviceTensorFeaturesARM->init(); ann_VkPhysicalDeviceTensorFeaturesARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkDeviceTensorMemoryRequirementsARM->mlib = &lib; ann_VkDeviceTensorMemoryRequirementsARM->init(); ann_VkDeviceTensorMemoryRequirementsARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkCopyTensorInfoARM->mlib = &lib; ann_VkCopyTensorInfoARM->init(); ann_VkCopyTensorInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkTensorCopyARM->mlib = &lib; ann_VkTensorCopyARM->init(); ann_VkTensorCopyARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkMemoryDedicatedAllocateInfoTensorARM->mlib = &lib; ann_VkMemoryDedicatedAllocateInfoTensorARM->init(); ann_VkMemoryDedicatedAllocateInfoTensorARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkPhysicalDeviceDescriptorBufferTensorPropertiesARM->mlib = &lib; ann_VkPhysicalDeviceDescriptorBufferTensorPropertiesARM->init(); ann_VkPhysicalDeviceDescriptorBufferTensorPropertiesARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkPhysicalDeviceDescriptorBufferTensorFeaturesARM->mlib = &lib; ann_VkPhysicalDeviceDescriptorBufferTensorFeaturesARM->init(); ann_VkPhysicalDeviceDescriptorBufferTensorFeaturesARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkTensorCaptureDescriptorDataInfoARM->mlib = &lib; ann_VkTensorCaptureDescriptorDataInfoARM->init(); ann_VkTensorCaptureDescriptorDataInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkTensorViewCaptureDescriptorDataInfoARM->mlib = &lib; ann_VkTensorViewCaptureDescriptorDataInfoARM->init(); ann_VkTensorViewCaptureDescriptorDataInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkDescriptorGetTensorInfoARM->mlib = &lib; ann_VkDescriptorGetTensorInfoARM->init(); ann_VkDescriptorGetTensorInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkFrameBoundaryTensorsARM->mlib = &lib; ann_VkFrameBoundaryTensorsARM->init(); ann_VkFrameBoundaryTensorsARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkPhysicalDeviceExternalTensorInfoARM->mlib = &lib; ann_VkPhysicalDeviceExternalTensorInfoARM->init(); ann_VkPhysicalDeviceExternalTensorInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkExternalTensorPropertiesARM->mlib = &lib; ann_VkExternalTensorPropertiesARM->init(); ann_VkExternalTensorPropertiesARM->mlib = nullptr;
#endif
#if defined(VK_ARM_tensors)
    ann_VkExternalMemoryTensorCreateInfoARM->mlib = &lib; ann_VkExternalMemoryTensorCreateInfoARM->init(); ann_VkExternalMemoryTensorCreateInfoARM->mlib = nullptr;
#endif
#if defined(VK_EXT_shader_float8)
    ann_VkPhysicalDeviceShaderFloat8FeaturesEXT->mlib = &lib; ann_VkPhysicalDeviceShaderFloat8FeaturesEXT->init(); ann_VkPhysicalDeviceShaderFloat8FeaturesEXT->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkPhysicalDeviceDataGraphFeaturesARM->mlib = &lib; ann_VkPhysicalDeviceDataGraphFeaturesARM->init(); ann_VkPhysicalDeviceDataGraphFeaturesARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineConstantTensorSemiStructuredSparsityInfoARM->mlib = &lib; ann_VkDataGraphPipelineConstantTensorSemiStructuredSparsityInfoARM->init(); ann_VkDataGraphPipelineConstantTensorSemiStructuredSparsityInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineConstantARM->mlib = &lib; ann_VkDataGraphPipelineConstantARM->init(); ann_VkDataGraphPipelineConstantARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineResourceInfoARM->mlib = &lib; ann_VkDataGraphPipelineResourceInfoARM->init(); ann_VkDataGraphPipelineResourceInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph_optical_flow)
    ann_VkDataGraphPipelineResourceInfoImageLayoutARM->mlib = &lib; ann_VkDataGraphPipelineResourceInfoImageLayoutARM->init(); ann_VkDataGraphPipelineResourceInfoImageLayoutARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineCompilerControlCreateInfoARM->mlib = &lib; ann_VkDataGraphPipelineCompilerControlCreateInfoARM->init(); ann_VkDataGraphPipelineCompilerControlCreateInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineCreateInfoARM->mlib = &lib; ann_VkDataGraphPipelineCreateInfoARM->init(); ann_VkDataGraphPipelineCreateInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineShaderModuleCreateInfoARM->mlib = &lib; ann_VkDataGraphPipelineShaderModuleCreateInfoARM->init(); ann_VkDataGraphPipelineShaderModuleCreateInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineSessionCreateInfoARM->mlib = &lib; ann_VkDataGraphPipelineSessionCreateInfoARM->init(); ann_VkDataGraphPipelineSessionCreateInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineSessionBindPointRequirementsInfoARM->mlib = &lib; ann_VkDataGraphPipelineSessionBindPointRequirementsInfoARM->init(); ann_VkDataGraphPipelineSessionBindPointRequirementsInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineSessionBindPointRequirementARM->mlib = &lib; ann_VkDataGraphPipelineSessionBindPointRequirementARM->init(); ann_VkDataGraphPipelineSessionBindPointRequirementARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineSessionMemoryRequirementsInfoARM->mlib = &lib; ann_VkDataGraphPipelineSessionMemoryRequirementsInfoARM->init(); ann_VkDataGraphPipelineSessionMemoryRequirementsInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkBindDataGraphPipelineSessionMemoryInfoARM->mlib = &lib; ann_VkBindDataGraphPipelineSessionMemoryInfoARM->init(); ann_VkBindDataGraphPipelineSessionMemoryInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineInfoARM->mlib = &lib; ann_VkDataGraphPipelineInfoARM->init(); ann_VkDataGraphPipelineInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelinePropertyQueryResultARM->mlib = &lib; ann_VkDataGraphPipelinePropertyQueryResultARM->init(); ann_VkDataGraphPipelinePropertyQueryResultARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineIdentifierCreateInfoARM->mlib = &lib; ann_VkDataGraphPipelineIdentifierCreateInfoARM->init(); ann_VkDataGraphPipelineIdentifierCreateInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphPipelineDispatchInfoARM->mlib = &lib; ann_VkDataGraphPipelineDispatchInfoARM->init(); ann_VkDataGraphPipelineDispatchInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkPhysicalDeviceDataGraphProcessingEngineARM->mlib = &lib; ann_VkPhysicalDeviceDataGraphProcessingEngineARM->init(); ann_VkPhysicalDeviceDataGraphProcessingEngineARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkPhysicalDeviceDataGraphOperationSupportARM->mlib = &lib; ann_VkPhysicalDeviceDataGraphOperationSupportARM->init(); ann_VkPhysicalDeviceDataGraphOperationSupportARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkQueueFamilyDataGraphPropertiesARM->mlib = &lib; ann_VkQueueFamilyDataGraphPropertiesARM->init(); ann_VkQueueFamilyDataGraphPropertiesARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkPhysicalDeviceQueueFamilyDataGraphProcessingEngineInfoARM->mlib = &lib; ann_VkPhysicalDeviceQueueFamilyDataGraphProcessingEngineInfoARM->init(); ann_VkPhysicalDeviceQueueFamilyDataGraphProcessingEngineInfoARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkQueueFamilyDataGraphProcessingEnginePropertiesARM->mlib = &lib; ann_VkQueueFamilyDataGraphProcessingEnginePropertiesARM->init(); ann_VkQueueFamilyDataGraphProcessingEnginePropertiesARM->mlib = nullptr;
#endif
#if defined(VK_ARM_data_graph)
    ann_VkDataGraphProcessingEngineCreateInfoARM->mlib = &lib; ann_VkDataGraphProcessingEngineCreateInfoARM->init(); ann_VkDataGraphProcessingEngineCreateInfoARM->mlib = nullptr;
#endif
#if defined(VK_SEC_pipeline_cache_incremental_mode)
    ann_VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC->mlib = &lib; ann_VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC->init(); ann_VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC->mlib = nullptr;
#endif
}

}
