// generated by generator/generate.das -- DO NOT EDIT

#include "dasVULKAN.h"

namespace das {

#if defined(VK_EXT_vertex_input_dynamic_state)
struct VkVertexInputAttributeDescription2EXT_Ann : ManagedStructureAnnotation<VkVertexInputAttributeDescription2EXT> {
    VkVertexInputAttributeDescription2EXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkVertexInputAttributeDescription2EXT", ml, "VkVertexInputAttributeDescription2EXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkVertexInputAttributeDescription2EXT_Ann * ann_VkVertexInputAttributeDescription2EXT = nullptr;
void VkVertexInputAttributeDescription2EXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkVertexInputAttributeDescription2EXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(location)>("location", "location");
    addField<DAS_BIND_MANAGED_FIELD(binding)>("binding", "binding");
    addField<DAS_BIND_MANAGED_FIELD(format)>("format", "format");
    addField<DAS_BIND_MANAGED_FIELD(offset)>("offset", "offset");
}
#endif

#if defined(VK_EXT_color_write_enable)
struct VkPhysicalDeviceColorWriteEnableFeaturesEXT_Ann : ManagedStructureAnnotation<VkPhysicalDeviceColorWriteEnableFeaturesEXT> {
    VkPhysicalDeviceColorWriteEnableFeaturesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceColorWriteEnableFeaturesEXT", ml, "VkPhysicalDeviceColorWriteEnableFeaturesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceColorWriteEnableFeaturesEXT_Ann * ann_VkPhysicalDeviceColorWriteEnableFeaturesEXT = nullptr;
void VkPhysicalDeviceColorWriteEnableFeaturesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceColorWriteEnableFeaturesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(colorWriteEnable)>("colorWriteEnable", "colorWriteEnable");
}
#endif

#if defined(VK_EXT_color_write_enable)
struct VkPipelineColorWriteCreateInfoEXT_Ann : ManagedStructureAnnotation<VkPipelineColorWriteCreateInfoEXT> {
    VkPipelineColorWriteCreateInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPipelineColorWriteCreateInfoEXT", ml, "VkPipelineColorWriteCreateInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPipelineColorWriteCreateInfoEXT_Ann * ann_VkPipelineColorWriteCreateInfoEXT = nullptr;
void VkPipelineColorWriteCreateInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPipelineColorWriteCreateInfoEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(attachmentCount)>("attachmentCount", "attachmentCount");
    addFieldEx("pColorWriteEnables", "pColorWriteEnables", offsetof(VkPipelineColorWriteCreateInfoEXT, pColorWriteEnables), makeType<VkBool32 *>(*mlib));
}
#endif

#if defined(VK_VERSION_1_3)
struct VkMemoryBarrier2_Ann : ManagedStructureAnnotation<VkMemoryBarrier2> {
    VkMemoryBarrier2_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkMemoryBarrier2", ml, "VkMemoryBarrier2") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkMemoryBarrier2_Ann * ann_VkMemoryBarrier2 = nullptr;
void VkMemoryBarrier2_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkMemoryBarrier2, pNext), makeType<void *>(*mlib));
    addFieldEx("srcStageMask", "srcStageMask", offsetof(VkMemoryBarrier2, srcStageMask), makeVkFlags_VkPipelineStageFlags2());
    addFieldEx("srcAccessMask", "srcAccessMask", offsetof(VkMemoryBarrier2, srcAccessMask), makeVkFlags_VkAccessFlags2());
    addFieldEx("dstStageMask", "dstStageMask", offsetof(VkMemoryBarrier2, dstStageMask), makeVkFlags_VkPipelineStageFlags2());
    addFieldEx("dstAccessMask", "dstAccessMask", offsetof(VkMemoryBarrier2, dstAccessMask), makeVkFlags_VkAccessFlags2());
}
#endif

#if defined(VK_VERSION_1_3)
struct VkImageMemoryBarrier2_Ann : ManagedStructureAnnotation<VkImageMemoryBarrier2> {
    VkImageMemoryBarrier2_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkImageMemoryBarrier2", ml, "VkImageMemoryBarrier2") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkImageMemoryBarrier2_Ann * ann_VkImageMemoryBarrier2 = nullptr;
void VkImageMemoryBarrier2_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkImageMemoryBarrier2, pNext), makeType<void *>(*mlib));
    addFieldEx("srcStageMask", "srcStageMask", offsetof(VkImageMemoryBarrier2, srcStageMask), makeVkFlags_VkPipelineStageFlags2());
    addFieldEx("srcAccessMask", "srcAccessMask", offsetof(VkImageMemoryBarrier2, srcAccessMask), makeVkFlags_VkAccessFlags2());
    addFieldEx("dstStageMask", "dstStageMask", offsetof(VkImageMemoryBarrier2, dstStageMask), makeVkFlags_VkPipelineStageFlags2());
    addFieldEx("dstAccessMask", "dstAccessMask", offsetof(VkImageMemoryBarrier2, dstAccessMask), makeVkFlags_VkAccessFlags2());
    addField<DAS_BIND_MANAGED_FIELD(oldLayout)>("oldLayout", "oldLayout");
    addField<DAS_BIND_MANAGED_FIELD(newLayout)>("newLayout", "newLayout");
    addField<DAS_BIND_MANAGED_FIELD(srcQueueFamilyIndex)>("srcQueueFamilyIndex", "srcQueueFamilyIndex");
    addField<DAS_BIND_MANAGED_FIELD(dstQueueFamilyIndex)>("dstQueueFamilyIndex", "dstQueueFamilyIndex");
    addField<DAS_BIND_MANAGED_FIELD(image)>("image", "image");
    addField<DAS_BIND_MANAGED_FIELD(subresourceRange)>("subresourceRange", "subresourceRange");
}
#endif

#if defined(VK_VERSION_1_3)
struct VkBufferMemoryBarrier2_Ann : ManagedStructureAnnotation<VkBufferMemoryBarrier2> {
    VkBufferMemoryBarrier2_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkBufferMemoryBarrier2", ml, "VkBufferMemoryBarrier2") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkBufferMemoryBarrier2_Ann * ann_VkBufferMemoryBarrier2 = nullptr;
void VkBufferMemoryBarrier2_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkBufferMemoryBarrier2, pNext), makeType<void *>(*mlib));
    addFieldEx("srcStageMask", "srcStageMask", offsetof(VkBufferMemoryBarrier2, srcStageMask), makeVkFlags_VkPipelineStageFlags2());
    addFieldEx("srcAccessMask", "srcAccessMask", offsetof(VkBufferMemoryBarrier2, srcAccessMask), makeVkFlags_VkAccessFlags2());
    addFieldEx("dstStageMask", "dstStageMask", offsetof(VkBufferMemoryBarrier2, dstStageMask), makeVkFlags_VkPipelineStageFlags2());
    addFieldEx("dstAccessMask", "dstAccessMask", offsetof(VkBufferMemoryBarrier2, dstAccessMask), makeVkFlags_VkAccessFlags2());
    addField<DAS_BIND_MANAGED_FIELD(srcQueueFamilyIndex)>("srcQueueFamilyIndex", "srcQueueFamilyIndex");
    addField<DAS_BIND_MANAGED_FIELD(dstQueueFamilyIndex)>("dstQueueFamilyIndex", "dstQueueFamilyIndex");
    addField<DAS_BIND_MANAGED_FIELD(buffer)>("buffer", "buffer");
    addField<DAS_BIND_MANAGED_FIELD(offset)>("offset", "offset");
    addField<DAS_BIND_MANAGED_FIELD(size)>("size", "size");
}
#endif

#if defined(VK_KHR_maintenance8)
struct VkMemoryBarrierAccessFlags3KHR_Ann : ManagedStructureAnnotation<VkMemoryBarrierAccessFlags3KHR> {
    VkMemoryBarrierAccessFlags3KHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkMemoryBarrierAccessFlags3KHR", ml, "VkMemoryBarrierAccessFlags3KHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkMemoryBarrierAccessFlags3KHR_Ann * ann_VkMemoryBarrierAccessFlags3KHR = nullptr;
void VkMemoryBarrierAccessFlags3KHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkMemoryBarrierAccessFlags3KHR, pNext), makeType<void *>(*mlib));
    addFieldEx("srcAccessMask3", "srcAccessMask3", offsetof(VkMemoryBarrierAccessFlags3KHR, srcAccessMask3), makeVkFlags_VkAccessFlags3KHR());
    addFieldEx("dstAccessMask3", "dstAccessMask3", offsetof(VkMemoryBarrierAccessFlags3KHR, dstAccessMask3), makeVkFlags_VkAccessFlags3KHR());
}
#endif

#if defined(VK_VERSION_1_3)
struct VkDependencyInfo_Ann : ManagedStructureAnnotation<VkDependencyInfo> {
    VkDependencyInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkDependencyInfo", ml, "VkDependencyInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkDependencyInfo_Ann * ann_VkDependencyInfo = nullptr;
void VkDependencyInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkDependencyInfo, pNext), makeType<void *>(*mlib));
    addFieldEx("dependencyFlags", "dependencyFlags", offsetof(VkDependencyInfo, dependencyFlags), makeVkFlags_VkDependencyFlags());
    addField<DAS_BIND_MANAGED_FIELD(memoryBarrierCount)>("memoryBarrierCount", "memoryBarrierCount");
    addFieldEx("pMemoryBarriers", "pMemoryBarriers", offsetof(VkDependencyInfo, pMemoryBarriers), makeType<VkMemoryBarrier2 *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(bufferMemoryBarrierCount)>("bufferMemoryBarrierCount", "bufferMemoryBarrierCount");
    addFieldEx("pBufferMemoryBarriers", "pBufferMemoryBarriers", offsetof(VkDependencyInfo, pBufferMemoryBarriers), makeType<VkBufferMemoryBarrier2 *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(imageMemoryBarrierCount)>("imageMemoryBarrierCount", "imageMemoryBarrierCount");
    addFieldEx("pImageMemoryBarriers", "pImageMemoryBarriers", offsetof(VkDependencyInfo, pImageMemoryBarriers), makeType<VkImageMemoryBarrier2 *>(*mlib));
}
#endif

#if defined(VK_VERSION_1_3)
struct VkSemaphoreSubmitInfo_Ann : ManagedStructureAnnotation<VkSemaphoreSubmitInfo> {
    VkSemaphoreSubmitInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkSemaphoreSubmitInfo", ml, "VkSemaphoreSubmitInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkSemaphoreSubmitInfo_Ann * ann_VkSemaphoreSubmitInfo = nullptr;
void VkSemaphoreSubmitInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkSemaphoreSubmitInfo, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(semaphore)>("semaphore", "semaphore");
    addField<DAS_BIND_MANAGED_FIELD(value)>("value", "value");
    addFieldEx("stageMask", "stageMask", offsetof(VkSemaphoreSubmitInfo, stageMask), makeVkFlags_VkPipelineStageFlags2());
    addField<DAS_BIND_MANAGED_FIELD(deviceIndex)>("deviceIndex", "deviceIndex");
}
#endif

#if defined(VK_VERSION_1_3)
struct VkCommandBufferSubmitInfo_Ann : ManagedStructureAnnotation<VkCommandBufferSubmitInfo> {
    VkCommandBufferSubmitInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkCommandBufferSubmitInfo", ml, "VkCommandBufferSubmitInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkCommandBufferSubmitInfo_Ann * ann_VkCommandBufferSubmitInfo = nullptr;
void VkCommandBufferSubmitInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkCommandBufferSubmitInfo, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(commandBuffer)>("commandBuffer", "commandBuffer");
    addField<DAS_BIND_MANAGED_FIELD(deviceMask)>("deviceMask", "deviceMask");
}
#endif

#if defined(VK_VERSION_1_3)
struct VkSubmitInfo2_Ann : ManagedStructureAnnotation<VkSubmitInfo2> {
    VkSubmitInfo2_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkSubmitInfo2", ml, "VkSubmitInfo2") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkSubmitInfo2_Ann * ann_VkSubmitInfo2 = nullptr;
void VkSubmitInfo2_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkSubmitInfo2, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkSubmitInfo2, flags), makeVkFlags_VkSubmitFlags());
    addField<DAS_BIND_MANAGED_FIELD(waitSemaphoreInfoCount)>("waitSemaphoreInfoCount", "waitSemaphoreInfoCount");
    addFieldEx("pWaitSemaphoreInfos", "pWaitSemaphoreInfos", offsetof(VkSubmitInfo2, pWaitSemaphoreInfos), makeType<VkSemaphoreSubmitInfo *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(commandBufferInfoCount)>("commandBufferInfoCount", "commandBufferInfoCount");
    addFieldEx("pCommandBufferInfos", "pCommandBufferInfos", offsetof(VkSubmitInfo2, pCommandBufferInfos), makeType<VkCommandBufferSubmitInfo *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(signalSemaphoreInfoCount)>("signalSemaphoreInfoCount", "signalSemaphoreInfoCount");
    addFieldEx("pSignalSemaphoreInfos", "pSignalSemaphoreInfos", offsetof(VkSubmitInfo2, pSignalSemaphoreInfos), makeType<VkSemaphoreSubmitInfo *>(*mlib));
}
#endif

#if defined(VK_NV_device_diagnostic_checkpoints)
struct VkQueueFamilyCheckpointProperties2NV_Ann : ManagedStructureAnnotation<VkQueueFamilyCheckpointProperties2NV> {
    VkQueueFamilyCheckpointProperties2NV_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkQueueFamilyCheckpointProperties2NV", ml, "VkQueueFamilyCheckpointProperties2NV") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkQueueFamilyCheckpointProperties2NV_Ann * ann_VkQueueFamilyCheckpointProperties2NV = nullptr;
void VkQueueFamilyCheckpointProperties2NV_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkQueueFamilyCheckpointProperties2NV, pNext), makeType<void *>(*mlib));
    addFieldEx("checkpointExecutionStageMask", "checkpointExecutionStageMask", offsetof(VkQueueFamilyCheckpointProperties2NV, checkpointExecutionStageMask), makeVkFlags_VkPipelineStageFlags2());
}
#endif

#if defined(VK_NV_device_diagnostic_checkpoints)
struct VkCheckpointData2NV_Ann : ManagedStructureAnnotation<VkCheckpointData2NV> {
    VkCheckpointData2NV_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkCheckpointData2NV", ml, "VkCheckpointData2NV") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkCheckpointData2NV_Ann * ann_VkCheckpointData2NV = nullptr;
void VkCheckpointData2NV_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkCheckpointData2NV, pNext), makeType<void *>(*mlib));
    addFieldEx("stage", "stage", offsetof(VkCheckpointData2NV, stage), makeVkFlags_VkPipelineStageFlags2());
    addFieldEx("pCheckpointMarker", "pCheckpointMarker", offsetof(VkCheckpointData2NV, pCheckpointMarker), makeType<void *>(*mlib));
}
#endif

#if defined(VK_VERSION_1_3)
struct VkPhysicalDeviceSynchronization2Features_Ann : ManagedStructureAnnotation<VkPhysicalDeviceSynchronization2Features> {
    VkPhysicalDeviceSynchronization2Features_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceSynchronization2Features", ml, "VkPhysicalDeviceSynchronization2Features") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceSynchronization2Features_Ann * ann_VkPhysicalDeviceSynchronization2Features = nullptr;
void VkPhysicalDeviceSynchronization2Features_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceSynchronization2Features, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(synchronization2)>("synchronization2", "synchronization2");
}
#endif

#if defined(VK_KHR_unified_image_layouts)
struct VkPhysicalDeviceUnifiedImageLayoutsFeaturesKHR_Ann : ManagedStructureAnnotation<VkPhysicalDeviceUnifiedImageLayoutsFeaturesKHR> {
    VkPhysicalDeviceUnifiedImageLayoutsFeaturesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceUnifiedImageLayoutsFeaturesKHR", ml, "VkPhysicalDeviceUnifiedImageLayoutsFeaturesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceUnifiedImageLayoutsFeaturesKHR_Ann * ann_VkPhysicalDeviceUnifiedImageLayoutsFeaturesKHR = nullptr;
void VkPhysicalDeviceUnifiedImageLayoutsFeaturesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceUnifiedImageLayoutsFeaturesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(unifiedImageLayouts)>("unifiedImageLayouts", "unifiedImageLayouts");
    addField<DAS_BIND_MANAGED_FIELD(unifiedImageLayoutsVideo)>("unifiedImageLayoutsVideo", "unifiedImageLayoutsVideo");
}
#endif

#if defined(VK_VERSION_1_4)
struct VkPhysicalDeviceHostImageCopyFeatures_Ann : ManagedStructureAnnotation<VkPhysicalDeviceHostImageCopyFeatures> {
    VkPhysicalDeviceHostImageCopyFeatures_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceHostImageCopyFeatures", ml, "VkPhysicalDeviceHostImageCopyFeatures") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceHostImageCopyFeatures_Ann * ann_VkPhysicalDeviceHostImageCopyFeatures = nullptr;
void VkPhysicalDeviceHostImageCopyFeatures_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceHostImageCopyFeatures, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(hostImageCopy)>("hostImageCopy", "hostImageCopy");
}
#endif

#if defined(VK_VERSION_1_4)
struct VkPhysicalDeviceHostImageCopyProperties_Ann : ManagedStructureAnnotation<VkPhysicalDeviceHostImageCopyProperties> {
    VkPhysicalDeviceHostImageCopyProperties_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceHostImageCopyProperties", ml, "VkPhysicalDeviceHostImageCopyProperties") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceHostImageCopyProperties_Ann * ann_VkPhysicalDeviceHostImageCopyProperties = nullptr;
void VkPhysicalDeviceHostImageCopyProperties_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceHostImageCopyProperties, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(copySrcLayoutCount)>("copySrcLayoutCount", "copySrcLayoutCount");
    addFieldEx("pCopySrcLayouts", "pCopySrcLayouts", offsetof(VkPhysicalDeviceHostImageCopyProperties, pCopySrcLayouts), makeType<VkImageLayout *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(copyDstLayoutCount)>("copyDstLayoutCount", "copyDstLayoutCount");
    addFieldEx("pCopyDstLayouts", "pCopyDstLayouts", offsetof(VkPhysicalDeviceHostImageCopyProperties, pCopyDstLayouts), makeType<VkImageLayout *>(*mlib));
    addFieldEx("optimalTilingLayoutUUID", "optimalTilingLayoutUUID", offsetof(VkPhysicalDeviceHostImageCopyProperties, optimalTilingLayoutUUID), makeFixedArrayTypeDecl(int32_t(VK_UUID_SIZE), makeType<uint8_t>(*mlib)));
    addField<DAS_BIND_MANAGED_FIELD(identicalMemoryTypeRequirements)>("identicalMemoryTypeRequirements", "identicalMemoryTypeRequirements");
}
#endif

#if defined(VK_VERSION_1_4)
struct VkMemoryToImageCopy_Ann : ManagedStructureAnnotation<VkMemoryToImageCopy> {
    VkMemoryToImageCopy_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkMemoryToImageCopy", ml, "VkMemoryToImageCopy") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkMemoryToImageCopy_Ann * ann_VkMemoryToImageCopy = nullptr;
void VkMemoryToImageCopy_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkMemoryToImageCopy, pNext), makeType<void *>(*mlib));
    addFieldEx("pHostPointer", "pHostPointer", offsetof(VkMemoryToImageCopy, pHostPointer), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(memoryRowLength)>("memoryRowLength", "memoryRowLength");
    addField<DAS_BIND_MANAGED_FIELD(memoryImageHeight)>("memoryImageHeight", "memoryImageHeight");
    addField<DAS_BIND_MANAGED_FIELD(imageSubresource)>("imageSubresource", "imageSubresource");
    addField<DAS_BIND_MANAGED_FIELD(imageOffset)>("imageOffset", "imageOffset");
    addField<DAS_BIND_MANAGED_FIELD(imageExtent)>("imageExtent", "imageExtent");
}
#endif

#if defined(VK_VERSION_1_4)
struct VkImageToMemoryCopy_Ann : ManagedStructureAnnotation<VkImageToMemoryCopy> {
    VkImageToMemoryCopy_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkImageToMemoryCopy", ml, "VkImageToMemoryCopy") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkImageToMemoryCopy_Ann * ann_VkImageToMemoryCopy = nullptr;
void VkImageToMemoryCopy_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkImageToMemoryCopy, pNext), makeType<void *>(*mlib));
    addFieldEx("pHostPointer", "pHostPointer", offsetof(VkImageToMemoryCopy, pHostPointer), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(memoryRowLength)>("memoryRowLength", "memoryRowLength");
    addField<DAS_BIND_MANAGED_FIELD(memoryImageHeight)>("memoryImageHeight", "memoryImageHeight");
    addField<DAS_BIND_MANAGED_FIELD(imageSubresource)>("imageSubresource", "imageSubresource");
    addField<DAS_BIND_MANAGED_FIELD(imageOffset)>("imageOffset", "imageOffset");
    addField<DAS_BIND_MANAGED_FIELD(imageExtent)>("imageExtent", "imageExtent");
}
#endif

#if defined(VK_VERSION_1_4)
struct VkCopyMemoryToImageInfo_Ann : ManagedStructureAnnotation<VkCopyMemoryToImageInfo> {
    VkCopyMemoryToImageInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkCopyMemoryToImageInfo", ml, "VkCopyMemoryToImageInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkCopyMemoryToImageInfo_Ann * ann_VkCopyMemoryToImageInfo = nullptr;
void VkCopyMemoryToImageInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkCopyMemoryToImageInfo, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkCopyMemoryToImageInfo, flags), makeVkFlags_VkHostImageCopyFlags());
    addField<DAS_BIND_MANAGED_FIELD(dstImage)>("dstImage", "dstImage");
    addField<DAS_BIND_MANAGED_FIELD(dstImageLayout)>("dstImageLayout", "dstImageLayout");
    addField<DAS_BIND_MANAGED_FIELD(regionCount)>("regionCount", "regionCount");
    addFieldEx("pRegions", "pRegions", offsetof(VkCopyMemoryToImageInfo, pRegions), makeType<VkMemoryToImageCopy *>(*mlib));
}
#endif

#if defined(VK_VERSION_1_4)
struct VkCopyImageToMemoryInfo_Ann : ManagedStructureAnnotation<VkCopyImageToMemoryInfo> {
    VkCopyImageToMemoryInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkCopyImageToMemoryInfo", ml, "VkCopyImageToMemoryInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkCopyImageToMemoryInfo_Ann * ann_VkCopyImageToMemoryInfo = nullptr;
void VkCopyImageToMemoryInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkCopyImageToMemoryInfo, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkCopyImageToMemoryInfo, flags), makeVkFlags_VkHostImageCopyFlags());
    addField<DAS_BIND_MANAGED_FIELD(srcImage)>("srcImage", "srcImage");
    addField<DAS_BIND_MANAGED_FIELD(srcImageLayout)>("srcImageLayout", "srcImageLayout");
    addField<DAS_BIND_MANAGED_FIELD(regionCount)>("regionCount", "regionCount");
    addFieldEx("pRegions", "pRegions", offsetof(VkCopyImageToMemoryInfo, pRegions), makeType<VkImageToMemoryCopy *>(*mlib));
}
#endif

#if defined(VK_VERSION_1_4)
struct VkCopyImageToImageInfo_Ann : ManagedStructureAnnotation<VkCopyImageToImageInfo> {
    VkCopyImageToImageInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkCopyImageToImageInfo", ml, "VkCopyImageToImageInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkCopyImageToImageInfo_Ann * ann_VkCopyImageToImageInfo = nullptr;
void VkCopyImageToImageInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkCopyImageToImageInfo, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkCopyImageToImageInfo, flags), makeVkFlags_VkHostImageCopyFlags());
    addField<DAS_BIND_MANAGED_FIELD(srcImage)>("srcImage", "srcImage");
    addField<DAS_BIND_MANAGED_FIELD(srcImageLayout)>("srcImageLayout", "srcImageLayout");
    addField<DAS_BIND_MANAGED_FIELD(dstImage)>("dstImage", "dstImage");
    addField<DAS_BIND_MANAGED_FIELD(dstImageLayout)>("dstImageLayout", "dstImageLayout");
    addField<DAS_BIND_MANAGED_FIELD(regionCount)>("regionCount", "regionCount");
    addFieldEx("pRegions", "pRegions", offsetof(VkCopyImageToImageInfo, pRegions), makeType<VkImageCopy2 *>(*mlib));
}
#endif

#if defined(VK_VERSION_1_4)
struct VkHostImageLayoutTransitionInfo_Ann : ManagedStructureAnnotation<VkHostImageLayoutTransitionInfo> {
    VkHostImageLayoutTransitionInfo_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkHostImageLayoutTransitionInfo", ml, "VkHostImageLayoutTransitionInfo") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkHostImageLayoutTransitionInfo_Ann * ann_VkHostImageLayoutTransitionInfo = nullptr;
void VkHostImageLayoutTransitionInfo_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkHostImageLayoutTransitionInfo, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(image)>("image", "image");
    addField<DAS_BIND_MANAGED_FIELD(oldLayout)>("oldLayout", "oldLayout");
    addField<DAS_BIND_MANAGED_FIELD(newLayout)>("newLayout", "newLayout");
    addField<DAS_BIND_MANAGED_FIELD(subresourceRange)>("subresourceRange", "subresourceRange");
}
#endif

#if defined(VK_VERSION_1_4)
struct VkSubresourceHostMemcpySize_Ann : ManagedStructureAnnotation<VkSubresourceHostMemcpySize> {
    VkSubresourceHostMemcpySize_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkSubresourceHostMemcpySize", ml, "VkSubresourceHostMemcpySize") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkSubresourceHostMemcpySize_Ann * ann_VkSubresourceHostMemcpySize = nullptr;
void VkSubresourceHostMemcpySize_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkSubresourceHostMemcpySize, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(size)>("size", "size");
}
#endif

#if defined(VK_VERSION_1_4)
struct VkHostImageCopyDevicePerformanceQuery_Ann : ManagedStructureAnnotation<VkHostImageCopyDevicePerformanceQuery> {
    VkHostImageCopyDevicePerformanceQuery_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkHostImageCopyDevicePerformanceQuery", ml, "VkHostImageCopyDevicePerformanceQuery") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkHostImageCopyDevicePerformanceQuery_Ann * ann_VkHostImageCopyDevicePerformanceQuery = nullptr;
void VkHostImageCopyDevicePerformanceQuery_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkHostImageCopyDevicePerformanceQuery, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(optimalDeviceAccess)>("optimalDeviceAccess", "optimalDeviceAccess");
    addField<DAS_BIND_MANAGED_FIELD(identicalMemoryLayout)>("identicalMemoryLayout", "identicalMemoryLayout");
}
#endif

#if defined(VK_EXT_primitives_generated_query)
struct VkPhysicalDevicePrimitivesGeneratedQueryFeaturesEXT_Ann : ManagedStructureAnnotation<VkPhysicalDevicePrimitivesGeneratedQueryFeaturesEXT> {
    VkPhysicalDevicePrimitivesGeneratedQueryFeaturesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDevicePrimitivesGeneratedQueryFeaturesEXT", ml, "VkPhysicalDevicePrimitivesGeneratedQueryFeaturesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDevicePrimitivesGeneratedQueryFeaturesEXT_Ann * ann_VkPhysicalDevicePrimitivesGeneratedQueryFeaturesEXT = nullptr;
void VkPhysicalDevicePrimitivesGeneratedQueryFeaturesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDevicePrimitivesGeneratedQueryFeaturesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(primitivesGeneratedQuery)>("primitivesGeneratedQuery", "primitivesGeneratedQuery");
    addField<DAS_BIND_MANAGED_FIELD(primitivesGeneratedQueryWithRasterizerDiscard)>("primitivesGeneratedQueryWithRasterizerDiscard", "primitivesGeneratedQueryWithRasterizerDiscard");
    addField<DAS_BIND_MANAGED_FIELD(primitivesGeneratedQueryWithNonZeroStreams)>("primitivesGeneratedQueryWithNonZeroStreams", "primitivesGeneratedQueryWithNonZeroStreams");
}
#endif

#if defined(VK_EXT_legacy_dithering)
struct VkPhysicalDeviceLegacyDitheringFeaturesEXT_Ann : ManagedStructureAnnotation<VkPhysicalDeviceLegacyDitheringFeaturesEXT> {
    VkPhysicalDeviceLegacyDitheringFeaturesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceLegacyDitheringFeaturesEXT", ml, "VkPhysicalDeviceLegacyDitheringFeaturesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceLegacyDitheringFeaturesEXT_Ann * ann_VkPhysicalDeviceLegacyDitheringFeaturesEXT = nullptr;
void VkPhysicalDeviceLegacyDitheringFeaturesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceLegacyDitheringFeaturesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(legacyDithering)>("legacyDithering", "legacyDithering");
}
#endif

#if defined(VK_EXT_multisampled_render_to_single_sampled)
struct VkPhysicalDeviceMultisampledRenderToSingleSampledFeaturesEXT_Ann : ManagedStructureAnnotation<VkPhysicalDeviceMultisampledRenderToSingleSampledFeaturesEXT> {
    VkPhysicalDeviceMultisampledRenderToSingleSampledFeaturesEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceMultisampledRenderToSingleSampledFeaturesEXT", ml, "VkPhysicalDeviceMultisampledRenderToSingleSampledFeaturesEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceMultisampledRenderToSingleSampledFeaturesEXT_Ann * ann_VkPhysicalDeviceMultisampledRenderToSingleSampledFeaturesEXT = nullptr;
void VkPhysicalDeviceMultisampledRenderToSingleSampledFeaturesEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceMultisampledRenderToSingleSampledFeaturesEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(multisampledRenderToSingleSampled)>("multisampledRenderToSingleSampled", "multisampledRenderToSingleSampled");
}
#endif

#if defined(VK_KHR_present_id2)
struct VkSurfaceCapabilitiesPresentId2KHR_Ann : ManagedStructureAnnotation<VkSurfaceCapabilitiesPresentId2KHR> {
    VkSurfaceCapabilitiesPresentId2KHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkSurfaceCapabilitiesPresentId2KHR", ml, "VkSurfaceCapabilitiesPresentId2KHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkSurfaceCapabilitiesPresentId2KHR_Ann * ann_VkSurfaceCapabilitiesPresentId2KHR = nullptr;
void VkSurfaceCapabilitiesPresentId2KHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkSurfaceCapabilitiesPresentId2KHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(presentId2Supported)>("presentId2Supported", "presentId2Supported");
}
#endif

#if defined(VK_KHR_present_wait2)
struct VkSurfaceCapabilitiesPresentWait2KHR_Ann : ManagedStructureAnnotation<VkSurfaceCapabilitiesPresentWait2KHR> {
    VkSurfaceCapabilitiesPresentWait2KHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkSurfaceCapabilitiesPresentWait2KHR", ml, "VkSurfaceCapabilitiesPresentWait2KHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkSurfaceCapabilitiesPresentWait2KHR_Ann * ann_VkSurfaceCapabilitiesPresentWait2KHR = nullptr;
void VkSurfaceCapabilitiesPresentWait2KHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkSurfaceCapabilitiesPresentWait2KHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(presentWait2Supported)>("presentWait2Supported", "presentWait2Supported");
}
#endif

#if defined(VK_EXT_multisampled_render_to_single_sampled)
struct VkSubpassResolvePerformanceQueryEXT_Ann : ManagedStructureAnnotation<VkSubpassResolvePerformanceQueryEXT> {
    VkSubpassResolvePerformanceQueryEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkSubpassResolvePerformanceQueryEXT", ml, "VkSubpassResolvePerformanceQueryEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkSubpassResolvePerformanceQueryEXT_Ann * ann_VkSubpassResolvePerformanceQueryEXT = nullptr;
void VkSubpassResolvePerformanceQueryEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkSubpassResolvePerformanceQueryEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(optimal)>("optimal", "optimal");
}
#endif

#if defined(VK_EXT_multisampled_render_to_single_sampled)
struct VkMultisampledRenderToSingleSampledInfoEXT_Ann : ManagedStructureAnnotation<VkMultisampledRenderToSingleSampledInfoEXT> {
    VkMultisampledRenderToSingleSampledInfoEXT_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkMultisampledRenderToSingleSampledInfoEXT", ml, "VkMultisampledRenderToSingleSampledInfoEXT") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkMultisampledRenderToSingleSampledInfoEXT_Ann * ann_VkMultisampledRenderToSingleSampledInfoEXT = nullptr;
void VkMultisampledRenderToSingleSampledInfoEXT_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkMultisampledRenderToSingleSampledInfoEXT, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(multisampledRenderToSingleSampledEnable)>("multisampledRenderToSingleSampledEnable", "multisampledRenderToSingleSampledEnable");
    addField<DAS_BIND_MANAGED_FIELD(rasterizationSamples)>("rasterizationSamples", "rasterizationSamples");
}
#endif

#if defined(VK_VERSION_1_4)
struct VkPhysicalDevicePipelineProtectedAccessFeatures_Ann : ManagedStructureAnnotation<VkPhysicalDevicePipelineProtectedAccessFeatures> {
    VkPhysicalDevicePipelineProtectedAccessFeatures_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDevicePipelineProtectedAccessFeatures", ml, "VkPhysicalDevicePipelineProtectedAccessFeatures") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDevicePipelineProtectedAccessFeatures_Ann * ann_VkPhysicalDevicePipelineProtectedAccessFeatures = nullptr;
void VkPhysicalDevicePipelineProtectedAccessFeatures_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDevicePipelineProtectedAccessFeatures, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(pipelineProtectedAccess)>("pipelineProtectedAccess", "pipelineProtectedAccess");
}
#endif

#if defined(VK_KHR_video_queue)
struct VkQueueFamilyVideoPropertiesKHR_Ann : ManagedStructureAnnotation<VkQueueFamilyVideoPropertiesKHR> {
    VkQueueFamilyVideoPropertiesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkQueueFamilyVideoPropertiesKHR", ml, "VkQueueFamilyVideoPropertiesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkQueueFamilyVideoPropertiesKHR_Ann * ann_VkQueueFamilyVideoPropertiesKHR = nullptr;
void VkQueueFamilyVideoPropertiesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkQueueFamilyVideoPropertiesKHR, pNext), makeType<void *>(*mlib));
    addFieldEx("videoCodecOperations", "videoCodecOperations", offsetof(VkQueueFamilyVideoPropertiesKHR, videoCodecOperations), makeVkFlags_VkVideoCodecOperationFlagsKHR());
}
#endif

#if defined(VK_KHR_video_queue)
struct VkQueueFamilyQueryResultStatusPropertiesKHR_Ann : ManagedStructureAnnotation<VkQueueFamilyQueryResultStatusPropertiesKHR> {
    VkQueueFamilyQueryResultStatusPropertiesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkQueueFamilyQueryResultStatusPropertiesKHR", ml, "VkQueueFamilyQueryResultStatusPropertiesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkQueueFamilyQueryResultStatusPropertiesKHR_Ann * ann_VkQueueFamilyQueryResultStatusPropertiesKHR = nullptr;
void VkQueueFamilyQueryResultStatusPropertiesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkQueueFamilyQueryResultStatusPropertiesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(queryResultStatusSupport)>("queryResultStatusSupport", "queryResultStatusSupport");
}
#endif

#if defined(VK_KHR_video_queue)
struct VkVideoProfileListInfoKHR_Ann : ManagedStructureAnnotation<VkVideoProfileListInfoKHR> {
    VkVideoProfileListInfoKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkVideoProfileListInfoKHR", ml, "VkVideoProfileListInfoKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkVideoProfileListInfoKHR_Ann * ann_VkVideoProfileListInfoKHR = nullptr;
void VkVideoProfileListInfoKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkVideoProfileListInfoKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(profileCount)>("profileCount", "profileCount");
    addFieldEx("pProfiles", "pProfiles", offsetof(VkVideoProfileListInfoKHR, pProfiles), makeType<VkVideoProfileInfoKHR *>(*mlib));
}
#endif

#if defined(VK_KHR_video_queue)
struct VkPhysicalDeviceVideoFormatInfoKHR_Ann : ManagedStructureAnnotation<VkPhysicalDeviceVideoFormatInfoKHR> {
    VkPhysicalDeviceVideoFormatInfoKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkPhysicalDeviceVideoFormatInfoKHR", ml, "VkPhysicalDeviceVideoFormatInfoKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkPhysicalDeviceVideoFormatInfoKHR_Ann * ann_VkPhysicalDeviceVideoFormatInfoKHR = nullptr;
void VkPhysicalDeviceVideoFormatInfoKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkPhysicalDeviceVideoFormatInfoKHR, pNext), makeType<void *>(*mlib));
    addFieldEx("imageUsage", "imageUsage", offsetof(VkPhysicalDeviceVideoFormatInfoKHR, imageUsage), makeVkFlags_VkImageUsageFlags());
}
#endif

#if defined(VK_KHR_video_queue)
struct VkVideoFormatPropertiesKHR_Ann : ManagedStructureAnnotation<VkVideoFormatPropertiesKHR> {
    VkVideoFormatPropertiesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkVideoFormatPropertiesKHR", ml, "VkVideoFormatPropertiesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkVideoFormatPropertiesKHR_Ann * ann_VkVideoFormatPropertiesKHR = nullptr;
void VkVideoFormatPropertiesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkVideoFormatPropertiesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(format)>("format", "format");
    addField<DAS_BIND_MANAGED_FIELD(componentMapping)>("componentMapping", "componentMapping");
    addFieldEx("imageCreateFlags", "imageCreateFlags", offsetof(VkVideoFormatPropertiesKHR, imageCreateFlags), makeVkFlags_VkImageCreateFlags());
    addField<DAS_BIND_MANAGED_FIELD(imageType)>("imageType", "imageType");
    addField<DAS_BIND_MANAGED_FIELD(imageTiling)>("imageTiling", "imageTiling");
    addFieldEx("imageUsageFlags", "imageUsageFlags", offsetof(VkVideoFormatPropertiesKHR, imageUsageFlags), makeVkFlags_VkImageUsageFlags());
}
#endif

#if defined(VK_KHR_video_encode_quantization_map)
struct VkVideoEncodeQuantizationMapCapabilitiesKHR_Ann : ManagedStructureAnnotation<VkVideoEncodeQuantizationMapCapabilitiesKHR> {
    VkVideoEncodeQuantizationMapCapabilitiesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkVideoEncodeQuantizationMapCapabilitiesKHR", ml, "VkVideoEncodeQuantizationMapCapabilitiesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkVideoEncodeQuantizationMapCapabilitiesKHR_Ann * ann_VkVideoEncodeQuantizationMapCapabilitiesKHR = nullptr;
void VkVideoEncodeQuantizationMapCapabilitiesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkVideoEncodeQuantizationMapCapabilitiesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(maxQuantizationMapExtent)>("maxQuantizationMapExtent", "maxQuantizationMapExtent");
}
#endif

#if defined(VK_KHR_video_encode_quantization_map)
struct VkVideoEncodeH264QuantizationMapCapabilitiesKHR_Ann : ManagedStructureAnnotation<VkVideoEncodeH264QuantizationMapCapabilitiesKHR> {
    VkVideoEncodeH264QuantizationMapCapabilitiesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkVideoEncodeH264QuantizationMapCapabilitiesKHR", ml, "VkVideoEncodeH264QuantizationMapCapabilitiesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkVideoEncodeH264QuantizationMapCapabilitiesKHR_Ann * ann_VkVideoEncodeH264QuantizationMapCapabilitiesKHR = nullptr;
void VkVideoEncodeH264QuantizationMapCapabilitiesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkVideoEncodeH264QuantizationMapCapabilitiesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(minQpDelta)>("minQpDelta", "minQpDelta");
    addField<DAS_BIND_MANAGED_FIELD(maxQpDelta)>("maxQpDelta", "maxQpDelta");
}
#endif

#if defined(VK_KHR_video_encode_quantization_map)
struct VkVideoEncodeH265QuantizationMapCapabilitiesKHR_Ann : ManagedStructureAnnotation<VkVideoEncodeH265QuantizationMapCapabilitiesKHR> {
    VkVideoEncodeH265QuantizationMapCapabilitiesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkVideoEncodeH265QuantizationMapCapabilitiesKHR", ml, "VkVideoEncodeH265QuantizationMapCapabilitiesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkVideoEncodeH265QuantizationMapCapabilitiesKHR_Ann * ann_VkVideoEncodeH265QuantizationMapCapabilitiesKHR = nullptr;
void VkVideoEncodeH265QuantizationMapCapabilitiesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkVideoEncodeH265QuantizationMapCapabilitiesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(minQpDelta)>("minQpDelta", "minQpDelta");
    addField<DAS_BIND_MANAGED_FIELD(maxQpDelta)>("maxQpDelta", "maxQpDelta");
}
#endif

#if defined(VK_KHR_video_encode_quantization_map)
struct VkVideoEncodeAV1QuantizationMapCapabilitiesKHR_Ann : ManagedStructureAnnotation<VkVideoEncodeAV1QuantizationMapCapabilitiesKHR> {
    VkVideoEncodeAV1QuantizationMapCapabilitiesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkVideoEncodeAV1QuantizationMapCapabilitiesKHR", ml, "VkVideoEncodeAV1QuantizationMapCapabilitiesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkVideoEncodeAV1QuantizationMapCapabilitiesKHR_Ann * ann_VkVideoEncodeAV1QuantizationMapCapabilitiesKHR = nullptr;
void VkVideoEncodeAV1QuantizationMapCapabilitiesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkVideoEncodeAV1QuantizationMapCapabilitiesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(minQIndexDelta)>("minQIndexDelta", "minQIndexDelta");
    addField<DAS_BIND_MANAGED_FIELD(maxQIndexDelta)>("maxQIndexDelta", "maxQIndexDelta");
}
#endif

#if defined(VK_KHR_video_encode_quantization_map)
struct VkVideoFormatQuantizationMapPropertiesKHR_Ann : ManagedStructureAnnotation<VkVideoFormatQuantizationMapPropertiesKHR> {
    VkVideoFormatQuantizationMapPropertiesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkVideoFormatQuantizationMapPropertiesKHR", ml, "VkVideoFormatQuantizationMapPropertiesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkVideoFormatQuantizationMapPropertiesKHR_Ann * ann_VkVideoFormatQuantizationMapPropertiesKHR = nullptr;
void VkVideoFormatQuantizationMapPropertiesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkVideoFormatQuantizationMapPropertiesKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(quantizationMapTexelSize)>("quantizationMapTexelSize", "quantizationMapTexelSize");
}
#endif

#if defined(VK_KHR_video_encode_quantization_map)
struct VkVideoFormatH265QuantizationMapPropertiesKHR_Ann : ManagedStructureAnnotation<VkVideoFormatH265QuantizationMapPropertiesKHR> {
    VkVideoFormatH265QuantizationMapPropertiesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkVideoFormatH265QuantizationMapPropertiesKHR", ml, "VkVideoFormatH265QuantizationMapPropertiesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkVideoFormatH265QuantizationMapPropertiesKHR_Ann * ann_VkVideoFormatH265QuantizationMapPropertiesKHR = nullptr;
void VkVideoFormatH265QuantizationMapPropertiesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkVideoFormatH265QuantizationMapPropertiesKHR, pNext), makeType<void *>(*mlib));
    addFieldEx("compatibleCtbSizes", "compatibleCtbSizes", offsetof(VkVideoFormatH265QuantizationMapPropertiesKHR, compatibleCtbSizes), makeVkFlags_VkVideoEncodeH265CtbSizeFlagsKHR());
}
#endif

#if defined(VK_KHR_video_encode_quantization_map)
struct VkVideoFormatAV1QuantizationMapPropertiesKHR_Ann : ManagedStructureAnnotation<VkVideoFormatAV1QuantizationMapPropertiesKHR> {
    VkVideoFormatAV1QuantizationMapPropertiesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkVideoFormatAV1QuantizationMapPropertiesKHR", ml, "VkVideoFormatAV1QuantizationMapPropertiesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkVideoFormatAV1QuantizationMapPropertiesKHR_Ann * ann_VkVideoFormatAV1QuantizationMapPropertiesKHR = nullptr;
void VkVideoFormatAV1QuantizationMapPropertiesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkVideoFormatAV1QuantizationMapPropertiesKHR, pNext), makeType<void *>(*mlib));
    addFieldEx("compatibleSuperblockSizes", "compatibleSuperblockSizes", offsetof(VkVideoFormatAV1QuantizationMapPropertiesKHR, compatibleSuperblockSizes), makeVkFlags_VkVideoEncodeAV1SuperblockSizeFlagsKHR());
}
#endif

#if defined(VK_KHR_video_queue)
struct VkVideoProfileInfoKHR_Ann : ManagedStructureAnnotation<VkVideoProfileInfoKHR> {
    VkVideoProfileInfoKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkVideoProfileInfoKHR", ml, "VkVideoProfileInfoKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkVideoProfileInfoKHR_Ann * ann_VkVideoProfileInfoKHR = nullptr;
void VkVideoProfileInfoKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkVideoProfileInfoKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(videoCodecOperation)>("videoCodecOperation", "videoCodecOperation");
    addFieldEx("chromaSubsampling", "chromaSubsampling", offsetof(VkVideoProfileInfoKHR, chromaSubsampling), makeVkFlags_VkVideoChromaSubsamplingFlagsKHR());
    addFieldEx("lumaBitDepth", "lumaBitDepth", offsetof(VkVideoProfileInfoKHR, lumaBitDepth), makeVkFlags_VkVideoComponentBitDepthFlagsKHR());
    addFieldEx("chromaBitDepth", "chromaBitDepth", offsetof(VkVideoProfileInfoKHR, chromaBitDepth), makeVkFlags_VkVideoComponentBitDepthFlagsKHR());
}
#endif

#if defined(VK_KHR_video_queue)
struct VkVideoCapabilitiesKHR_Ann : ManagedStructureAnnotation<VkVideoCapabilitiesKHR> {
    VkVideoCapabilitiesKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkVideoCapabilitiesKHR", ml, "VkVideoCapabilitiesKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkVideoCapabilitiesKHR_Ann * ann_VkVideoCapabilitiesKHR = nullptr;
void VkVideoCapabilitiesKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkVideoCapabilitiesKHR, pNext), makeType<void *>(*mlib));
    addFieldEx("flags", "flags", offsetof(VkVideoCapabilitiesKHR, flags), makeVkFlags_VkVideoCapabilityFlagsKHR());
    addField<DAS_BIND_MANAGED_FIELD(minBitstreamBufferOffsetAlignment)>("minBitstreamBufferOffsetAlignment", "minBitstreamBufferOffsetAlignment");
    addField<DAS_BIND_MANAGED_FIELD(minBitstreamBufferSizeAlignment)>("minBitstreamBufferSizeAlignment", "minBitstreamBufferSizeAlignment");
    addField<DAS_BIND_MANAGED_FIELD(pictureAccessGranularity)>("pictureAccessGranularity", "pictureAccessGranularity");
    addField<DAS_BIND_MANAGED_FIELD(minCodedExtent)>("minCodedExtent", "minCodedExtent");
    addField<DAS_BIND_MANAGED_FIELD(maxCodedExtent)>("maxCodedExtent", "maxCodedExtent");
    addField<DAS_BIND_MANAGED_FIELD(maxDpbSlots)>("maxDpbSlots", "maxDpbSlots");
    addField<DAS_BIND_MANAGED_FIELD(maxActiveReferencePictures)>("maxActiveReferencePictures", "maxActiveReferencePictures");
    addField<DAS_BIND_MANAGED_FIELD(stdHeaderVersion)>("stdHeaderVersion", "stdHeaderVersion");
}
#endif

#if defined(VK_KHR_video_queue)
struct VkVideoSessionMemoryRequirementsKHR_Ann : ManagedStructureAnnotation<VkVideoSessionMemoryRequirementsKHR> {
    VkVideoSessionMemoryRequirementsKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkVideoSessionMemoryRequirementsKHR", ml, "VkVideoSessionMemoryRequirementsKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkVideoSessionMemoryRequirementsKHR_Ann * ann_VkVideoSessionMemoryRequirementsKHR = nullptr;
void VkVideoSessionMemoryRequirementsKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkVideoSessionMemoryRequirementsKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(memoryBindIndex)>("memoryBindIndex", "memoryBindIndex");
    addField<DAS_BIND_MANAGED_FIELD(memoryRequirements)>("memoryRequirements", "memoryRequirements");
}
#endif

#if defined(VK_KHR_video_queue)
struct VkBindVideoSessionMemoryInfoKHR_Ann : ManagedStructureAnnotation<VkBindVideoSessionMemoryInfoKHR> {
    VkBindVideoSessionMemoryInfoKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkBindVideoSessionMemoryInfoKHR", ml, "VkBindVideoSessionMemoryInfoKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkBindVideoSessionMemoryInfoKHR_Ann * ann_VkBindVideoSessionMemoryInfoKHR = nullptr;
void VkBindVideoSessionMemoryInfoKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkBindVideoSessionMemoryInfoKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(memoryBindIndex)>("memoryBindIndex", "memoryBindIndex");
    addField<DAS_BIND_MANAGED_FIELD(memory)>("memory", "memory");
    addField<DAS_BIND_MANAGED_FIELD(memoryOffset)>("memoryOffset", "memoryOffset");
    addField<DAS_BIND_MANAGED_FIELD(memorySize)>("memorySize", "memorySize");
}
#endif

#if defined(VK_KHR_video_queue)
struct VkVideoPictureResourceInfoKHR_Ann : ManagedStructureAnnotation<VkVideoPictureResourceInfoKHR> {
    VkVideoPictureResourceInfoKHR_Ann(ModuleLibrary & ml) : ManagedStructureAnnotation("VkVideoPictureResourceInfoKHR", ml, "VkVideoPictureResourceInfoKHR") {}
    virtual bool isLocal() const override { return true; }
    virtual bool canCopy() const override { return true; }
    virtual bool canMove() const override { return true; }
    void init();
};
static VkVideoPictureResourceInfoKHR_Ann * ann_VkVideoPictureResourceInfoKHR = nullptr;
void VkVideoPictureResourceInfoKHR_Ann::init() {
    addField<DAS_BIND_MANAGED_FIELD(sType)>("sType", "sType");
    addFieldEx("pNext", "pNext", offsetof(VkVideoPictureResourceInfoKHR, pNext), makeType<void *>(*mlib));
    addField<DAS_BIND_MANAGED_FIELD(codedOffset)>("codedOffset", "codedOffset");
    addField<DAS_BIND_MANAGED_FIELD(codedExtent)>("codedExtent", "codedExtent");
    addField<DAS_BIND_MANAGED_FIELD(baseArrayLayer)>("baseArrayLayer", "baseArrayLayer");
    addField<DAS_BIND_MANAGED_FIELD(imageViewBinding)>("imageViewBinding", "imageViewBinding");
}
#endif

void das_vulkan_add_structs_15(Module & mod, ModuleLibrary & lib) {
#if defined(VK_EXT_vertex_input_dynamic_state)
    ann_VkVertexInputAttributeDescription2EXT = new VkVertexInputAttributeDescription2EXT_Ann(lib); mod.addAnnotation(ann_VkVertexInputAttributeDescription2EXT);
#endif
#if defined(VK_EXT_color_write_enable)
    ann_VkPhysicalDeviceColorWriteEnableFeaturesEXT = new VkPhysicalDeviceColorWriteEnableFeaturesEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceColorWriteEnableFeaturesEXT);
#endif
#if defined(VK_EXT_color_write_enable)
    ann_VkPipelineColorWriteCreateInfoEXT = new VkPipelineColorWriteCreateInfoEXT_Ann(lib); mod.addAnnotation(ann_VkPipelineColorWriteCreateInfoEXT);
#endif
#if defined(VK_VERSION_1_3)
    ann_VkMemoryBarrier2 = new VkMemoryBarrier2_Ann(lib); mod.addAnnotation(ann_VkMemoryBarrier2);
#endif
#if defined(VK_VERSION_1_3)
    ann_VkImageMemoryBarrier2 = new VkImageMemoryBarrier2_Ann(lib); mod.addAnnotation(ann_VkImageMemoryBarrier2);
#endif
#if defined(VK_VERSION_1_3)
    ann_VkBufferMemoryBarrier2 = new VkBufferMemoryBarrier2_Ann(lib); mod.addAnnotation(ann_VkBufferMemoryBarrier2);
#endif
#if defined(VK_KHR_maintenance8)
    ann_VkMemoryBarrierAccessFlags3KHR = new VkMemoryBarrierAccessFlags3KHR_Ann(lib); mod.addAnnotation(ann_VkMemoryBarrierAccessFlags3KHR);
#endif
#if defined(VK_VERSION_1_3)
    ann_VkDependencyInfo = new VkDependencyInfo_Ann(lib); mod.addAnnotation(ann_VkDependencyInfo);
#endif
#if defined(VK_VERSION_1_3)
    ann_VkSemaphoreSubmitInfo = new VkSemaphoreSubmitInfo_Ann(lib); mod.addAnnotation(ann_VkSemaphoreSubmitInfo);
#endif
#if defined(VK_VERSION_1_3)
    ann_VkCommandBufferSubmitInfo = new VkCommandBufferSubmitInfo_Ann(lib); mod.addAnnotation(ann_VkCommandBufferSubmitInfo);
#endif
#if defined(VK_VERSION_1_3)
    ann_VkSubmitInfo2 = new VkSubmitInfo2_Ann(lib); mod.addAnnotation(ann_VkSubmitInfo2);
#endif
#if defined(VK_NV_device_diagnostic_checkpoints)
    ann_VkQueueFamilyCheckpointProperties2NV = new VkQueueFamilyCheckpointProperties2NV_Ann(lib); mod.addAnnotation(ann_VkQueueFamilyCheckpointProperties2NV);
#endif
#if defined(VK_NV_device_diagnostic_checkpoints)
    ann_VkCheckpointData2NV = new VkCheckpointData2NV_Ann(lib); mod.addAnnotation(ann_VkCheckpointData2NV);
#endif
#if defined(VK_VERSION_1_3)
    ann_VkPhysicalDeviceSynchronization2Features = new VkPhysicalDeviceSynchronization2Features_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceSynchronization2Features);
#endif
#if defined(VK_KHR_unified_image_layouts)
    ann_VkPhysicalDeviceUnifiedImageLayoutsFeaturesKHR = new VkPhysicalDeviceUnifiedImageLayoutsFeaturesKHR_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceUnifiedImageLayoutsFeaturesKHR);
#endif
#if defined(VK_VERSION_1_4)
    ann_VkPhysicalDeviceHostImageCopyFeatures = new VkPhysicalDeviceHostImageCopyFeatures_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceHostImageCopyFeatures);
#endif
#if defined(VK_VERSION_1_4)
    ann_VkPhysicalDeviceHostImageCopyProperties = new VkPhysicalDeviceHostImageCopyProperties_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceHostImageCopyProperties);
#endif
#if defined(VK_VERSION_1_4)
    ann_VkMemoryToImageCopy = new VkMemoryToImageCopy_Ann(lib); mod.addAnnotation(ann_VkMemoryToImageCopy);
#endif
#if defined(VK_VERSION_1_4)
    ann_VkImageToMemoryCopy = new VkImageToMemoryCopy_Ann(lib); mod.addAnnotation(ann_VkImageToMemoryCopy);
#endif
#if defined(VK_VERSION_1_4)
    ann_VkCopyMemoryToImageInfo = new VkCopyMemoryToImageInfo_Ann(lib); mod.addAnnotation(ann_VkCopyMemoryToImageInfo);
#endif
#if defined(VK_VERSION_1_4)
    ann_VkCopyImageToMemoryInfo = new VkCopyImageToMemoryInfo_Ann(lib); mod.addAnnotation(ann_VkCopyImageToMemoryInfo);
#endif
#if defined(VK_VERSION_1_4)
    ann_VkCopyImageToImageInfo = new VkCopyImageToImageInfo_Ann(lib); mod.addAnnotation(ann_VkCopyImageToImageInfo);
#endif
#if defined(VK_VERSION_1_4)
    ann_VkHostImageLayoutTransitionInfo = new VkHostImageLayoutTransitionInfo_Ann(lib); mod.addAnnotation(ann_VkHostImageLayoutTransitionInfo);
#endif
#if defined(VK_VERSION_1_4)
    ann_VkSubresourceHostMemcpySize = new VkSubresourceHostMemcpySize_Ann(lib); mod.addAnnotation(ann_VkSubresourceHostMemcpySize);
#endif
#if defined(VK_VERSION_1_4)
    ann_VkHostImageCopyDevicePerformanceQuery = new VkHostImageCopyDevicePerformanceQuery_Ann(lib); mod.addAnnotation(ann_VkHostImageCopyDevicePerformanceQuery);
#endif
#if defined(VK_EXT_primitives_generated_query)
    ann_VkPhysicalDevicePrimitivesGeneratedQueryFeaturesEXT = new VkPhysicalDevicePrimitivesGeneratedQueryFeaturesEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDevicePrimitivesGeneratedQueryFeaturesEXT);
#endif
#if defined(VK_EXT_legacy_dithering)
    ann_VkPhysicalDeviceLegacyDitheringFeaturesEXT = new VkPhysicalDeviceLegacyDitheringFeaturesEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceLegacyDitheringFeaturesEXT);
#endif
#if defined(VK_EXT_multisampled_render_to_single_sampled)
    ann_VkPhysicalDeviceMultisampledRenderToSingleSampledFeaturesEXT = new VkPhysicalDeviceMultisampledRenderToSingleSampledFeaturesEXT_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceMultisampledRenderToSingleSampledFeaturesEXT);
#endif
#if defined(VK_KHR_present_id2)
    ann_VkSurfaceCapabilitiesPresentId2KHR = new VkSurfaceCapabilitiesPresentId2KHR_Ann(lib); mod.addAnnotation(ann_VkSurfaceCapabilitiesPresentId2KHR);
#endif
#if defined(VK_KHR_present_wait2)
    ann_VkSurfaceCapabilitiesPresentWait2KHR = new VkSurfaceCapabilitiesPresentWait2KHR_Ann(lib); mod.addAnnotation(ann_VkSurfaceCapabilitiesPresentWait2KHR);
#endif
#if defined(VK_EXT_multisampled_render_to_single_sampled)
    ann_VkSubpassResolvePerformanceQueryEXT = new VkSubpassResolvePerformanceQueryEXT_Ann(lib); mod.addAnnotation(ann_VkSubpassResolvePerformanceQueryEXT);
#endif
#if defined(VK_EXT_multisampled_render_to_single_sampled)
    ann_VkMultisampledRenderToSingleSampledInfoEXT = new VkMultisampledRenderToSingleSampledInfoEXT_Ann(lib); mod.addAnnotation(ann_VkMultisampledRenderToSingleSampledInfoEXT);
#endif
#if defined(VK_VERSION_1_4)
    ann_VkPhysicalDevicePipelineProtectedAccessFeatures = new VkPhysicalDevicePipelineProtectedAccessFeatures_Ann(lib); mod.addAnnotation(ann_VkPhysicalDevicePipelineProtectedAccessFeatures);
#endif
#if defined(VK_KHR_video_queue)
    ann_VkQueueFamilyVideoPropertiesKHR = new VkQueueFamilyVideoPropertiesKHR_Ann(lib); mod.addAnnotation(ann_VkQueueFamilyVideoPropertiesKHR);
#endif
#if defined(VK_KHR_video_queue)
    ann_VkQueueFamilyQueryResultStatusPropertiesKHR = new VkQueueFamilyQueryResultStatusPropertiesKHR_Ann(lib); mod.addAnnotation(ann_VkQueueFamilyQueryResultStatusPropertiesKHR);
#endif
#if defined(VK_KHR_video_queue)
    ann_VkVideoProfileListInfoKHR = new VkVideoProfileListInfoKHR_Ann(lib); mod.addAnnotation(ann_VkVideoProfileListInfoKHR);
#endif
#if defined(VK_KHR_video_queue)
    ann_VkPhysicalDeviceVideoFormatInfoKHR = new VkPhysicalDeviceVideoFormatInfoKHR_Ann(lib); mod.addAnnotation(ann_VkPhysicalDeviceVideoFormatInfoKHR);
#endif
#if defined(VK_KHR_video_queue)
    ann_VkVideoFormatPropertiesKHR = new VkVideoFormatPropertiesKHR_Ann(lib); mod.addAnnotation(ann_VkVideoFormatPropertiesKHR);
#endif
#if defined(VK_KHR_video_encode_quantization_map)
    ann_VkVideoEncodeQuantizationMapCapabilitiesKHR = new VkVideoEncodeQuantizationMapCapabilitiesKHR_Ann(lib); mod.addAnnotation(ann_VkVideoEncodeQuantizationMapCapabilitiesKHR);
#endif
#if defined(VK_KHR_video_encode_quantization_map)
    ann_VkVideoEncodeH264QuantizationMapCapabilitiesKHR = new VkVideoEncodeH264QuantizationMapCapabilitiesKHR_Ann(lib); mod.addAnnotation(ann_VkVideoEncodeH264QuantizationMapCapabilitiesKHR);
#endif
#if defined(VK_KHR_video_encode_quantization_map)
    ann_VkVideoEncodeH265QuantizationMapCapabilitiesKHR = new VkVideoEncodeH265QuantizationMapCapabilitiesKHR_Ann(lib); mod.addAnnotation(ann_VkVideoEncodeH265QuantizationMapCapabilitiesKHR);
#endif
#if defined(VK_KHR_video_encode_quantization_map)
    ann_VkVideoEncodeAV1QuantizationMapCapabilitiesKHR = new VkVideoEncodeAV1QuantizationMapCapabilitiesKHR_Ann(lib); mod.addAnnotation(ann_VkVideoEncodeAV1QuantizationMapCapabilitiesKHR);
#endif
#if defined(VK_KHR_video_encode_quantization_map)
    ann_VkVideoFormatQuantizationMapPropertiesKHR = new VkVideoFormatQuantizationMapPropertiesKHR_Ann(lib); mod.addAnnotation(ann_VkVideoFormatQuantizationMapPropertiesKHR);
#endif
#if defined(VK_KHR_video_encode_quantization_map)
    ann_VkVideoFormatH265QuantizationMapPropertiesKHR = new VkVideoFormatH265QuantizationMapPropertiesKHR_Ann(lib); mod.addAnnotation(ann_VkVideoFormatH265QuantizationMapPropertiesKHR);
#endif
#if defined(VK_KHR_video_encode_quantization_map)
    ann_VkVideoFormatAV1QuantizationMapPropertiesKHR = new VkVideoFormatAV1QuantizationMapPropertiesKHR_Ann(lib); mod.addAnnotation(ann_VkVideoFormatAV1QuantizationMapPropertiesKHR);
#endif
#if defined(VK_KHR_video_queue)
    ann_VkVideoProfileInfoKHR = new VkVideoProfileInfoKHR_Ann(lib); mod.addAnnotation(ann_VkVideoProfileInfoKHR);
#endif
#if defined(VK_KHR_video_queue)
    ann_VkVideoCapabilitiesKHR = new VkVideoCapabilitiesKHR_Ann(lib); mod.addAnnotation(ann_VkVideoCapabilitiesKHR);
#endif
#if defined(VK_KHR_video_queue)
    ann_VkVideoSessionMemoryRequirementsKHR = new VkVideoSessionMemoryRequirementsKHR_Ann(lib); mod.addAnnotation(ann_VkVideoSessionMemoryRequirementsKHR);
#endif
#if defined(VK_KHR_video_queue)
    ann_VkBindVideoSessionMemoryInfoKHR = new VkBindVideoSessionMemoryInfoKHR_Ann(lib); mod.addAnnotation(ann_VkBindVideoSessionMemoryInfoKHR);
#endif
#if defined(VK_KHR_video_queue)
    ann_VkVideoPictureResourceInfoKHR = new VkVideoPictureResourceInfoKHR_Ann(lib); mod.addAnnotation(ann_VkVideoPictureResourceInfoKHR);
#endif
}

void das_vulkan_fill_structs_15(Module & mod, ModuleLibrary & lib) {
#if defined(VK_EXT_vertex_input_dynamic_state)
    ann_VkVertexInputAttributeDescription2EXT->mlib = &lib; ann_VkVertexInputAttributeDescription2EXT->init(); ann_VkVertexInputAttributeDescription2EXT->mlib = nullptr;
#endif
#if defined(VK_EXT_color_write_enable)
    ann_VkPhysicalDeviceColorWriteEnableFeaturesEXT->mlib = &lib; ann_VkPhysicalDeviceColorWriteEnableFeaturesEXT->init(); ann_VkPhysicalDeviceColorWriteEnableFeaturesEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_color_write_enable)
    ann_VkPipelineColorWriteCreateInfoEXT->mlib = &lib; ann_VkPipelineColorWriteCreateInfoEXT->init(); ann_VkPipelineColorWriteCreateInfoEXT->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_3)
    ann_VkMemoryBarrier2->mlib = &lib; ann_VkMemoryBarrier2->init(); ann_VkMemoryBarrier2->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_3)
    ann_VkImageMemoryBarrier2->mlib = &lib; ann_VkImageMemoryBarrier2->init(); ann_VkImageMemoryBarrier2->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_3)
    ann_VkBufferMemoryBarrier2->mlib = &lib; ann_VkBufferMemoryBarrier2->init(); ann_VkBufferMemoryBarrier2->mlib = nullptr;
#endif
#if defined(VK_KHR_maintenance8)
    ann_VkMemoryBarrierAccessFlags3KHR->mlib = &lib; ann_VkMemoryBarrierAccessFlags3KHR->init(); ann_VkMemoryBarrierAccessFlags3KHR->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_3)
    ann_VkDependencyInfo->mlib = &lib; ann_VkDependencyInfo->init(); ann_VkDependencyInfo->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_3)
    ann_VkSemaphoreSubmitInfo->mlib = &lib; ann_VkSemaphoreSubmitInfo->init(); ann_VkSemaphoreSubmitInfo->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_3)
    ann_VkCommandBufferSubmitInfo->mlib = &lib; ann_VkCommandBufferSubmitInfo->init(); ann_VkCommandBufferSubmitInfo->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_3)
    ann_VkSubmitInfo2->mlib = &lib; ann_VkSubmitInfo2->init(); ann_VkSubmitInfo2->mlib = nullptr;
#endif
#if defined(VK_NV_device_diagnostic_checkpoints)
    ann_VkQueueFamilyCheckpointProperties2NV->mlib = &lib; ann_VkQueueFamilyCheckpointProperties2NV->init(); ann_VkQueueFamilyCheckpointProperties2NV->mlib = nullptr;
#endif
#if defined(VK_NV_device_diagnostic_checkpoints)
    ann_VkCheckpointData2NV->mlib = &lib; ann_VkCheckpointData2NV->init(); ann_VkCheckpointData2NV->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_3)
    ann_VkPhysicalDeviceSynchronization2Features->mlib = &lib; ann_VkPhysicalDeviceSynchronization2Features->init(); ann_VkPhysicalDeviceSynchronization2Features->mlib = nullptr;
#endif
#if defined(VK_KHR_unified_image_layouts)
    ann_VkPhysicalDeviceUnifiedImageLayoutsFeaturesKHR->mlib = &lib; ann_VkPhysicalDeviceUnifiedImageLayoutsFeaturesKHR->init(); ann_VkPhysicalDeviceUnifiedImageLayoutsFeaturesKHR->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_4)
    ann_VkPhysicalDeviceHostImageCopyFeatures->mlib = &lib; ann_VkPhysicalDeviceHostImageCopyFeatures->init(); ann_VkPhysicalDeviceHostImageCopyFeatures->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_4)
    ann_VkPhysicalDeviceHostImageCopyProperties->mlib = &lib; ann_VkPhysicalDeviceHostImageCopyProperties->init(); ann_VkPhysicalDeviceHostImageCopyProperties->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_4)
    ann_VkMemoryToImageCopy->mlib = &lib; ann_VkMemoryToImageCopy->init(); ann_VkMemoryToImageCopy->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_4)
    ann_VkImageToMemoryCopy->mlib = &lib; ann_VkImageToMemoryCopy->init(); ann_VkImageToMemoryCopy->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_4)
    ann_VkCopyMemoryToImageInfo->mlib = &lib; ann_VkCopyMemoryToImageInfo->init(); ann_VkCopyMemoryToImageInfo->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_4)
    ann_VkCopyImageToMemoryInfo->mlib = &lib; ann_VkCopyImageToMemoryInfo->init(); ann_VkCopyImageToMemoryInfo->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_4)
    ann_VkCopyImageToImageInfo->mlib = &lib; ann_VkCopyImageToImageInfo->init(); ann_VkCopyImageToImageInfo->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_4)
    ann_VkHostImageLayoutTransitionInfo->mlib = &lib; ann_VkHostImageLayoutTransitionInfo->init(); ann_VkHostImageLayoutTransitionInfo->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_4)
    ann_VkSubresourceHostMemcpySize->mlib = &lib; ann_VkSubresourceHostMemcpySize->init(); ann_VkSubresourceHostMemcpySize->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_4)
    ann_VkHostImageCopyDevicePerformanceQuery->mlib = &lib; ann_VkHostImageCopyDevicePerformanceQuery->init(); ann_VkHostImageCopyDevicePerformanceQuery->mlib = nullptr;
#endif
#if defined(VK_EXT_primitives_generated_query)
    ann_VkPhysicalDevicePrimitivesGeneratedQueryFeaturesEXT->mlib = &lib; ann_VkPhysicalDevicePrimitivesGeneratedQueryFeaturesEXT->init(); ann_VkPhysicalDevicePrimitivesGeneratedQueryFeaturesEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_legacy_dithering)
    ann_VkPhysicalDeviceLegacyDitheringFeaturesEXT->mlib = &lib; ann_VkPhysicalDeviceLegacyDitheringFeaturesEXT->init(); ann_VkPhysicalDeviceLegacyDitheringFeaturesEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_multisampled_render_to_single_sampled)
    ann_VkPhysicalDeviceMultisampledRenderToSingleSampledFeaturesEXT->mlib = &lib; ann_VkPhysicalDeviceMultisampledRenderToSingleSampledFeaturesEXT->init(); ann_VkPhysicalDeviceMultisampledRenderToSingleSampledFeaturesEXT->mlib = nullptr;
#endif
#if defined(VK_KHR_present_id2)
    ann_VkSurfaceCapabilitiesPresentId2KHR->mlib = &lib; ann_VkSurfaceCapabilitiesPresentId2KHR->init(); ann_VkSurfaceCapabilitiesPresentId2KHR->mlib = nullptr;
#endif
#if defined(VK_KHR_present_wait2)
    ann_VkSurfaceCapabilitiesPresentWait2KHR->mlib = &lib; ann_VkSurfaceCapabilitiesPresentWait2KHR->init(); ann_VkSurfaceCapabilitiesPresentWait2KHR->mlib = nullptr;
#endif
#if defined(VK_EXT_multisampled_render_to_single_sampled)
    ann_VkSubpassResolvePerformanceQueryEXT->mlib = &lib; ann_VkSubpassResolvePerformanceQueryEXT->init(); ann_VkSubpassResolvePerformanceQueryEXT->mlib = nullptr;
#endif
#if defined(VK_EXT_multisampled_render_to_single_sampled)
    ann_VkMultisampledRenderToSingleSampledInfoEXT->mlib = &lib; ann_VkMultisampledRenderToSingleSampledInfoEXT->init(); ann_VkMultisampledRenderToSingleSampledInfoEXT->mlib = nullptr;
#endif
#if defined(VK_VERSION_1_4)
    ann_VkPhysicalDevicePipelineProtectedAccessFeatures->mlib = &lib; ann_VkPhysicalDevicePipelineProtectedAccessFeatures->init(); ann_VkPhysicalDevicePipelineProtectedAccessFeatures->mlib = nullptr;
#endif
#if defined(VK_KHR_video_queue)
    ann_VkQueueFamilyVideoPropertiesKHR->mlib = &lib; ann_VkQueueFamilyVideoPropertiesKHR->init(); ann_VkQueueFamilyVideoPropertiesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_video_queue)
    ann_VkQueueFamilyQueryResultStatusPropertiesKHR->mlib = &lib; ann_VkQueueFamilyQueryResultStatusPropertiesKHR->init(); ann_VkQueueFamilyQueryResultStatusPropertiesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_video_queue)
    ann_VkVideoProfileListInfoKHR->mlib = &lib; ann_VkVideoProfileListInfoKHR->init(); ann_VkVideoProfileListInfoKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_video_queue)
    ann_VkPhysicalDeviceVideoFormatInfoKHR->mlib = &lib; ann_VkPhysicalDeviceVideoFormatInfoKHR->init(); ann_VkPhysicalDeviceVideoFormatInfoKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_video_queue)
    ann_VkVideoFormatPropertiesKHR->mlib = &lib; ann_VkVideoFormatPropertiesKHR->init(); ann_VkVideoFormatPropertiesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_video_encode_quantization_map)
    ann_VkVideoEncodeQuantizationMapCapabilitiesKHR->mlib = &lib; ann_VkVideoEncodeQuantizationMapCapabilitiesKHR->init(); ann_VkVideoEncodeQuantizationMapCapabilitiesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_video_encode_quantization_map)
    ann_VkVideoEncodeH264QuantizationMapCapabilitiesKHR->mlib = &lib; ann_VkVideoEncodeH264QuantizationMapCapabilitiesKHR->init(); ann_VkVideoEncodeH264QuantizationMapCapabilitiesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_video_encode_quantization_map)
    ann_VkVideoEncodeH265QuantizationMapCapabilitiesKHR->mlib = &lib; ann_VkVideoEncodeH265QuantizationMapCapabilitiesKHR->init(); ann_VkVideoEncodeH265QuantizationMapCapabilitiesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_video_encode_quantization_map)
    ann_VkVideoEncodeAV1QuantizationMapCapabilitiesKHR->mlib = &lib; ann_VkVideoEncodeAV1QuantizationMapCapabilitiesKHR->init(); ann_VkVideoEncodeAV1QuantizationMapCapabilitiesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_video_encode_quantization_map)
    ann_VkVideoFormatQuantizationMapPropertiesKHR->mlib = &lib; ann_VkVideoFormatQuantizationMapPropertiesKHR->init(); ann_VkVideoFormatQuantizationMapPropertiesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_video_encode_quantization_map)
    ann_VkVideoFormatH265QuantizationMapPropertiesKHR->mlib = &lib; ann_VkVideoFormatH265QuantizationMapPropertiesKHR->init(); ann_VkVideoFormatH265QuantizationMapPropertiesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_video_encode_quantization_map)
    ann_VkVideoFormatAV1QuantizationMapPropertiesKHR->mlib = &lib; ann_VkVideoFormatAV1QuantizationMapPropertiesKHR->init(); ann_VkVideoFormatAV1QuantizationMapPropertiesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_video_queue)
    ann_VkVideoProfileInfoKHR->mlib = &lib; ann_VkVideoProfileInfoKHR->init(); ann_VkVideoProfileInfoKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_video_queue)
    ann_VkVideoCapabilitiesKHR->mlib = &lib; ann_VkVideoCapabilitiesKHR->init(); ann_VkVideoCapabilitiesKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_video_queue)
    ann_VkVideoSessionMemoryRequirementsKHR->mlib = &lib; ann_VkVideoSessionMemoryRequirementsKHR->init(); ann_VkVideoSessionMemoryRequirementsKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_video_queue)
    ann_VkBindVideoSessionMemoryInfoKHR->mlib = &lib; ann_VkBindVideoSessionMemoryInfoKHR->init(); ann_VkBindVideoSessionMemoryInfoKHR->mlib = nullptr;
#endif
#if defined(VK_KHR_video_queue)
    ann_VkVideoPictureResourceInfoKHR->mlib = &lib; ann_VkVideoPictureResourceInfoKHR->init(); ann_VkVideoPictureResourceInfoKHR->mlib = nullptr;
#endif
}

}
