foreach(_var DASLANG ROOT OUT)
    if(NOT DEFINED ${_var})
        message(FATAL_ERROR "check_generated.cmake: -D${_var} is required")
    endif()
endforeach()
file(REMOVE_RECURSE "${OUT}")
file(MAKE_DIRECTORY "${OUT}/src" "${OUT}/daslib")
execute_process(COMMAND "${DASLANG}" modules/dasVulkan/generator/generate.das --
        --out "${OUT}/src" --boost-out "${OUT}/daslib" --skip-report "${OUT}/skip_report.txt"
    WORKING_DIRECTORY "${ROOT}" RESULT_VARIABLE _rc)
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "the generator failed (${_rc})")
endif()
set(_pairs "generator/skip_report.txt|skip_report.txt" "generator/copyability_report.txt|copyability_report.txt")
foreach(_dir src daslib)
    file(GLOB _files RELATIVE "${OUT}/${_dir}" "${OUT}/${_dir}/*")
    foreach(_f IN LISTS _files)
        list(APPEND _pairs "${_dir}/${_f}|${_dir}/${_f}")
    endforeach()
endforeach()
set(_stale "")
foreach(_pair IN LISTS _pairs)
    string(REPLACE "|" ";" _pair "${_pair}")
    list(GET _pair 0 _committed)
    list(GET _pair 1 _fresh)
    execute_process(COMMAND ${CMAKE_COMMAND} -E compare_files
        "${ROOT}/modules/dasVulkan/${_committed}" "${OUT}/${_fresh}" RESULT_VARIABLE _differs)
    if(_differs)
        execute_process(COMMAND git diff --no-index -- "${ROOT}/modules/dasVulkan/${_committed}" "${OUT}/${_fresh}")
        list(APPEND _stale ${_committed})
    endif()
endforeach()
if(_stale)
    message(FATAL_ERROR "the committed dasVulkan output differs from a fresh generator run: ${_stale}")
endif()
