if(TARGET libDasModuleAudio)
    add_executable(test_audio_playback_buffer test_playback_buffer.cpp)
    get_target_property(_audio_includes libDasModuleAudio INCLUDE_DIRECTORIES)
    target_include_directories(test_audio_playback_buffer PRIVATE ${_audio_includes})
    target_compile_features(test_audio_playback_buffer PRIVATE cxx_std_17)
    if(MSVC)
        target_compile_options(test_audio_playback_buffer PRIVATE /UNDEBUG)
    else()
        target_compile_options(test_audio_playback_buffer PRIVATE -UNDEBUG)
    endif()
    find_package(Threads REQUIRED)
    target_link_libraries(test_audio_playback_buffer PRIVATE Threads::Threads ${CMAKE_DL_LIBS})
    add_test(NAME audio_playback_buffer COMMAND test_audio_playback_buffer WORKING_DIRECTORY ${PROJECT_SOURCE_DIR})
    set_tests_properties(audio_playback_buffer PROPERTIES LABELS "small")
    add_dependencies(test-small test_audio_playback_buffer)
endif()
