foreach(_var DASLANG ROOT OUT)
    if(NOT DEFINED ${_var})
        message(FATAL_ERROR "index_sweep.cmake: -D${_var} is required")
    endif()
endforeach()
# -DPACKAGES_JSON=<file> sweeps a local index instead of the published one (the unit test's
# no-network route to the platform skip)
if(DEFINED PACKAGES_JSON)
    configure_file("${PACKAGES_JSON}" "${OUT}/packages.json" COPYONLY)
else()
    file(DOWNLOAD https://raw.githubusercontent.com/borisbat/daspkg-index/main/packages.json
        "${OUT}/packages.json" STATUS _status)
    list(GET _status 0 _code)
    if(NOT _code EQUAL 0)
        message(FATAL_ERROR "packages.json: ${_status}")
    endif()
endif()
file(READ "${OUT}/packages.json" _json)
if(CMAKE_HOST_WIN32)
    set(_host windows)
elseif(CMAKE_HOST_APPLE)
    set(_host darwin)
else()
    set(_host linux)
endif()
string(JSON _count LENGTH "${_json}")
math(EXPR _last "${_count} - 1")
string(TOLOWER "${CMAKE_HOST_SYSTEM_NAME}" _host)
set(_failed "")
set(_summary "")
foreach(_i RANGE ${_last})
    string(JSON _name GET "${_json}" ${_i} name)
    string(JSON _url GET "${_json}" ${_i} url)
    string(JSON _platforms ERROR_VARIABLE _any_platform GET "${_json}" ${_i} platforms)
    if(NOT _any_platform)
        string(JSON _nplatforms LENGTH "${_platforms}")
        set(_on_host FALSE)
        if(_nplatforms GREATER 0)
            math(EXPR _lastp "${_nplatforms} - 1")
            foreach(_p RANGE ${_lastp})
                string(JSON _pname GET "${_platforms}" ${_p})
                if(_pname STREQUAL _host)
                    set(_on_host TRUE)
                endif()
            endforeach()
        endif()
        if(NOT _on_host)
            string(APPEND _summary "| ${_name} | skipped - ${_host} is not among its platforms |\n")
            continue()
        endif()
    endif()
    string(REGEX REPLACE "^github.com/" "" _repo "${_url}")
    # an entry declaring platforms this host is not among is skipped, not installed: the
    # sweep exists for ABI breakage, and a package that never builds here cannot show it
    string(JSON _nplat ERROR_VARIABLE _noplat LENGTH "${_json}" ${_i} platforms)
    if(NOT _noplat AND _nplat GREATER 0)
        set(_plats "")
        set(_supported FALSE)
        math(EXPR _plast "${_nplat} - 1")
        foreach(_p RANGE ${_plast})
            string(JSON _plat GET "${_json}" ${_i} platforms ${_p})
            list(APPEND _plats ${_plat})
            if(_plat STREQUAL _host)
                set(_supported TRUE)
            endif()
        endforeach()
        if(NOT _supported)
            string(REPLACE ";" ", " _plats "${_plats}")
            message(NOTICE "skip ${_name}: ${_plats} only, this is ${_host}")
            string(APPEND _summary "| ${_name} | :fast_forward: ${_plats} only |\n")
            continue()
        endif()
    endif()
    execute_process(COMMAND git ls-remote --symref "https://${_url}" HEAD OUTPUT_VARIABLE _ls)
    string(REGEX MATCH "ref: refs/heads/([^\t\n]+)" _unused "${_ls}")
    set(_def "${CMAKE_MATCH_1}")
    if(_def STREQUAL "")
        message(NOTICE "::error::${_name}: cannot resolve default branch for ${_repo}")
        list(APPEND _failed ${_name})
        string(APPEND _summary "| ${_name} | :x: default-branch resolve failed |\n")
        continue()
    endif()
    message(NOTICE "::group::install ${_name} (${_repo} @ ${_def})")
    execute_process(COMMAND "${DASLANG}" utils/daspkg/main.das -- install ${_name} --branch ${_def}
        WORKING_DIRECTORY "${ROOT}" RESULT_VARIABLE _rc)
    if(_rc EQUAL 0)
        string(APPEND _summary "| ${_name} | :white_check_mark: ${_def} |\n")
    elseif(_rc EQUAL 3)
        # the manifest refused this host (daspkg exit 3) while the index entry did not say so:
        # the entry is stale until the next update-index, and the sweep does not fail on it
        string(APPEND _summary "| ${_name} | :fast_forward: manifest refuses ${_host}; index entry lacks platforms |\n")
    else()
        list(APPEND _failed ${_name})
        string(APPEND _summary "| ${_name} | :x: install failed (${_def}) |\n")
    endif()
    message(NOTICE "::endgroup::")
endforeach()
if(DEFINED ENV{GITHUB_STEP_SUMMARY})
    execute_process(COMMAND git rev-parse --short HEAD WORKING_DIRECTORY "${ROOT}"
        OUTPUT_VARIABLE _head OUTPUT_STRIP_TRAILING_WHITESPACE)
    file(APPEND "$ENV{GITHUB_STEP_SUMMARY}"
        "## daspkg-index sweep — $ENV{GITHUB_REF_NAME} @ ${_head}\n\n| package | status |\n|---|---|\n${_summary}")
endif()
if(_failed)
    message(FATAL_ERROR "FAILED: ${_failed}")
endif()
