foreach(_var DASLANG ROOT OUT)
    if(NOT DEFINED ${_var})
        message(FATAL_ERROR "index_sweep.cmake: -D${_var} is required")
    endif()
endforeach()
file(DOWNLOAD https://raw.githubusercontent.com/borisbat/daspkg-index/main/packages.json
    "${OUT}/packages.json" STATUS _status)
list(GET _status 0 _code)
if(NOT _code EQUAL 0)
    message(FATAL_ERROR "packages.json: ${_status}")
endif()
file(READ "${OUT}/packages.json" _json)
string(JSON _count LENGTH "${_json}")
math(EXPR _last "${_count} - 1")
set(_failed "")
set(_summary "")
foreach(_i RANGE ${_last})
    string(JSON _name GET "${_json}" ${_i} name)
    string(JSON _url GET "${_json}" ${_i} url)
    string(REGEX REPLACE "^github.com/" "" _repo "${_url}")
    execute_process(COMMAND git ls-remote --symref "https://${_url}" HEAD OUTPUT_VARIABLE _ls)
    string(REGEX MATCH "ref: refs/heads/([^\t\n]+)" _unused "${_ls}")
    set(_def "${CMAKE_MATCH_1}")
    if(_def STREQUAL "")
        message(NOTICE "::error::${_name}: cannot resolve default branch for ${_repo}")
        list(APPEND _failed ${_name})
        string(APPEND _summary "| ${_name} | :x: default-branch resolve failed |\n")
        continue()
    endif()
    message(NOTICE "::group::install ${_name} (${_repo} @ ${_def})")
    execute_process(COMMAND "${DASLANG}" utils/daspkg/main.das -- install ${_name} --branch ${_def}
        WORKING_DIRECTORY "${ROOT}" RESULT_VARIABLE _rc)
    if(_rc EQUAL 0)
        string(APPEND _summary "| ${_name} | :white_check_mark: ${_def} |\n")
    else()
        list(APPEND _failed ${_name})
        string(APPEND _summary "| ${_name} | :x: install failed (${_def}) |\n")
    endif()
    message(NOTICE "::endgroup::")
endforeach()
if(DEFINED ENV{GITHUB_STEP_SUMMARY})
    execute_process(COMMAND git rev-parse --short HEAD WORKING_DIRECTORY "${ROOT}"
        OUTPUT_VARIABLE _head OUTPUT_STRIP_TRAILING_WHITESPACE)
    file(APPEND "$ENV{GITHUB_STEP_SUMMARY}"
        "## daspkg-index sweep — $ENV{GITHUB_REF_NAME} @ ${_head}\n\n| package | status |\n|---|---|\n${_summary}")
endif()
if(_failed)
    message(FATAL_ERROR "FAILED: ${_failed}")
endif()
