foreach(_var DASLANG ROOT OUT)
    if(NOT DEFINED ${_var})
        message(FATAL_ERROR "stand.cmake: -D${_var} is required")
    endif()
endforeach()
separate_arguments(_args UNIX_COMMAND "${ARGS}")
function(git_line out)
    execute_process(COMMAND git ${ARGN} WORKING_DIRECTORY "${ROOT}" OUTPUT_VARIABLE _v OUTPUT_STRIP_TRAILING_WHITESPACE)
    string(REPLACE "\\" "\\\\" _v "${_v}")
    string(REPLACE "\"" "\\\"" _v "${_v}")
    set(${out} "${_v}" PARENT_SCOPE)
endfunction()
git_line(_sha rev-parse HEAD)
git_line(_date log -1 --format=%cI)
git_line(_subject log -1 --format=%s)
git_line(_author log -1 --format=%an)
string(SUBSTRING "${_sha}" 0 8 _short)
string(TIMESTAMP _stamp "%Y%m%dT%H%M%SZ" UTC)
string(TIMESTAMP _started "%Y-%m-%dT%H:%M:%SZ" UTC)
cmake_host_system_information(RESULT _host QUERY HOSTNAME)
cmake_host_system_information(RESULT _cores QUERY NUMBER_OF_LOGICAL_CORES)
set(_id "${_stamp}-${_short}")
file(MAKE_DIRECTORY "${OUT}/runs" "${OUT}/site")
file(WRITE "${OUT}/meta.json" "{\"run_id\":\"${_id}\",\"started\":\"${_started}\",\"commit\":{\"sha\":\"${_sha}\",\"date\":\"${_date}\",\"subject\":\"${_subject}\",\"author\":\"${_author}\"},\"machine\":{\"host\":\"${_host}\",\"cores\":${_cores}},\"build\":{\"status\":\"ok\"}}\n")
execute_process(COMMAND "${DASLANG}" utils/benchctl/main.das -- run --root . --meta "${OUT}/meta.json"
        --out "${OUT}/runs/${_id}.json" ${_args}
    WORKING_DIRECTORY "${ROOT}" RESULT_VARIABLE _run_rc)
execute_process(COMMAND "${DASLANG}" utils/benchctl/main.das -- report --runs "${OUT}/runs"
        --out-data "${OUT}/site/data.json" --repo-url https://github.com/GaijinEntertainment/daScript
    WORKING_DIRECTORY "${ROOT}" RESULT_VARIABLE _report_rc)
file(COPY "${ROOT}/utils/internal/bench-stand/site/index.html" "${ROOT}/utils/internal/bench-stand/site/app.js"
    "${ROOT}/utils/internal/bench-stand/site/style.css" DESTINATION "${OUT}/site")
file(CREATE_LINK ../runs "${OUT}/site/runs" SYMBOLIC)
if(NOT _run_rc EQUAL 0 OR NOT _report_rc EQUAL 0)
    message(FATAL_ERROR "bench stand: run exited ${_run_rc}, report exited ${_report_rc}")
endif()
