const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const test = require('node:test');
const files = new Map(), timers = new Map();
let timerId = 0;
const element = () => ({style:{},append(){},remove(){},setAttribute(){},addEventListener(){},focus(){},replaceChildren(){},getContext(){throw Error('No GPU in transport test');},width:640,height:480});
const canvas = element();
const context = {console:{warn(){},error(){}},window:{addEventListener(){}},document:{createElement:element,body:element(),getElementById(){return canvas},querySelector(){return canvas}},Module:{calledRun:true,FS:{mkdirTree(){},writeFile(path,value){files.set(path,value)},readFile(path){if(!files.has(path))throw Error('missing');return files.get(path)},analyzePath(path){return{exists:files.has(path)}},unlink(path){files.delete(path)}}},setTimeout(fn,delay){const id=++timerId;timers.set(id,{fn,delay});return id},clearTimeout(id){timers.delete(id)},navigator:{userAgent:'test',platform:'test'},location:{pathname:'/'},devicePixelRatio:1,performance:{now(){return 0}},Date,JSON};
vm.runInNewContext(fs.readFileSync(path.join(__dirname, '../web/live_capture.js'),'utf8'),context);
const api=context.window.dasLiveCapture;
function tick(delay){const pair=[...timers].find(([,x])=>x.delay===delay);assert.ok(pair);timers.delete(pair[0]);return pair[1].fn();}
test('capture transport correlates replies and accepts native requests', async()=>{
 await assert.rejects(api.restore({}),/not a live report/);
 const first=api.capture();const timedOut=assert.rejects(first,/20 seconds/);
 await assert.rejects(api.capture(),/already running/);
 const oldId=JSON.parse(files.get('/live-capture/request.json')).id;
 tick(20000);await timedOut;
 context.window.dasLiveCaptureBrowserInfo=()=>({custom:'fixture',history:[1,2]});
 const second=api.capture();const newId=JSON.parse(files.get('/live-capture/request.json')).id;
 files.set('/live-capture/response.json',JSON.stringify({id:oldId,operation:'capture',snapshot:{frame:1,build:'fixture'}}));
 await tick(80);
 assert.equal(api.current,null,'a timed-out reply must not replace the current report');
 files.set('/live-capture/response.json',JSON.stringify({id:newId,operation:'capture',snapshot:{frame:2,build:'fixture'}}));
 await tick(80);assert.equal((await second).snapshot.frame,2);assert.equal(api.current.browser.custom,'fixture');assert.equal(api.current.browser.history.length,2);assert.equal(files.has('/live-capture/response.json'),false);
 files.set('/live-capture/response.json',JSON.stringify({id:'button-3',operation:'capture',snapshot:{frame:3,build:'fixture'}}));
 await tick(80);assert.equal(api.current.snapshot.frame,3,'native UI capture remains available');
 context.window.dasLiveCaptureBrowserInfo=()=>{throw Error('metadata fixture failure');};
 files.set('/live-capture/response.json',JSON.stringify({id:'button-4',operation:'capture',snapshot:{frame:4,build:'fixture'}}));
 await tick(80);assert.equal(api.current.browser.user_agent,'test','metadata-provider failure retains built-in fallback');
 context.window.dasLiveCaptureImage=async()=>({kind:'fixture',data_url:'data:image/png;base64,YQ=='});
 const encoded=api.capture();const encodedId=JSON.parse(files.get('/live-capture/request.json')).id;
 files.set('/live-capture/response.json',JSON.stringify({id:encodedId,operation:'capture',snapshot:{frame:5},image:'fixture.png',timings:{artifact_ms:3}}));
 await tick(80);const encodedReport=await encoded;assert.equal(encodedReport.image.kind,'fixture');assert.equal(encodedReport.capture_timings.artifact_ms,3);
 context.window.dasLiveCaptureImage=async()=>{throw Error('encoder fixture failure');};
 const failed=api.capture();const failedId=JSON.parse(files.get('/live-capture/request.json')).id;
 files.set('/live-capture/response.json',JSON.stringify({id:failedId,operation:'capture',snapshot:{frame:6},image:'fixture.png'}));
 await tick(80);assert.equal((await failed).image,null,'encoder rejection preserves report');
 let finishImage;context.window.dasLiveCaptureImage=()=>new Promise(resolve=>{finishImage=resolve;});
 const slow=api.capture();const expired=assert.rejects(slow,/20 seconds/);const slowId=JSON.parse(files.get('/live-capture/request.json')).id;
 files.set('/live-capture/response.json',JSON.stringify({id:slowId,operation:'capture',snapshot:{frame:7},image:'slow.png'}));
 const unfinished=tick(80);tick(20000);await expired;
 const retry=api.capture();const retryId=JSON.parse(files.get('/live-capture/request.json')).id;
 files.set('/live-capture/response.json',JSON.stringify({id:retryId,operation:'capture',snapshot:{frame:8}}));
 await tick(80);assert.equal((await retry).snapshot.frame,8,'polling continues while an old encoder is suspended');
 finishImage({kind:'late'});await unfinished;assert.equal(api.current.snapshot.frame,8,'expired encoder cannot replace a newer capture');
 context.Module.calledRun=false;await assert.rejects(api.capture(),/still loading/);
});
