find_program(DAS_PYTHON NAMES python3 python)
if(NOT DAS_PYTHON)
    set(DAS_PYTHON python3)
endif()

function(das_lane_dastest_target name)
    cmake_parse_arguments(A "" "COMMENT" "FILES;JIT_FILES;COMPILE_ONLY_FILES;ARGS;DEPENDS" ${ARGN})
    set(_cmds)
    foreach(_f IN LISTS A_COMPILE_ONLY_FILES)
        list(APPEND _cmds COMMAND $<TARGET_FILE:daslang> ${PROJECT_SOURCE_DIR}/dastest/dastest.das -- --compile-only --color --failures-only --test ${PROJECT_SOURCE_DIR}/${_f} ${A_ARGS})
    endforeach()
    foreach(_f IN LISTS A_FILES)
        list(APPEND _cmds COMMAND $<TARGET_FILE:daslang> ${PROJECT_SOURCE_DIR}/dastest/dastest.das -- --color --failures-only --test ${PROJECT_SOURCE_DIR}/${_f} ${A_ARGS})
    endforeach()
    foreach(_f IN LISTS A_JIT_FILES)
        list(APPEND _cmds COMMAND $<TARGET_FILE:daslang> -jit ${PROJECT_SOURCE_DIR}/dastest/dastest.das -- --color --failures-only --test ${PROJECT_SOURCE_DIR}/${_f} ${A_ARGS})
    endforeach()
    add_custom_target(${name} ${_cmds} DEPENDS daslang ${A_DEPENDS}
        WORKING_DIRECTORY ${PROJECT_SOURCE_DIR} COMMENT "${A_COMMENT}")
endfunction()
