options gen2
options indenting = 4

module strudel shared

require strudel/strudel_event public
require strudel/strudel_time public
require strudel/strudel_pattern public
require strudel/strudel_synth public
require strudel/strudel_samples public
require strudel/strudel_scheduler public
require strudel/strudel_mini public
require strudel/strudel_midi public
require strudel/strudel_pianoroll public
