name: Microsoft C++ Code Analysis

on: [ workflow_dispatch ]

permissions:
  contents: read

jobs:
  analyze:
    env:
      CONFIG_DIR: '${{ github.workspace }}/build'
      
    permissions:
      contents: read
      security-events: write
      
    name: ${{ matrix.target }} - ${{ matrix.cmake_configuration }}
    runs-on: ${{ matrix.target }}

    strategy:
      fail-fast: false
      matrix:
        target: [ windows-latest ]
        cmake_configuration: [ Debug, Release ]

    steps:
    - uses: actions/checkout@v3
      
    - name: Configure CMake
      run: cmake -B ${{ env.CONFIG_DIR }} -DCMAKE_BUILD_TYPE:STRING=${{ matrix.cmake_configuration }} -G "Visual Studio 17 2022"
        
    - name: Build CMake
      run: cmake --build ${{ env.CONFIG_DIR }} --config ${{ matrix.cmake_configuration }}      
          
    - name: Initialize MSVC Code Analysis
      uses: microsoft/msvc-code-analysis-action@v0.1.1
      # Provide a unique ID to access the sarif output path
      id: run-analysis
      with:
        cmakeBuildDirectory: ${{ env.CONFIG_DIR }}
        buildConfiguration: '${{ matrix.cmake_configuration }}'
        # Ruleset file that will determine what checks will be run
        ruleset: CustomRules.ruleset

    # Upload SARIF file to GitHub Code Scanning Alerts
    - name: Upload SARIF to GitHub
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.run-analysis.outputs.sarif }}

    # Upload SARIF file as an Artifact to download and view
    - name: Upload SARIF as an Artifact
      uses: actions/upload-artifact@v3
      with:
        name: sarif-file
        path: ${{ steps.run-analysis.outputs.sarif }}
