foreach(_var DASLANG ROOT)
    if(NOT DEFINED ${_var})
        message(FATAL_ERROR "build_site_wasm.cmake: -D${_var} is required")
    endif()
endforeach()
set(_out "${ROOT}/web/output64/examples")

function(must)
    execute_process(COMMAND ${ARGN} WORKING_DIRECTORY "${ROOT}" RESULT_VARIABLE _rc)
    if(NOT _rc EQUAL 0)
        message(FATAL_ERROR "failed (${_rc}): ${ARGN}")
    endif()
endfunction()

function(build_playground result)
    file(MAKE_DIRECTORY "${ROOT}/web/build")
    execute_process(COMMAND emcmake cmake -DCMAKE_BUILD_TYPE=Release -G Ninja -DDAS_WASM_PTHREADS=ON ..
        WORKING_DIRECTORY "${ROOT}/web/build" RESULT_VARIABLE _rc)
    if(_rc EQUAL 0)
        execute_process(COMMAND ninja daslang_static stage_site_playground
            WORKING_DIRECTORY "${ROOT}/web/build" RESULT_VARIABLE _rc)
    endif()
    set(${result} ${_rc} PARENT_SCOPE)
endfunction()

function(release_wasm root what)
    execute_process(COMMAND "${DASLANG}" utils/daspkg/main.das -- release wasm --root "${root}" --out "${_out}"
        WORKING_DIRECTORY "${ROOT}" RESULT_VARIABLE _rc)
    if(_rc EQUAL 0)
        message(STATUS "${root} wasm build OK")
    else()
        message(WARNING "${root} wasm build failed - ${what} this deploy.")
    endif()
endfunction()

must(git clone --depth 1 --recurse-submodules https://github.com/borisbat/dasImguiImplot.git modules/dasImguiImplot)
must(git clone --depth 1 --recurse-submodules https://github.com/borisbat/dasImguiNodeEditor.git modules/dasImguiNodeEditor)
build_playground(_rc)
if(NOT _rc EQUAL 0)
    message(WARNING "imgui-family playground build failed - rebuilding plain threaded daslang_static; the furier + path_tracer_lab playground samples will not run this deploy.")
    file(REMOVE_RECURSE "${ROOT}/modules/dasImguiImplot" "${ROOT}/modules/dasImguiNodeEditor" "${ROOT}/web/build")
    build_playground(_rc)
    if(NOT _rc EQUAL 0)
        message(FATAL_ERROR "the plain playground build failed too (${_rc})")
    endif()
endif()
file(REMOVE_RECURSE "${ROOT}/modules/dasImguiImplot" "${ROOT}/modules/dasImguiNodeEditor")

must(emcmake cmake -S web -B web/build64 -G Ninja -DCMAKE_BUILD_TYPE=Release
    "-DDAS_WEB_OUTPUT_DIR=${ROOT}/web/output64" -DDAS_WASM_MEMORY64=ON -DDAS_WASM_PTHREADS=ON
    -DCMAKE_CXX_FLAGS=-sMEMORY64=1 -DCMAKE_C_FLAGS=-sMEMORY64=1 "-DDAS_HOST_DASLANG_OVERRIDE=${DASLANG}")
must("${DASLANG}" utils/daspkg/main.das -- build --wasm)

foreach(_g arcanoid pacman boulder-dash river_run)
    release_wasm("examples/games/${_g}" "its card falls back to interpreted")
endforeach()
foreach(_ex furier path_tracer_lab physarum_lab)
    release_wasm("examples/graphics/${_ex}" "its examples card will be skipped")
endforeach()
foreach(_ex storyteller storywish parrot)
    release_wasm("examples/dasLLAMA/${_ex}" "the dasllama.io ${_ex} page will be a placeholder")
endforeach()

set(_probe "${_out}/dlim_config")
execute_process(COMMAND "${DASLANG}" utils/daspkg/main.das -- release wasm --root examples/dasLLAMA/wasm/dlim_config --out "${_out}"
    WORKING_DIRECTORY "${ROOT}" RESULT_VARIABLE _rc)
if(_rc EQUAL 0)
    execute_process(COMMAND node dlim_config.js WORKING_DIRECTORY "${_probe}" OUTPUT_FILE "${_probe}/wasm64.json" RESULT_VARIABLE _rc)
endif()
if(_rc EQUAL 0)
    execute_process(COMMAND python3 -c [=[import json,sys; has_key = lambda o, k: isinstance(o, dict) and (k in o or any(has_key(v, k) for v in o.values())) or isinstance(o, list) and any(has_key(v, k) for v in o); sys.exit(0 if has_key(json.load(open(sys.argv[1])), "backend") else 1)]=] "${_probe}/wasm64.json"
        RESULT_VARIABLE _rc)
endif()
if(NOT _rc EQUAL 0)
    file(REMOVE "${_probe}/wasm64.json")
    message(NOTICE "::error::the wasm64 DlimConfiguration probe failed - no model set can be minted for either dasllama.io example; the deploy stops here so the previous pages stay up")
    message(FATAL_ERROR "the wasm64 DlimConfiguration probe failed")
endif()
message(STATUS "wasm64 DlimConfiguration probe OK")
