foreach(_var DASLANG ROOT)
    if(NOT DEFINED ${_var})
        message(FATAL_ERROR "check_playground_samples.cmake: -D${_var} is required")
    endif()
endforeach()
set(_dir "${ROOT}/web/examples/ui/samples/examples")
file(GLOB _samples "${_dir}/*.das" "${_dir}/*/main.das")
set(_failed "")
foreach(_f IN LISTS _samples)
    execute_process(COMMAND "${DASLANG}" -dry-run "${_f}" WORKING_DIRECTORY "${ROOT}"
        OUTPUT_VARIABLE _log ERROR_VARIABLE _log RESULT_VARIABLE _rc)
    if(NOT _rc EQUAL 0)
        file(RELATIVE_PATH _rel "${_dir}" "${_f}")
        list(APPEND _failed "${_rel}")
        message(NOTICE "--- ${_f} ---\n${_log}")
    endif()
endforeach()
if(_failed)
    message(NOTICE "::error::curated playground sample(s) no longer compile: ${_failed}")
    message(FATAL_ERROR "curated playground samples failed to compile")
endif()
message(STATUS "all curated samples compile")
